### ISSUE TITLE
GitHub Discussions 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#104]
**Summary** 
GitHub Discussions is new way for software communities to collaborate within a repository alongside issues and pull requests.

**Intended Outcome** 
The new discussions feature is a space built for your community to discuss their work, ask questions and help one another.

**How will it work?** 
Discussions live in your project repository, so they’re accessible where your community is already working together. Their threaded format makes it easy to start, respond to, and organize unstructured conversations. Questions can be marked as answered, so over time a community’s knowledge base grows naturally. And because discussions aren’t closed the way issues are, they can easily serve as a place for maintaining FAQs and other collaborative documentation. We recognize that community discussion is as much a part of development as coding, so discussion contributions appear in users’ contribution graphs.

**Comment by alexcnichols** [comment]
https://github.blog/changelog/2020-12-08-github-discussions-now-available-as-a-public-beta/
