### ISSUE TITLE
Scale and optimize highly active repositories

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#108]
**Summary** 
This work provides scalability improvements that reduce the chance of rate limits being triggered.

**Intended Outcome** 
Large engineering teams with monolithic apps or with mono-repos have engineering practices that create a large number of updates, pull requests, and continuous integration runs against a single repository. At scale, these highly active repositories encounter rate limits when attempting to push and merge code. 

**How will it work?** 
This work won't create any user visible changes other than the absence of rate limit errors.

**Comment by Sid-ah** [comment]
https://github.blog/2021-03-16-improving-large-monorepo-performance-on-github/
