### ISSUE TITLE
Git action events (e.g. clone and push) appear in the audit logs

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#109]
**Summary**
We are adding Git CLI activities to the audit log on Github Enterprise Cloud. This data will sit alongside events captured through the web interface to provide enterprise customers with a vastly expanded data set for security and compliance audits.

**Intended Outcome** 
Customers will be able to more fully observe UI and CLI activity on their account through the audit log. This will help customers to better meet administration, compliance, and security response needs.

**How will it work?**
Two new events, `git.clone` and `git.push`, will be incorporated alongside existing audit log events and available for search, export, and access via the API. The `git.clone` event will be recorded on clone, fetch, and pull.

**Comment by alexcnichols** [comment]
https://github.blog/changelog/2020-12-10-audit-log-git-events-and-rest-api-now-available-in-limited-public-beta/
