### ISSUE TITLE
GHES Cluster HA/DR

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#110]
**Summary**
We are enabling Enterprise Server cluster customers to provision a secondary cluster that is configured to asynchronously replicate from the primary. This will provide a high availability configuration for cluster setups. We are planning to ship this in the 2.22 release.

**Intended Outcome**
These changes will reduce upgrade time by enabling customers to eliminate backup and restore tasks from the upgrade process, and reduce Recovery Time Objectives (RTO) and Recover Point Objectives (RPO) by enabling failover. 

**How will it work?**
We will add support for a passive cluster replica. Customers will be able to break replication for upgrades, and manually trigger failover to the replica.

**Comment by alexcnichols** [comment]
https://enterprise.github.com/releases/2.22.0/notes
