### ISSUE TITLE
Role-based Access Control (RBAC) - Custom Roles with fine-grained repo permissions

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#111]
**Summary**
We are providing the ability for enterprises to define custom roles with a set of fine-grained repo permissions that can be assigned to teams and users when adding them to repositories. This functionality provides Role-based access control (RBAC) support in GitHub Enterprise.

**Intended Outcome**
Greater flexibility and granularity for administering repo permissions through RBAC.

**How will it work?**
An organization administrator will be able to create custom roles, that inherit from our existing built-in roles, and customize a set of permissions for that role. Then, when a user or team is added to a repo the repo admin can then specify that role, which provides them a default set of permission grants.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-10-27-enterprise-organizations-can-now-create-custom-repository-roles/
