### ISSUE TITLE
Open Source Documentation for docs.github.com

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#112]
#### Summary 
The open-source community loves to innovate. Open-sourcing docs.github.com will welcome new ideas from a huge and diverse group of people.

This Autumn, we'll be moving to an open-source contribution model for GitHub Docs. 

#### Intended Outcome 
We build a community around docs.github.com of people who are passionate about developer documentation. This community will help us keep docs up to date, recommend & improve examples, and maybe even contribute complete articles, guides or tutorials. 

#### How will it work? 
At a high level, we'll accept internal and community contributions. Internal contributions are restricted to hubbers only, primarily on the Docs team. The reason for this is because we need docs access that is restricted from public consumption for confidential releases. 

For community contributions, we envision three pathways: 
- Contributors making small bug fixes via PRs
- Contributors working closely with GitHub, via issues and PRs, to make medium-sized contributions, like new articles or overhauls to existing articles
- Contributors creating indexed content that utilizes platform content components

**Comment by alexcnichols** [comment]
https://github.blog/changelog/2020-10-07-github-docs-are-now-open-source/
