### ISSUE TITLE
Packages: containers supporting OCI, granular permissions, and anonymous downloads on GHES (Public Beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#118]
**Summary**
This feature tracks the GA release of containers improvements to Packages on [GHES]. GitHub Packages container support will be improved so you can more easily share containers in your organization, set granular access permissions, and anonymously access public container images. It will also implement the [OCI] standards for hosting [Docker] images.

**Intended Outcome**
Customers on GHES have access to the latest update of GitHub Packages. GitHub Packages encourages inner-sourcing by sharing containers across the organization, allows for better enforcement of access policies, and supports anonymously downloading public container images. Additionally, GitHub Packages container support is optimized for sharing layers between images across the entire organization making it faster and more cost-efficient.

**How will it work?**
For 3.5, we will enable these new capabilities with exposing a new package registry GitHub Container Registry for all customers with subdomain on. Going forward packages on GHES will align with the updates that rolled out on github.com customers will be migrated from current docker services.

[OCI]: https://www.opencontainers.org/ "Open Containers Initiative"
[CNAB]: https://cnab.io/
[Docker]: https://www.docker.com/
[GitHub Packages]: https://github.com/features/packages
[GHES]: https://github.com/enterprise

**Comment by spaltrowitz** [comment]
this has shipped to GHES 3.5 🚢 https://docs.github.com/enterprise-server@3.5/admin/release-notes#github-container-registry-in-public-beta

closing out this issue
