### ISSUE TITLE
Packages: containers supporting OCI, granular permissions, and anonymous downloads (GA)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#121]
**Summary**
GitHub Packages container support will be improved so you can more easily share containers in your organization, set granular access permissions, and anonymously access public container images. It will also implement the [OCI] standards for hosting [Docker] images.

**Intended Outcome**
GitHub Packages encourages inner-sourcing by sharing containers across the organization, allows for better enforcement of access policies, and supports anonymously downloading public container images. Additionally, GitHub Packages container support is optimized for sharing layers between images across the entire organization making it faster and more cost-efficient.

**How will it work?**
Administrators can create unique permissions for packages and developers can store OCI compliant containers.

[Packages: Container Registry (GA)]: https://github.com/github/roadmap-internal/issues/144
[Packages: Container Registry (Beta)]: https://github.com/github/roadmap-internal/issues/101
[Packages: Helm Charts (Beta)]: https://github.com/github/roadmap-internal/issues/119
[Packages: Helm Charts (GA)]:https://github.com/github/roadmap-internal/issues/163 
[Packages: Universal / Generic Storage (Beta)]:https://github.com/github/roadmap-internal/issues/112
[Packages: Universal / Generic Storage (GA)]:https://github.com/github/roadmap-internal/issues/164
[Packages: Swift registry (Beta)]:https://github.com/github/roadmap-internal/issues/93
[Packages: Swift registry (GA)]:https://github.com/github/roadmap-internal/issues/145

[GitHub Packages]: https://github.com/features/packages
[GHES]: https://github.com/enterprise
[Plans]: https://github.com/pricing

[Container]: https://en.wikipedia.org/wiki/Container_(abstract_data_type)
[OCI]: https://www.opencontainers.org/ "Open Containers Initiative"
[ORAS]: https://github.com/deislabs/oras
[CNAB]: https://cnab.io/
[CNCF]: https://www.cncf.io/
[Kubernetes]: https://kubernetes.io/
[Docker]: https://www.docker.com/
[npm]: https://www.npmjs.com/
[Swift]: https://swift.org/
[Swift Package Manager]:https://swift.org/package-manager/
[Helm Charts]: https://github.com/github/roadmap-internal/issues/119
[Helm Hub]: https://hub.helm.sh/
[Rust]: https://www.rust-lang.org/
[Go]: https://golang.org/
[Go modules]:https://blog.golang.org/using-go-modules
[PHP]: https://www.php.net/
[Composer]: https://getcomposer.org/
[Debian]: https://www.debian.org/
[Python]: https://www.python.org/
[PyPI]: https://pypi.org/

**Comment by kevingduck** [comment]
Shipped - https://github.blog/changelog/2021-06-21-github-packages-container-registry-is-generally-available/
