### ISSUE TITLE
GitHub Packages: Helm Chart support (beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#122]
**Summary**
This feature tracks the beta release of support for [Helm Charts] available through support of the [OCI] standards in GitHub Packages. 

**Intended Outcome**
You can store and manage your public and private [Helm Charts] as of [Helm 3.0](https://helm.sh/blog/helm-3-released/) in the GitHub Packages Container Registry alongside your containers and other packages. 

**How will it work?**
You can add your organization's Helm charts, search the organization for charts, and also install a chart.

```shell
helm create helm-test
helm package ./helm-test 

echo "$TOKEN" | helm registry login -u $USER --password-stdin https://ghcr.io
helm chart save helm-test/ ghcr.io/mona/helm-test:latest
helm chart push ghcr.io/mona/helm-test:latest
```

[Packages]: https://github.com/features/packages
[GHES]: https://github.com/enterprise
[Plans]: https://github.com/pricing

[Container]: https://en.wikipedia.org/wiki/Container_(abstract_data_type)
[OCI]: https://www.opencontainers.org/ "Open Containers Initiative"
[ORAS]: https://github.com/deislabs/oras
[CNAB]: https://cnab.io/
[CNCF]: https://www.cncf.io/
[Kubernetes]: https://kubernetes.io/
[Docker]: https://www.docker.com/
[npm]: https://www.npmjs.com/
[Swift]: https://swift.org/
[Swift Package Manager]:https://swift.org/package-manager/
[Helm Charts]: https://helm.sh/
[Helm Hub]: https://hub.helm.sh/
[Rust]: https://www.rust-lang.org/
[Go]: https://golang.org/
[Go modules]:https://blog.golang.org/using-go-modules
[PHP]: https://www.php.net/
[Composer]: https://getcomposer.org/
[Debian]: https://www.debian.org/
[Python]: https://www.python.org/
[PyPI]: https://pypi.org/

**Comment by ankneis** [comment]
This is no longer planned due to a change in our strategic priorities and the allocation of our resources towards higher-priority initiatives.
