### ISSUE TITLE
GitHub Packages: generic package support (beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#123]
**Summary**
This feature tracks the beta release of support for generic packages which allows customers to upload arbitrary file types to GitHub Packages and retrieve that data directly as files or folders. This is intended for packages that don't have an established client. Example uses are installers, audio files, video files, etc. that you would use with your service.

**Intended Outcome**
Some customers have arbitrary file types such as vendored binary components or proprietary file types that are used in their deployments. By supporting generic packages, GitHub Packages allows you to manage these assets alongside other packages and easily integrate into release workflows. It's easy to tag and version these assets such that they can be pulled into production environments.

**How will it work?**
You can use the [ORAS] client to push to the [OCI] artifacts storage with `oras push` and download it with `oras pull`.

[Packages]: https://github.com/features/packages
[GHES]: https://github.com/enterprise
[Plans]: https://github.com/pricing

[Container]: https://en.wikipedia.org/wiki/Container_(abstract_data_type)
[OCI]: https://www.opencontainers.org/ "Open Containers Initiative"
[ORAS]: https://github.com/deislabs/oras
[CNAB]: https://cnab.io/
[CNCF]: https://www.cncf.io/
[Kubernetes]: https://kubernetes.io/
[Docker]: https://www.docker.com/
[npm]: https://www.npmjs.com/
[Swift]: https://swift.org/
[Swift Package Manager]:https://swift.org/package-manager/
[Helm Charts]: https://helm.sh/
[Helm Hub]: https://hub.helm.sh/
[Rust]: https://www.rust-lang.org/
[Go]: https://golang.org/
[Go modules]:https://blog.golang.org/using-go-modules
[PHP]: https://www.php.net/
[Composer]: https://getcomposer.org/
[Debian]: https://www.debian.org/
[Python]: https://www.python.org/
[PyPI]: https://pypi.org/

**Comment by ankneis** [comment]
This is no longer planned due to a change in our strategic priorities and the allocation of our resources towards higher-priority initiatives.
