### ISSUE TITLE
Webhook Deliveries API (beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#125]
#### Summary
Webhooks are a key way for our integrators to be notified of predefined GitHub events, and power many key integrations for CI, static analysis, and more. Unfortunately webhooks may fail to be delivered for a variety of reasons: severed connections, downtime from GitHub, or downtime from the integrator. Right now, we offer the ability to view failed webhook deliveries in the UI and retry them, but we don't provide a similar set of functionality in our REST or GraphQL API.

The ability to systematically determine which webhooks have failed and redeliver them has been requested a number of times by our integrators. By adding such an API, our users would be able to enumerate webhook deliveries and retry the ones that failed as a result of transient errors, improving the experience for their users.

#### Intended Outcome 
High-volume integrators can now filter on delivery attempts in the last 30 days, read the status of a specific deliveries, and trigger a redelivery if needed.

#### How will it work? 
The webhook deliveries API will extend the repository, organization, and app-based endpoints to include functionality to get all deliveries, get a single delivery, and create a new delivery attempt for a given hook. The `get all deliveries` endpoint will provide parameters for filtering by date, status, event type, and redelivery attempt, as well as pagination parameters. If failed deliveries are identified, new delivery attempts can be created via the `create new delivery attempt` endpoint.

**Comment by Sid-ah** [comment]
Closing this issue in favor of [this one](https://github.com/github/roadmap/issues/196).
