### ISSUE TITLE
GHES: Webhook System Improvements

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#126]
**Summary**

The webhook events delivery system has been rearchitected for higher throughput, faster deliveries, and fewer delayed messages.

**Intended Outcome**

In single virtual machine installations of GitHub Enterprise Server, overall memory footprint will be reduced by 1 GB and overall CPU utilization will fall by 10%. Large installations of GitHub Enterprise Server may be able to slightly reduce the number of virtual CPUs and memory allocated, or increase the runway for scaled up usage of GitHub.

**How will it work?**

On GitHub.com, this feature was deployed in June 2020. On GitHub Enterprise Server, this feature is available in 2.22 by special request and 2.23 by default.

**Comment by Sid-ah** [comment]
https://docs.github.com/en/enterprise-server@3.0/admin/release-notes#administration-changes
