### ISSUE TITLE
Insights: Fully integrated dashboards & reports for GHEC

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#128]
**Summary** 
This release brings Insights analytics to GitHub Enterprise Cloud (GHEC) customers, and does so in a first-class, integrated manner.  Key metrics will be incorporated into the “Insights” views for both organizations and repositories, providing greater visibility into important measures of team process and productivity.  Bringing Insights into the core GitHub experience will also enable integration of charts and reports into project Readmes, issues, pull requests, and discussions. 

![image](https://user-images.githubusercontent.com/940508/94942631-94a63400-04a4-11eb-9049-5548f758c3cf.png)
_Artwork is for illustrative purposes.  Actual experience may differ at launch._

**Intended Outcome**
Integrating Insights into GHEC will enable more customers to begin tracking key productivity and process metrics.  Building the features into the core GitHub experience will make it easier for developers to see and use metrics in their daily workflows.  

**How will it work?**
Insights will provide key code review and collaboration metrics, as well as goals and benchmarks, integrated into the organization and repository “Insights” views.  Users can view metrics for all repositories and teams, or they can filter to specific projects/groups they are interested in.  Users can also integrate charts into existing markdown documents, including readme files, and in comments using integrated commands to select metrics and filter data.

**Comment by ankneis** [comment]
This work is not currently planned.
