### ISSUE TITLE
Insights: Enterprise Scale and Benchmarks for GHES

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#129]
**Summary** 

Insights provides research-backed metrics for teams who want to understand and improve their engineering velocity. This release:

1. **Greatly improves the scalability and performance** of Insights so even the largest enterprises can view reports, create goals, and track progress towards those goals.
2. **Introduces Industry Benchmarks** informed by a deep analysis of repositories, committers, code reviews, etc. across multiple industries. These benchmarks will allow teams to compare their own team’s progress to that of the GitHub community at large.

![image](https://user-images.githubusercontent.com/940508/94942524-6b85a380-04a4-11eb-9492-8c3ce41579ca.png)
_Artwork is for illustrative purposes.  Actual experience may differ at launch._

**Intended Outcome**

Improved scalability and performance will enable Insights for all GHES customers.  Benchmarks will help teams understand how they compare to other teams in the industry and facilitate better goal setting.

**How will it work?**

Insights will bring analytics to GHES customers through a standalone application that imports data from their GHES instance.  The Insights app provides a portal that contains key code review and collaboration metrics, as well as goals and benchmarks.  Users can view metrics for all repositories and teams, or they can filter to specific groups they are interested in.

**Comment by ankneis** [comment]
This is not currently planned.
