### ISSUE TITLE
Apps: Device Authorization Flow for OAuth

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#130]
**Summary**
OAuth Apps and GitHub Apps now support OAuth 2.0 Device Authorization Grant flows, in addition to the existing Web Application Flow.

**Intended Outcome**
Certain environments do not have a supported web browser or are headless with no user interface. Adding this authorization flow support allows these applications to make authorized calls to the GitHub API.

**How will it work?**
In the case of a developer tool like a CLI, the tool asks the user to navigate to https://github.com/login/device on a computer with a desktop browser and enter a code like `ABCD-EFGH`. In the background, the CLI tool polls GitHub every few seconds to see if it has been granted a token or been given an error. After this procedure is complete and the OAuth user grant flow is authorized, the CLI tool receives a token.

<img width="575" alt="Screen Shot 2020-06-08 at 10 42 09 AM" src="https://user-images.githubusercontent.com/526432/84062894-e9152900-a974-11ea-8819-42b862ba3ab7.png">

**Comment by alexcnichols** [comment]
https://github.blog/changelog/2020-12-04-oauth-2-0-device-authorization-flow-now-ga/
