### ISSUE TITLE
Mobile: Support for GHES

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#131]
**Summary**
[GitHub Mobile](https://github.com/mobile) extends support for [GHES](https://github.com/enterprise) (GitHub Enterprise Server).

**Intended Outcome**
GitHub Enterprise Server customers can use GitHub Mobile.

**How will it work?**
Developers will have the ability to sign into GitHub Enterprise Server accounts as well as a github.com account from the GitHub Mobile app on Android and iOS. If there are multiple accounts, developers can switch between active accounts. GitHub Mobile will only show features that the connected GHES instance supports.

**Comment by Sid-ah** [comment]
https://docs.github.com/en/enterprise-server@3.0/admin/release-notes#github-mobile-beta
