### ISSUE TITLE
Dependabot combined notifications emails

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#133]
#### Summary 
**Dependabot will send a combined notification, available for both email and web, for Dependabot alerts in mass notification situations.** That is: (a) per repo, when Dependabot is enabled on a repository, (b) per repo, when a new manifest file is committed, and (c) per user, when a new vulnerability is discovered.

Today, Dependabot alerts and Dependabot updates send a user individual web notifications and notifications emails for each Dependabot alert in their environment (though users can also [opt into a digest](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/configuring-notifications-for-vulnerable-dependencies#configuring-notifications-for-dependabot-alerts)). 

#### Intended Outcome 
To reduce the volume of notifications a user receives for Dependabot, and increase their read rate and usefulness.

#### How will it work? 
We will only send one notification for Dependabot alerts and PRs (for email and/or web) when:
* A repo enables Dependabot alerts and/or updates. This will be a repo-level summary.
* A repo changes a manifest file. This will be a repo-level summary.
* A new vulnerability is discovered. This will be a user-level summary, across all repos a user has access to.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-03-18-grouped-dependabot-alert-notifications/
