### ISSUE TITLE
Enterprise Verified Domains

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#137]
#### Summary 
Verified domains at the enterprise level on GitHub Enterprise Cloud.

#### Intended Outcome 
We enable [Organization owners to verify domains](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/verifying-your-organizations-domain), for various security reasons. 

Enterprise Cloud Accounts comprised of many organizations currently have to verify domains in each organization individually. This is an inefficiency for Enterprises with a handful of organizations, but can easily become a blocker for Enterprises with hundreds or thousands of organizations. 

The goal of this initiative is to empower the enterprise to manage their verified domains, and all downstream benefits.

#### How will it work? 
Enterprise administrators will be able to verify one or more domains and restrict email notifications to a domain. These restrictions will be inherited by organizations that belong to the Enterprise.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-03-08-enterprise-domain-verification-for-github-enterprise-cloud-is-generally-available/
