### ISSUE TITLE
Dependabot: grouped updates

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#148]
#### Summary 
Today, Dependabot generally sends one PR per package updated. Unfortunately, sometimes there are dependencies that ought to be updated together, and there's no way for developers to specify which ones. 

#### Intended Outcome 
To make Dependabot work better for developers and dependencies that need to be updated together. 

#### How will it work? 
We will allow developers to add configuration into their Dependabot.yml which lets them specify the set of dependencies that should be updated together.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/. Closing as complete!
