### ISSUE TITLE
Dependabot: Ecosystem updates Q1 2021

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#150]
#### Summary 
Updating ecosystem support for [Dependabot version updates](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-dependabot-version-updates), to newer versions of ecosystems.

#### Intended Outcome 
Allow users to stay on the latest version(s) of ecosystems, and reduce error rates in updates.

#### How will it work? 
Dependabot will support the latest version of these ecosystems:

- [x] npm v7
- [x] bundler v2
- [x] piptools 5.5

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-02-08-dependabot-npm-v7-support/

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-01-19-dependabot-pip-compile-5-5-0-support/
https://github.blog/changelog/2021-03-31-dependabot-bundler-v2-support/
