### ISSUE TITLE
Default opt-in and granular notification settings for security alerts

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#151]
#### Summary 
Make security alerts opt-in rather than opt-out, so that they are partching of 'All' but not part of 'Watching/mention' notification settings. As part of [custom notification controls](https://github.blog/changelog/2020-11-20-custom-notification-controls/), select whether to receive security alerts for a given repository. Security alerts include alerts for Dependabot, code scanning, and secret scanning.

#### Intended Outcome 
Have additional control over the types of notifications received for your repositories, and reduce noise where notifications are not desired.

#### How will it work? 
A user can select whether or not to receive security alerts as part of custom watching notifications.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-06-08-security-alert-notifications-are-now-opt-in/
