### ISSUE TITLE
Secret scanning: user defined patterns (server beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#159]
#### Summary 
Today, secret scanning in private repositories scans for a [list of secret types](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-secret-scanning#about-secret-scanning-for-private-repositories) with patterns written and maintained by GitHub. With this change, secret scanning users will be able to write their own patterns and be alerted of any instances of them in their existing codebase, or any time they are committed in future.

#### Intended Outcome 
Secret scanning users can scan for patterns specific to their organization, such as internal credentials, and for patterns that GitHub has not yet added support for.

#### How will it work? 
GitHub will provide a UI for secret scanning users to define custom patterns to scan for. This UI will be available at the enterprise, organization, and repo levels.

New and existing commits will be scanned for any instances of these patterns, and any findings will be surfaced as secret scanning alerts.

**Comment by Sid-ah** [comment]
https://docs.github.com/en/enterprise-server@3.2/admin/release-notes#3.2.0
