### ISSUE TITLE
Secret scanning: user defined patterns (cloud beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#160]
#### Summary 
Today, secret scanning in private repositories scans for a [list of secret types](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-secret-scanning#about-secret-scanning-for-private-repositories) with patterns written and maintained by GitHub. With this change, secret scanning users will be able to write their own patterns and be alerted of any instances of them in their existing codebase, or any time they are committed in future.

#### Intended Outcome 
Secret scanning users are able to scan for patterns specific to their organisation, such as internal credentials, or for patterns GitHub has not yet added support for.

#### How will it work? 
GitHub will provide a UI for secret scanning users to define custom patterns to scan for. Initially this UI will be available at the repo level, but it will quickly be extended to the organisation level.

New and existing commits will be scanned for any instances of these patterns, and any findings will be surfaced as secret scanning alerts.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-06-04-secret-scanning-now-supports-user-defined-patterns-on-private-repositories/
