### ISSUE TITLE
Actions: GitHub Actions on GitHub AE (Beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#163]
**Summary**
GitHub Actions is available in Beta on GitHub AE (GHAE).

**Intended Outcome**
GitHub AE Customers can now use a beta of GitHub Actions.

**How will it work?**
GitHub Actions on AE uses a new [AE hosted runner](https://docs.github.com/en/github-ae@latest/actions/using-github-hosted-runners/about-ae-hosted-runners), only available on GitHub AE, that enables you to customize the size, image, and networking configuration of the runners. These runners are a finished-service CI compute environment with auto-scaling and management done by GitHub. During the beta, the use of AE hosted runners is free of charge. For more information, see ["Adding AE hosted runners."](https://docs.github.com/en/github-ae@latest/actions/using-github-hosted-runners/adding-ae-hosted-runners).

**Comment by alexcnichols** [comment]
https://docs.github.com/en/github-ae@latest/admin/overview/github-ae-release-notes
