### ISSUE TITLE
Actions: Deployment branches Environment protection rule

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#164]
#### Summary
We are adding a new Environment protection rule that will let you define which branches are allowed to deploy to a specific Environment. 

#### Intended Outcome
Customers will have additional controls to prevent unreviewed code from being deployed into specific Environments

#### How will it work? 
When editing an Environment there will be an additional section under the Protection Rules where you can specify which branches can deploy to the Environment.  This list operates an an allow list and any job deploying to the environment from a  branch that does not match the rule will fail.

The setting will have three options:
* All - All branches in the repository
* Protected Branches - All branches matching the Branch Protection Rules for the repository
* Custom - A specific list of branch name patterns

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-06-22-github-actions-environments-environment-protection-rules-and-environment-secrets-are-generally-available/
