### ISSUE TITLE
Actions: Workflow run events appear in the Audit Log

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#165]
#### Summary 
We are adding workflow run activities to the audit log. This data will set alongside existing events to provide enterprise customers with a greatly expanded data set for security and compliance audits.

#### Intended Outcome 
Customers will be able to more fully observe GitHub Actions activity on their account through the audit log. This will help customers to better meet administration, compliance, and security response needs.

#### How will it work? 
New events will be incorporated into the audit log when:

* A workflow run is created, completed, deleted, or re-run
* A workflow job is scheduled. Importantly, this job will include the list of secrets that were provided to the runner
* A self-hosted runner's version is updated

In addition, the existing audit log event that is emitted when a self-hosted runner is registered will be updated to include the runner ID.

**Comment by alexcnichols** [comment]
https://github.blog/changelog/2021-02-23-github-actions-workflow-run-events-are-now-included-in-the-audit-log/
