### ISSUE TITLE
Push Protections (Beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#166]
#### Summary 

In highly regulated industries like banking, finance, healthcare, and government, customers often need to enforce compliance workflows at the point where changes are introduced to their code (on the Git push). And regardless of size or regulation, many customers implement standards like branch naming and commit messages, which also need to be intercepted on push.

Push protections will analyze incoming Git data for conformance to a set of customer-defined rules. If everything looks good, the change is allowed. If not, the push is rejected, and the pusher will have to address the problems before pushing again.

#### Intended Outcome 

GitHub already has branch protections to keep mainline clean. Push protections take those patterns and "shift them left", earlier in the process. Push protections can help keep unwanted file types, file names, commit messages, and branch names out of the repository completely. They can act as a fast filter making sure that, for example, each commit has an associated work item or that all commits are GPG signed.

In addition, for GitHub Enterprise Server customers, push protections are intended to eliminate the need to write and maintain most [custom pre-receive hooks](https://docs.github.com/en/enterprise-server/admin/policies/about-pre-receive-hooks). By making these protections native to GitHub, we can avoid performance overhead and bottlenecks.

#### How will it work? 

Much like branch protections, there will be a set of push protections that repository, organization, and enterprise administrators can opt into. When a developer pushes to the repo, if it fails any of the push protections, the developer will be notified and offered assistance in making the push conform.

The first round of push protections will cover validation of commit messages, committers, authors, branch names, file names, and file paths.

**Comment by alexcnichols** [comment]
This item has been closed in favor of more granular items to better represent what is coming:

- https://github.com/github/roadmap/issues/478
- https://github.com/github/roadmap/issues/477
- https://github.com/github/roadmap/issues/476
- and more!
