### ISSUE TITLE
Insights: Data Access APIs

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#168]
**Summary** 
Insights data access APIs are new APIs aimed at enterprise teams that need to include GitHub data in externally developed reports.  The APIs will provide data for artifacts such as commits, PRs, and issues in formats that facilitate report development in popular Business Intelligence (BI) tools.

**Intended Outcome**
Data access APIs will enable customers to more easily integrate GitHub data into custom BI reports.  Report developers will be able to use a single, consistent set of APIs to get data in a report-ready format.

**How will it work?**
As teams use GitHub for coding, issue tracking, CI/CD, etc, data about the usage is collected into the Insights platform for use in charts, reports, dashboards and other analytics features.  Once the data has been ingested and transformed into a format that's ready for reporting, the data will be available to be included in those 1st-party analytics features.  Following the ingestion and transformation, the analytics data will also be available through the APIs for use in external reports.

**Comment by ankneis** [comment]
This work is currently not planned.
