### ISSUE TITLE
Passkey support for strong, passwordless authentication 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#170]
#### Summary 

In August 2019, GitHub [added support for Web Authentication (WebAuthn) security keys](https://github.blog/2019-08-21-github-supports-webauthn-for-security-keys/), a shared standard for secure authentication on the web. WebAuthn allowed customers to use physical security keys, or in some specific cases, in-device biometric verification as a second factor when logging in to GitHub. At the time, [we wrote](https://github.blog/2019-08-21-github-supports-webauthn-for-security-keys/#the-future-of-authentication-secure-and-easy-to-use):

> Because platform support is not yet ubiquitous, GitHub currently supports security keys as a supplemental second factor. But we’re evaluating security keys as a primary second factor as more platforms support them. In addition, WebAuthn can make it possible to support login using your device as a “single-factor” security key with biometric authentication instead of a password. Although we’re not ready to announce further plans, we’ll continue to pursue ways to make secure authentication as easy as possible for everyone on GitHub.

With the release of the [passkeys standard](https://fidoalliance.org/passkeys/), we're excited to add support on GitHub.com for this next generation of unphishable credentials, and take a step towards a passwordless future. 

#### Intended Outcome 

1. Users can login from a using a passkey via their web browser
2. Users can confirm risky actions ("sudo") using a passkey via their web browser
3. Users can update their existing platform authenticator security keys (Touch ID, Face ID, Window Hello, etc) to function as passkeys
4. Users can skip entering their password using credential mediation with a passkey
5. Users can pass 2FA using a passkey

#### How will it work?

Once a passkey is registered, customers can log in to GitHub.com or confirm potentially risking actions through a biometric gesture or PIN, without needing to enter their password. Passkeys can be managed via the account security settings page.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-07-12-passkeys-public-beta/
