### ISSUE TITLE
GitHub AE Azure Active Directory (AAD) group sync support

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#172]
**Summary** 
Extends support for syncing Azure AD groups to GitHub teams in GitHub AE (GHAE).

**Intended Outcome**
This release syncs Azure AD with the teams you’ve set up on GitHub, so you can assign a set of access permissions to all the members of a group, instead of providing rights one by one. You’ll be able to assign one or more Azure AD groups to a team within GitHub and automatically keep membership synchronized in one, up-to-date place. In addition to speeding up administration, having just one place to manage users helps strengthen security and audit compliance.

**How will it work?** 
As per [our solution on GitHub.com](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-team-synchronization-for-your-organization), Azure AD groups will automatically sync to GHAE teams once the feature is enabled.

**Comment by Sid-ah** [comment]
https://docs.github.com/en/github-ae@latest/admin/overview/github-ae-release-notes
