### ISSUE TITLE
Dark mode support for GHES

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#173]
#### Summary 
After upgrading to GHES 3.2, dark mode is generally available with a seamless dark mode experience across GitHub. 

#### Intended Outcome 
Whether as a personal preference or as a way to reduce eye strain in low light conditions, dark mode gives developers more choice and flexibility in how and when they use GitHub.

#### How will it work? 
From the appearance settings page, a user is able to choose between default to system (matching OS preferences), light mode or dark mode for their preferred GitHub theme setting.

<img width="640" alt="dark mode GA" src="https://user-images.githubusercontent.com/33528647/108231428-c1837c80-710f-11eb-8c47-cd40a2ddd59a.png">

**Comment by Sid-ah** [comment]
https://docs.github.com/enterprise-server@3.2/admin/release-notes#dark-and-dark-dimmed-themes
