### ISSUE TITLE
High contrast themes beta

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#174]
<img width="1440" alt="high-contrast-mode_cropped" src="https://user-images.githubusercontent.com/33528647/108772251-c0e15080-752a-11eb-9392-6f4bf479809e.png">

_Note: Final design is subject to change_

#### Summary 
We are committed to making GitHub a more accessible and inclusive home for all developers. The high contrast theme will be available in both light and dark modes and was designed to increase the color contrast between background and foreground elements in order to meet or exceed WCAG 2.1 contrast requirements across GitHub.com. 

#### Intended Outcome 
GitHub.com is accessible to all developers: whether they experience low vision, another type of visual impairment, or simply prefer the increased legibility of higher contrast between elements.  

#### How will it work? 
From the [appearance settings](https://github.com/settings/appearance) page, a user is able to choose the high contrast theme as their preferred light, dark or default to system color mode.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-06-28-dark-high-contrast-theme-beta-for-github-com/
