### ISSUE TITLE
Dimmed theme

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#175]
![GitHub-dimmed-theme](https://user-images.githubusercontent.com/33528647/108391972-3b833680-71e0-11eb-8f2d-0327fd91c43c.png)

#### Summary 
After releasing our dark mode beta at Universe 2020, the [feedback from our community](https://github.community/t/dark-mode-theme-with-less-contrast/147845) to create a theme with less contrast was loud and clear. The dimmed theme will join dark mode as a new theme designed to reduce the contrast of the background and foreground elements in GitHub.com. 

#### Intended Outcome 
Whether as a personal preference or as a way to reduce contrast and strain on the eye for those who experience light sensitivity, GitHub's dimmed theme gives developers more choice and flexibility in how and when they use GitHub.

#### How will it work? 
From the [appearance settings](https://github.com/settings/appearance) page, a user is able to choose the dimmed theme as their preferred light, dark or default to system color mode.

**Comment by alexcnichols** [comment]
Shipped! 🚢   https://github.blog/changelog/2021-04-14-dark-and-dimmed-themes-are-now-generally-available/
