### ISSUE TITLE
Colorblind themes

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#176]
![Colorblind-theme-image](https://user-images.githubusercontent.com/33528647/108381993-5badf800-71d6-11eb-8423-2c2def288536.png)

#### Summary 
Color blindness affects approximately 1 in 12 men (8%) and 1 in 200 women in the world, with a majority impacted by the red/green color spectrum. As red and green have become ubiquitous indicators for status (open vs. closed, pass vs. failed) as well as for communicating warning or destructive action states, red/green colorblind users are forced use shape and iconography to interpret meaning from UI. This new theme swaps red and green across GitHub.com for orange and blue to make GitHub more inclusive for users with deuteranomaly color blindness.  

#### Intended Outcome 
Users with red/green color blindness are able to use GitHub.com with a theme that uses colors within their visible spectrum.

#### How will it work? 
From the [appearance settings](https://github.com/settings/appearance) page, a user is able to choose the deuteranomaly colorblind theme as their preferred light, dark or default to system color mode.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-09-29-colorblind-themes-beta
