### ISSUE TITLE
Dark mode theme GA

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#177]
<img width="640" alt="dark mode GA" src="https://user-images.githubusercontent.com/33528647/108231428-c1837c80-710f-11eb-8c47-cd40a2ddd59a.png">

#### Summary 
GitHub's dark mode is generally available to all customers with a seamless dark mode experience on github.com and GitHub Enterprise Cloud. 

#### Intended Outcome 
Whether as a personal preference or as a way to reduce eye strain in low light conditions, dark mode gives developers more choice and flexibility in how and when they use GitHub. 

#### How will it work? 
From the [appearance settings](https://github.com/settings/appearance) page, a user is able to choose between default to system (matching OS preferences), light mode or dark mode for their preferred GitHub theme setting.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-04-14-dark-and-dimmed-themes-are-now-generally-available/
