### ISSUE TITLE
GHES: Rename any branch of an existing repository

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#180]
#### Summary

Many communities, both on GitHub and in the wider Git community, are considering renaming the default branch name of their repository from `master`. We're making some updates to GitHub to make that process easier.

#### How will it work?

You'll be able to rename any branch, including the default branch, of an existing repository. The rename feature will take care of retargeting open pull requests and open releases, and will show your contributors a message to help them update their local copy of the repository after the rename.

![branch-rename-dialog](https://github.com/github/renaming/raw/main/rename-default-branch-dialog.png)

[Learn more at `github/renaming`](https://github.com/github/renaming/)

**Comment by Sid-ah** [comment]
- https://github.blog/changelog/2021-01-19-support-for-renaming-an-existing-branch/ 
- Shipped with [GHES 3.1](https://github.blog/changelog/2021-05-06-github-enterprise-server-3-1-is-available-as-a-release-candidate/)
