### ISSUE TITLE
Audit Log Git events and REST API GA

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#181]
#### Summary 
In https://github.com/github/roadmap-internal/issues/18 we added Git events (clone, fetch, and push) and a REST API to the GitHub Audit Log as a public beta. We will now bring this to GA.

#### Intended Outcome 
* REST API is GA for all GHEC customers. 
* All GHEC customers have access to the export Git events button
* Git exports button in Audit Log UI can accept exporting over the full 7 days of history (up to 100MB). 

#### How will it work? 
REST API and Git events will be GA for all GHEC customers.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-04-12-audit-log-git-events-and-rest-api-are-generally-available/
