### ISSUE TITLE
Enterprise and Organization Verified Domains on GHES

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#183]
#### Summary  

Enterprise verified domains have released to [general availability on GitHub Enterprise Cloud](https://github.blog/changelog/2021-03-08-enterprise-domain-verification-for-github-enterprise-cloud-is-generally-available/), augmenting the existing organization-level capability. We are now adding enterprise and organization verified domains to all of our enterprise offerings by adding support for GitHub Enterprise Server 3.2.

#### Intended Outcome 

Administrators for private GitHub deployments need to assure that email notification flow only goes to verified domains. While it is unlikely for email addresses that are out of compliance to be added to user profiles, this feature will provide demonstrable assurance to enterprise and organization owners that only specific domains will be eligible for notification delivery. Additionally, owners will be able to display the verified badge for internal domains that are accessible within the network boundary of the private GitHub deployment.

#### How will it work? 

Enterprise and organization owners will be able to verify domains and apply email notification restrictions at an enterprise or organization level for their private GitHub deployment. This will be done within enterprise and organization settings pages under the "verified domains" tab.

**Comment by Sid-ah** [comment]
https://docs.github.com/enterprise-server@3.2/admin/release-notes#approving-unverified-domains-for-email-notifications
