### ISSUE TITLE
Okta User & Group SCIM Support in GHAE

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#185]
#### Summary 
Enterprises using GHAE with Okta as their identity provider (IdP) will be able to manage automated user provisioning via SCIM (System for Cross Domain Identity Management).  Additionally, Enterprises will be able to sync team membership between Okta push groups and GitHub teams via SCIM. Enterprises will still be able to manually create teams and manage the membership of those teams manually in GHAE. GitHub teams that are linked to a push group are managed solely through Okta and cannot be edited manually on GHAE.

#### Intended Outcome 
Many pipeline customers for GHAE have thousands or tens of thousand users they will onboarding to the platform.  Additionally, these customers have hundreds of groups they use to organize these users in their IdP.  Today, these customers are forced to use the UI to create and manage team membership on GHAE.  For the majority of large GHAE customers, this is a non starter.  We are bringing Group SCIM to GHAE to allow these customers to manage the membership of their teams via Okta.

#### How will it work? 
Enterprises must first enable Okta SAML(Security Assertion Markup Language) and SCIM on their GHAE instance.  Next, they create their teams on GitHub and have their push groups setup in Okta (if not already setup previously). Organization owners are then able to connect teams in GitHub to push groups in Okta to manage membership.  These teams can then be assigned access to repositories on GHAE and assigned roles.

#### Links
- https://github.com/github/external-identities/issues/70

**Comment by alexcnichols** [comment]
Closing as shipped in GHAE 3.2.
