### ISSUE TITLE
Okta SAML SSO Support in GHAE

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#186]
#### Summary 
Enterprises using GHAE with Okta as their identity provider (IdP) will be able to enable SAML SSO for their GHAE instance. Username/password authentication is disabled when SAML SSO is enabled.

#### Intended Outcome 
[Potential customers](https://github.com/github/customer-feedback/issues/3606) that use Okta as their identity provider are blocked from using GHAE as we do not officially support Okta authentication.

#### How will it work? 
- Customers will be able to setup and enable SAML SSO with Okta for GHAE
- End Users will only be able to authenticate into their GHAE instance via SAML SSO.  Username/password authentication will be disabled.
- End Users will be unable to modify their name or email via their personal settings page

**Comment by alexcnichols** [comment]
Closing as shipped in GHAE 3.2.
