### ISSUE TITLE
Custom billing notifications

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#187]
#### Summary 
Today, GitHub sends email notifications when an account consumes 75%, 90%, and 100% of included usage and the spending limit amount. Custom billing notifications will allow customers to specify when a notification should be sent and to whom. 

#### Intended Outcome 
Billing notifications helps organizations stay on top of their usage so they can better plan and take action to avoid service disruptions and unwanted expenses. With custom notifications, customers can ensure the right stakeholders are alerted at the right time. 

#### How will it work? 
Customers can customize different notification thresholds and notification recipients.

**Comment by ankneis** [comment]
Closing this issue as it is outdated. We are currently focused on other priorities including building a billing platform that allows customers more visibility over their usage
