### ISSUE TITLE
SOC 1 and SOC 2, Type 2 Certifications for GHAE

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#189]
#### Summary 
SOC 1 and SOC 2, Type 2 Certifications for GitHub AE. 

#### Intended Outcome 
Customers who have requirements for SOC 1 and SOC 2 compliance for any services they use, will be able to use GitHub AE. Note that the period of performance for the initial SOC report will be less than 12 months, due to the product being new. Some customers require a full year's performance, which will be available in CY22.

#### How will it work? 
Any customer using GitHub AE will be assured of these certifications. They will be able to download relevant Azure SOC certificates from the [Microsoft Trust Centre](https://servicetrust.microsoft.com/Documents/ComplianceReports).

**Comment by ankneis** [comment]
🚢 Shipped as of 12/5!
