### ISSUE TITLE
Dependabot: Ecosystem updates Q2 2021

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#191]
#### Summary 
Updating ecosystem support for [Dependabot version updates](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-dependabot-version-updates), to newer versions of ecosystems.

This is a continuation of work from https://github.com/github/roadmap/issues/150.

#### Intended Outcome 
Allow users to stay on the latest version(s) of ecosystems, and reduce error rates in updates.

#### How will it work? 
Dependabot will support the latest version of these ecosystems:

- [x] pipenv 2020.11.15
- [x] terraform 0.14

**Comment by Sid-ah** [comment]
- https://github.blog/changelog/2021-06-10-dependabot-updated-pip-pip-tools-and-pipenv-support/
- https://github.blog/changelog/2021-06-10-dependabot-now-supports-terraform-1-0/
