### ISSUE TITLE
GHAE Status Page

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#192]
#### Summary 
Similar to GitHubstatus.com, we are launching a status page for GHAE at GHAEstatus.com.  The status page will report on the availability of GHAE services for each GHAE regions.

#### Intended Outcome 
The goal is to enable all GHAE users - both end users and administrators - to have a single source of accurate, live and real-time information on the status of GHAE regions. In the case of a service degradation, we hope that GHAE end users will initially check the status page before contacting their administrator. 

#### How will it work? 
GHAE customers will be able to see the availability of GHAE regions, broken down by core service. No specific customer information will be published. The page will look and operate in a very similar fashion to the [GitHub.com status page](https://www.githubstatus.com/).

Here is a mockup of the page design.

![Finalized design mockup](https://user-images.githubusercontent.com/34689779/114792982-3f45bc00-9d3e-11eb-98f2-de7bd5a8156e.png)

**Comment by ankneis** [comment]
🚢 Shipped!
