### ISSUE TITLE
CodeQL package manager (public beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#197]
#### Summary 

CodeQL is designed to query codebases for vulnerabilities. The queries to detect security problems are all [open source, and available in our GitHub repository](https://github.com/github/codeql). To further enable the security community to share their security knowledge, we've created the CodeQL packaging ecosystem. This enables security experts to create, share, depend on, and run CodeQL queries and libraries (much like `npm` for the JS/TS ecosystem). CodeQL packs will be available in the GitHub Package Registry (GHPR), and can easily be integrated into GitHub Code Scanning.

#### Intended Outcome 

CodeQL query and library authors can upload their packs to the GitHub Package Registry using the CodeQL CLI. Users of Code Scanning can integrate CodeQL packs into their CodeQL Action workflow. Users of the CodeQL CLI can fetch and run query packs, as well as express dependencies on CodeQL library packs.

#### How will it work? 

Under the hood, CodeQL packs are using GHPR's container registry: CodeQL packs are Docker containers in disguise. Users can enable CodeQL packs through Code Scanning, and further interact with packs through the [CodeQL CLI](https://github.com/github/codeql-cli-binaries/releases); there's no need to use the `docker` command.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-07-28-introducing-the-codeql-package-manager-public-beta/
