### ISSUE TITLE
CodeQL CLI: integrated support for uploading results to code scanning (from 3rd party CI systems)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#198]
#### Summary 

With the launch of Code Scanning, we also released the CodeQL Runner: a command-line tool that mimics functionality provided by the [CodeQL Action](https://github.com/github/codeql-action), especially for users of 3rd party CI systems. The functionality of the CodeQL runner will be migrated into the native [CodeQL CLI](https://github.com/github/codeql-cli-binaries/releases).  

#### Intended Outcome 

It will be much easier to set up CodeQL analysis for Code Scanning for those customers who rely on 3rd party CI/CD systems. Instead of downloading and installing an additional tool (the CodeQL Runner), customers can simply use the CodeQL CLI.

#### How will it work? 

The CodeQL CLI already has a [`codeql github upload-results` subcommand](https://github.blog/changelog/2021-03-12-codeql-code-scanning-improvements-for-users-analyzing-codebases-on-3rd-party-ci-cd-systems/), which replaces the corresponding [runner commands](https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-codeql-code-scanning-in-your-ci-system#codeql-runner-command-reference). We're working on multi-language support analysis and results upload, and multi-step build workflows support to get full feature parity between CodeQL Runner and CodeQL CLI.

**Comment by Sid-ah** [comment]
https://docs.github.com/enterprise-server@3.2/admin/release-notes#code-scanning-and-secret-scanning-changes
