### ISSUE TITLE
Actions: Custom deployment protection rules (gates)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#199]
#### Summary
Currently developers use the inbuilt [environment protection rules](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#environment-protection-rules) to require a manual approval, delay a job, or restrict the environment to certain branches.
We are now adding a new extensible mechanism to enable customers and partners to create their own custom protection rules to gate their deployments and make them more secure.

#### Intended Outcome 
Customers and partners can extend Environment protection rules to integrate with other services and control the promotion of deployments across environments.

#### How will it work? 
With the new custom deployment protection rules, you can create your own protection rules to use in your workflows or share the rules you build with the GitHub community.  Developers can find a suitable “protection rule”and enable it in their production and high valued environments.

**Comment by ankneis** [comment]
🚢 This has shipped! https://github.blog/changelog/2023-04-20-github-actions-create-and-share-your-own-deployment-protection-rules-for-safe-and-controlled-deployments. Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This has shipped with GHES 3.10: https://github.blog/2023-08-29-github-enterprise-server-3-10-is-now-generally-available/
