### ISSUE TITLE
GitHub pricing calculator 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#201]
#### Summary 
The pricing calculator is intended to help GitHub's users (new and existing) calculate the estimated cost for GitHub's consumptive services like Codespaces, Actions, Packages, and GitHub Advance Security. Users can create a custom price quote for the products offered through GitHub based on relevant criteria like number of users, frequency of use, and compute power for these services. Estimates can be shared with others by URL. In the future, we'll also add the ability to build estimates based on past use.

#### Intended Outcome 
We are building this to enable users to easily and conveniently estimate the cost of using GitHub services.

#### How will it work? 
The calculator will have a different section for each service. Within these sections we have designed a set of questions to help users estimate the cost of using the service. Artwork below provided as an example and may change for the actual implementation.

![image](https://user-images.githubusercontent.com/11078662/120750399-298d8100-c4bb-11eb-96df-24bfc32e73e7.png)

**Comment by Sid-ah** [comment]
https://github.com/pricing/calculator
