### ISSUE TITLE
Optional expiration for Personal Access Tokens (Cloud)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#203]
#### Summary 
Personal Access Tokens, or PATs, provide users with a quick way to create OAuth access tokens with they can use to make API calls. This is a typical way of getting API keys in SaaS products – PATs are broadly used today for needs that range from quick testing to automating workflows. However, PATs today do not offer an expiration option, meaning they exist until they are manually disabled.  Long-lived tokens (or, those with no expiration at all) can create larger security implications if they are to leak. Adding optional expiration to PATs increases both a user's and organization's ability to secure how their data is accessed.

#### Intended Outcome 
Users can create new PATs with optional expiry (specified at time of creation).

#### How will it work? 
Once introduced, the form for creating new PATs will have a new expiration field, allowing users to choose preset expiration intervals (7, 30, 60, 90 days from date of creation), a custom expiration date in the future, or no expiration. By default the shortest expiration interval will be chosen. The time and date of expiration will be returned in the response header when a PAT with expiration is used, and as the expiration of a PAT approaches, the owner will be notified by email in addition to a warning message in the [GitHub CLI](https://cli.github.com/) if it's being used. Once a token expires, it will be disabled and no longer be able to access GitHub APIs.

<img width="1440" alt="Default expiration" src="https://user-images.githubusercontent.com/1757782/120382044-0ce52380-c2d8-11eb-969b-02844ade5a2d.png">

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-07-26-expiration-options-for-personal-access-tokens/
