### ISSUE TITLE
[Server] Email notification restrictions for approved domains

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#204]
#### Summary 

Many companies want to be sure that email notifications are only being sent to approved and known corporate email addresses. This feature enables enterprise administrators to approve domains for email notifications on GitHub Enterprise Server. It will ship with GHES 3.2.

#### Intended Outcome 

Many enterprises have users with email addresses from different domains. This is especially common when working with consulting agencies or in joint projects with other businesses. The approved domains feature enables administrators to improve the security of their system and reduce the risk of corporate IP or source code being leaked through emails to non-corporate email addresses. 

#### How will it work? 

An enterprise or organization owner may approve a domain to be eligible for email notification restriction. Email notifications may then be restricted to selected verified or approved domains at an enterprise or organization level.

**Comment by Sid-ah** [comment]
https://docs.github.com/enterprise-server@3.2/admin/release-notes#approving-unverified-domains-for-email-notifications
