### ISSUE TITLE
Swift security analysis support in CodeQL code scanning (beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#206]
#### Summary 
CodeQL is the analysis engine that provides the vast majority of our code scanning results. We're planning to add Swift code analysis support in public beta.

#### Intended Outcome 

Looking at language popularity data on GitHub.com, Swift is a very popular language both within the open source community and with our enterprise customers — mostly for creating mobile apps for iOS. Building Swift support for CodeQL means that we'll be able to flag up security alerts in your Swift codebases.

#### How will it work? 
Analyzing Swift codebases with CodeQL in code scanning will work much the same as scanning other source code in languages that we already support. After you've set up CodeQL analysis in an Actions workflow on a Swift repository, the analysis job will be triggered as configured. As soon as the analysis is finished, the CodeQL results will then become visible to you in the "Security" tab and on pull requests.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-06-01-codeql-code-scanning-now-supports-swift-beta!

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This has shipped with GHES 3.10: https://github.blog/2023-08-29-github-enterprise-server-3-10-is-now-generally-available/
