### ISSUE TITLE
Email notification restrictions for approved domains beta

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#209]
#### Summary 

The verified domains functionality allows enterprise and organization owners the ability to restrict email notification flow to specific verified domains. This feature adds the flexibility to approve domains for email notification that cannot be expressly verified by the administration team. This will be available for GitHub Enterprise Cloud, and GitHub Enterprise Server.

#### Intended Outcome 

Many enterprises have users with email addresses from different domains. In some of these cases, the administration team does not have the ability to complete the domain verification flow. This is especially evident when working with consulting agencies or in joint projects with other businesses.

#### How will it work? 

Much like verified domains, an enterprise or organization owner may approve a domain to be eligible for email notification restriction. Email notifications may then be restricted to selected verified or approved domains at an enterprise or organization level.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-05-13-restricting-email-notifications-to-an-approved-domain-public-beta/
