### ISSUE TITLE
GHES: `main` becomes the default branch for new repositories

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#210]
#### Summary

Many communities, both on GitHub and in the wider Git community, are considering renaming the default branch name of their repository from `master`. GitHub is gradually renaming the default branch of all our repositories from `master` to `main`. We’re also making changes to GitHub Enterprise Server in a few phases, designed to cause as little disruption to existing projects as possible.

#### How will it work? 

In GHES 3.0 (see https://github.com/github/roadmap-internal/issues/259), you'll be able to set the default branch name used when a repository is created on your server. You'll be able to set this default for a particular user, for an organization, or for the entire GitHub Enterprise Server.

When you upgrade to GHES 3.2, this default will be set to `main`, unless you choose a different default while your server is running GHES 3.0.

[Learn more at `github/renaming`](https://github.com/github/renaming/)

**Comment by Sid-ah** [comment]
https://docs.github.com/enterprise-server@3.2/admin/release-notes#branches-changes
