### ISSUE TITLE
Limit who can approve or request changes to pull requests in open source projects

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#212]
### Summary

Currently, any user can approve or request changes to a pull request in an open source project even if they have no relationship to the project. This can be confusing both for that user and for the pull request author, who may think their changes were approved (or rejected). This can also be a source of frustration for open source maintainers.

A new moderation setting will let open source projects limit who can approve and request changes. Users can still review changes and submit comments, but will not be able to approve or request changes when enabled:

<img src="https://user-images.githubusercontent.com/2503052/124037401-80f51300-d9cd-11eb-952a-54d5d571f058.png" width="700px">

### Intended Outcome

Helps reduce the confusion caused when a user with no relationship to an open source project approves or requests changes to a pull request in that project.

### How will it work?

A new moderation setting will let open source project admins restrict "approve" and "request changes" reviews to certain types of users, similar to the options available for [interaction limits](https://docs.github.com/en/communities/moderating-comments-and-conversations/limiting-interactions-in-your-repository). For example:

![image](https://user-images.githubusercontent.com/2503052/124037506-aaae3a00-d9cd-11eb-8dd2-aeb07a162ad0.png)

When enabled, users can still review pull requests and submit comments, but will not be able to approve or request changes if they do not have the required relationship to the project.

**Comment by Sid-ah** [comment]
https://github.blog/2021-11-01-github-keeps-getting-better-for-open-source-maintainers/
