### ISSUE TITLE
Audit log API on GHAE and GHES

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#216]
### Summary

Following on from the [general availability announcement of the GHEC API](https://github.blog/changelog/2021-04-12-audit-log-git-events-and-rest-api-are-generally-available/) for this same purpose, we will ship the audit log APIs to GHAE and GHES. 

### Intended Outcome

The goal is to provide customers with the ability to interface with audit log data with the right tools based on the troubleshooting or investigative jobs to be done. Log forwarding provides customers with the ability to retain and analyze data with their own toolkit and determine patterns over time, while the API and UI provide the ability to analyze more specific events of note that have happened in recent history.

### How will it work?

We will ship the API with a similar [schema to GHEC](https://docs.github.com/en/organizations/keeping-your-organization-secure/reviewing-the-audit-log-for-your-organization#using-the-rest-api), but with additional data returned regarding the actor.

**Comment by spaltrowitz** [comment]
this has shipped to GHES and GHAE. closing out this issue 🚢
