### ISSUE TITLE
Updated billing overview page 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#217]
### Summary

The billing overview page will provide customers with a high-level overview for all things billing related: licensing, usage reports, and previous invoices. It will also include a chart showing the account's spending over this billing period and a usage forecast view.  

![image](https://user-images.githubusercontent.com/11078662/123352101-780aca00-d513-11eb-82ca-d83023adbbcd.png)

This UI update will be one of two releases intended to enhance the user experience for billing managers.

### Intended Outcome

The current billing overview page provides some info about usage in the enterprise account but focuses on the entitlements view and usage relative to it. The only way customers can view their actual usage beyond their entitlements is by downloading a CSV file and doing the calculations manually.  This release will provide dashboards and reports that allow billing administrators to view summary and detail data by service, org, repos and meter. 

### How will it work?

Customers will be able to: 

- View High-level overview of their current usage, licenses consumed and remaining, and previous invoices. 
- Understand credits available (if applicable)
- Understand the usage summary by organization, repo, and service 
- View their usage over this billing period including a usage forecast view
- Download a .csv report for all usage information in this page
- View existing budgets (spending limits)

**Comment by ankneis** [comment]
For more up-to-date information, please reference this roadmap issue: https://github.com/github/roadmap/issues/1031
