### ISSUE TITLE
Create a branch from an issue

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#218]
### Summary

The branch is the first thing a developer creates when the start working on a new issue. Creating that association makes it really easy for someone to then follow the work happening and keep everything connected as they take their idea to code.

### Intended Outcome

We want to help developers get started on work faster and signal to their team where to find the code changes related to an issue. It should also be really easy to then follow development to the pull request without the user needing to do additional work to link everything together.

### How will it work?

From the issue page, a user can quickly create a branch with an auto-generated or custom name that becomes associated with the issue. They can then fetch the branch and switch to it in their development environment and further development changes (such as commits and pull requests) are automatically associated with the issue.

**Comment by spaltrowitz** [comment]
:ship:  Shipped to dotcom! https://github.blog/changelog/2022-03-02-create-a-branch-for-an-issue/
