### ISSUE TITLE
Enterprise Managed Users (General Availability) 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#222]
### Summary

GitHub Enterprise Managed Users (EMUs) are a new type of user account aimed for professional use on GitHub Enterprise Cloud (GHEC). EMUs are provisioned and managed via an enterprise's identity provider (IdP), providing companies with user lifecycle control and enhanced security.

### Intended Outcome

Enterprises using EMUs can create user accounts for their employees via a linked IdP. Administrators are also able to manage user profile data, like display names and email addresses, as well as membership to GitHub teams through their IdP.

### How will it work?

After setting up a link between a GHEC account and a supported IdP, enterprises will be able to enable SAML (Security Assertion Markup Language) with SCIM (System for Cross-domain Identity Management) to manage the user provisioning lifecycle of EMUs. Once the EMU account is created, the user will be able to login to GitHub.com using single sign-on (SSO) and gain access to their provisioned organization(s).  EMU accounts will only be able to contribute (e.g. open issues, create pull requests) to repositories in organizations owned by their GitHub Enterprise Cloud account. EMUs will have read-only access to public repositories on GitHub.com, but will not be able to make contributions to public repos. Additionally, Enterprises using Azure Active Directory or Okta as their IdP will be able to use EMUs.

Membership to GitHub teams will also be managed through the enterprise's IdP. Administrators may add users to groups in their IdP and those groups memberships will be reflected on teams in the enterprise's organizations. Administrators are then able to add those teams to repositories and assign roles on GitHub. In addition, enterprise owners will be able to audit the activity of EMUs in their enterprise account.

**Comment by Sid-ah** [comment]
https://github.blog/2021-09-30-enterprise-managed-users-generally-available-github-enterprise-cloud/
