### ISSUE TITLE
Billing Usage API

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#246]
### Summary

Today, customers can access billing usage data via our in product UI and a CSV report. The current usage data displayed in the Billing UI isn't granular enough for many customers to gain relevant insights (such as identifying top spending repos) and pulling information from the CSV is very manual and time consuming. 

The billing usage API will allow Enterprise admins to programmatically access their Enterprise account's detailed billing and usage data so they can more easily understand their usage. 

### Intended Outcome

Customers can more easily analyze usage, create custom reports and integrate with existing BI tools.

### How will it work?

Enterprise Admins can retrieve the following information from our APIs:
- Total spend for Enterprise account
- Total entitlements usage for Enterprise account
- Total remaining prepaid credits for Enterprise account 
- Total spend and usage for Enterprise account by service
- Total spend and usage per org
- Total spend and usage per service per org / total spend per org per service
- Total spend and usage per service per repo / total spend per repo per service
- Total spend relative to budget (Actions/Packages and Codespaces)

_Under consideration:_
- Total enterprise licenses purchased & SKU type/plan (i.e. GHE, GHE-C, GHE-S, etc)
- Total enterprise licenses consumed by license type (standalone vs bundle) & state (accepted, pending, etc.)
- If Bundle licenses purchased, total licenses matched with VS subscribers

APIs will return data up to 180 days, customizable by the customer via parameter input with a default of 30 days.

**Example API call and response**

![image](https://user-images.githubusercontent.com/8868628/131002110-8ae41d64-fb0a-4430-a7c9-8094f931b575.png)

**Comment by ankneis** [comment]
Closing this issue as it is outdated - new plan for billing API work to be scoped soon.
