### ISSUE TITLE
Actions: Use actions from internal repositories on GHES 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#254]
### Summary

This feature enables workflows to use actions in internal repositories, without having to publish those actions to the GitHub Marketplace.

### Intended Outcome

Currently, to use an action in an Actions workflow its code must be in the same repository as the workflow, or a separate public repository, or published to the GitHub Marketplace. This feature allows Actions workflows to use actions that have their code in an internal repository, which is important for customers that need to keep the code of their action private.

### How will it work?

Users will be able to mark an internal repository as accessible to any workflow that exists in the same enterprise account.

**Comment by ankneis** [comment]
🚢 This feature shipped: https://docs.github.com/en/enterprise-server@3.5/admin/release-notes
