### ISSUE TITLE
Secret scanning GA on GitHub AE

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#266]
### Summary

In addition to GHEC and GHES, [secret scanning](https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning#about-secret-scanning-for-private-repositories) will now also be generally available on GHAE. Customers will have more options for secret scanning's configurability, expanded pattern coverage, improved false positive reduction, and more advanced features to secure their repositories.

Secret scanning has been in beta on GHAE since February 22nd.

### Intended Outcome

Customers using GitHub Advanced Security will now benefit from the general availability of secret scanning on GHAE. Improvements include performance updates and major new features like [user-defined patterns](https://docs.github.com/en/code-security/secret-scanning/defining-custom-patterns-for-secret-scanning).

### How will it work?

GHAE customers can enable secret scanning on repositories with GitHub Advanced Security.

**Comment by ankneis** [comment]
🚢 This has shipped: https://docs.github.com/en/github-ae@latest/admin/release-notes#github-advanced-security-features-are-generally-available
