### ISSUE TITLE
Secret scanning: dry-runs for user defined patterns (server)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#267]
### Summary

As testing tool, a dry-run scan will allow users to hone their custom regex patterns by determining the estimated number and quality of alerts generated for a specified pattern. This feature will be available on GHES 3.5 and follows editing support for custom patterns introduced in GHES 3.3.

### Intended Outcome

A poorly authored regular expression can spawn thousands of results across an organization or repository. Dry-run scans will allow users to prevent a bloat of results by testing their patterns before submission.

### How will it work?

Users can easily test their patterns before publishing at the repository and organization levels. The dry-run scan will provide users with an estimate of the number of alerts that their pattern would create if published, as well as a sample set of detected secrets in the relevant repositories.

**Comment by ankneis** [comment]
🚢 This has shipped: https://docs.github.com/en/enterprise-server@3.5/admin/release-notes
