### ISSUE TITLE
Secret scanning: dry-runs for user defined patterns (cloud)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#268]
### Summary

As a testing feature, a dry-run scan will allow users to hone their custom regex patterns by determining the estimated number and quality of alerts generated for a specified pattern.

### Intended Outcome

A poorly authored regular expression can spawn thousands of results across an organization or repository. Dry-run scans will allow users to prevent a bloat of results by testing their patterns before submission.

### How will it work?

When creating a custom pattern, users can easily test their patterns before publishing. A dry-run scan will provide users with an estimate of the number of alerts that their pattern would create if published, as well as a sample set of detected secrets in the relevant repositories.

**Comment by ankneis** [comment]
⛵ Repo level dry runs [shipped](https://github.blog/changelog/2022-02-11-secret-scanning-dry-runs-for-repository-level-custom-pattern)!

**Comment by spaltrowitz** [comment]
this has now shipped for GitHub Advanced Security customers! https://github.blog/changelog/2022-04-06-secret-scanning-custom-pattern-events-now-in-the-audit-log/
