### ISSUE TITLE
Secret scanning: user defined patterns (server GA)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#270]
### Summary

The user-defined patterns [beta launch](https://docs.github.com/en/enterprise-server@3.2/admin/release-notes) enabled users to customize their secret scanning experience. Users can write their own patterns to find existing and future matches in their codebase. From beta to GA, we'll introduce new experiences, such as the ability to edit.

### Intended Outcome

Users can customize secret scanning to search for patterns of interest to their organization, such as internal credentials, as well as other patterns not yet supported by GitHub. Users can view and edit these patterns at the organization and repository levels. 

### How will it work?

In the beta launch on GHES 3.2, GitHub introduced a UI for secret scanning users to define their custom patterns at the organization and repository levels. Now, that UI experience will also enable editing for those user-defined patterns. Other UI additions and UX improvements, such as clearer error messaging, will also enrich the overall experience for customers. 

The product will still scan new and existing commits for instances of these patterns and relay findings as secret scanning alerts.

**Comment by Sid-ah** [comment]
https://github.blog/2021-12-07-github-enterprise-server-3-3-is-generally-available/
