### ISSUE TITLE
Actions:  Cache support on GHES

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#273]
**Summary** 
GitHub Actions enables customers to cache intermediate outputs and dependencies for their workflows via the cache action. Current Caching support is available only for Dotcom. This feature tracks the effort to bring the support to GHES.

**Intended Outcome** (Why are we building it?)
- GitHub Actions enables customers to cache intermediate outputs and dependencies for their workflows. 
- Caching is an effective way to make jobs faster and would further promote the enterprise adoption of Actions. 

**How will it work?** (Short description of workflow/functionality)
We will now start supporting Caching in GHES SKUs.

**Comment by spaltrowitz** [comment]
this has shipped to GHES! https://docs.github.com/enterprise-server@3.5/admin/release-notes#cache-support-for-github-actions-on-github-enterprise-server-is-now-generally-available closing out this issue.
