### ISSUE TITLE
Projects: Roadmap Layout [Private Beta]

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#278]
### Summary

Users will be able to create a Roadmap view to visualize issues and their relationships across a timespan and track a body of work towards a deadline.

### Intended Outcome

Providing users with a Roadmap layout will allow them to plan and track their work over time and towards a deadline. It gives users a visual component to understand the timing and progress of their initiatives and communicate with stakeholders.

In addition to the table and board layout types, a roadmap layout will provide users with a visual at-a-glance view of their work items.

### How will it work?

When creating a new project or project view, a user will be able to select a Roadmap layout alongside the table and board layouts. This will populate their work items along a time-based axis.

[Join the waitlist](https://github.com/features/issues/signup) to try it out!

**Comment by ankneis** [comment]
🚢 This has shipped in a Private Beta. [Join the waitlist here!](https://github.com/features/issues/signup)!
