### ISSUE TITLE
Filter and Save Project Insights Burnup Chart

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#279]
## Summary

We have heard a ton of feedback from existing Insights users that the current overall project burnup chart is nice, it lacks the specificity that many needs require. 

This specificity usually has to do with filtering out the "noise" in the chart and focusing on what really matters to them. 

This release adds our filter bar to the Insights tab which will allow teams to slice and dice the data in the burnup chart the same way they do in project views. 

## Intended Outcome

We want to enable teams to be able to track the status of work items which matter to them, in the same way they track issues that matter to them in filtered project views. 

Some things we've heard from customers that this helps enable include: 

* Tracking Status by Iteration
* Tracking Status by Milestone 
* Tracking Status by Single Select field 
* Tracking Status by Repository Label
* etc. 

Our hypothesis is that providing this functionality on top of the existing burnup chart brings existing customers a significant amount of value without needlessly complicating Project Insights.

### Filtering the existing Projects Insights burnup chart

We are following the existing pattern for filtering which we use in Project Views, like so: 
![Screen Shot 2022-01-28 at 1 16 07 PM](https://user-images.githubusercontent.com/16281246/151600127-4aea4f66-adc1-40ce-acd2-bda6f2f9d76d.png)

Users will be able to filter the existing Project Insights burnup chart in a number of helpful ways, like so: 
![Screen Shot 2022-01-28 at 1 17 24 PM](https://user-images.githubusercontent.com/16281246/151600671-6d37136e-8378-40c3-a8ee-e81bcb8beccf.png)
![Screen Shot 2022-01-28 at 1 18 00 PM](https://user-images.githubusercontent.com/16281246/151600672-83fd0ebe-2c45-4e60-b8a2-dd134e9da94f.png)
![Screen Shot 2022-01-28 at 1 18 32 PM](https://user-images.githubusercontent.com/16281246/151600673-5a6f6540-c0d5-4131-a591-02b55a68ba96.png)

### Generating a burnup chart from an existing view 

Users will also be able to generate a burnup chart directly from View options, which will copy over any of the current filters over to a new Projects Insights burnup chart: 

![Screen Shot 2022-01-28 at 1 22 22 PM](https://user-images.githubusercontent.com/16281246/151601088-0043280b-c640-4a7b-b3b7-cf89e5b6b772.png)

### Saving a filtered burnup chart 
We have also added functionality which allows users to save the charts they have generated: 

![Screen Shot 2022-01-28 at 1 23 36 PM](https://user-images.githubusercontent.com/16281246/151601390-81d96178-2d2a-4609-a2dc-ee007068d95e.png)

**Comment by ankneis** [comment]
🚢 Shipped as of 2/2! https://github.blog/changelog/2022-02-02-the-new-github-issues-02-02-update/
