### ISSUE TITLE
Archiving items for Projects

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#280]
### Summary

As part of improving automation in your projects we will be adding in a new function to allow you to archive an item in projects.

**Comment by ankneis** [comment]
New automations [auto-archive](https://github.blog/changelog/2022-10-18-the-new-github-issues-october-18th-update/#%F0%9F%A7%B9-keep-your-project-tidy-with-auto-archive) and [auto-add](https://github.blog/changelog/2023-01-19-github-issues-january-19th-update/#%F0%9F%A4%96-automatically-add-project-items-enterprise-accounts-only) are now available to [everyone](https://github.blog/changelog/2023-03-09-github-issues-projects-march-9th-update/#robot-automatically-add-and-archive-project-items).

Stay tuned for additional automations such as `close an item when moved to done' which are planned for the future.
