### ISSUE TITLE
Daily experience improvements for Projects

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#283]
### Summary

We want to make sure that using projects on a day-to-day basis is a great experience. There are a number of these 'daily activities' that we want to make sure are possible, including:

- [x] Re-orderable views 
- [x] Group-by assignee and repos
- [x] Show linked pull requests
- [x] Team level permissions
- [x] Ability to filter by the `@current` iteration

This list is non-exhaustive and we expect to continue iterating and improving based on your feedback.

**Comment by alexcnichols** [comment]
Re-orderable views: 🚢 Shipped! https://github.blog/changelog/2021-11-18-the-new-github-issues-11-18-update/

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-11-18-the-new-github-issues-11-18-update/
https://github.blog/changelog/2021-12-02-the-new-github-issues-12-02-update/
https://github.blog/changelog/2021-12-16-the-new-github-issues-12-16-update/
