### ISSUE TITLE
Draft issue improvements for Projects (beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#285]
### Summary

This update to draft issues in projects (beta) will include support for a new side-panel, markdown bodies and the ability to add assignees. 

### Intended Outcome

These improvements to draft issues are designed to help with initial shaping of an idea. 

The new side panel (which will come to issues in the project board in the future) now includes the ability to add a markdown based body and shows all the custom fields present in the view. 

Editable within the table layout, draft issues now support assignees.

Converting a draft issue to an issue will include the markdown body and selected assignees. 

### How will it work?

![Changelog - draft issue v2 0e](https://user-images.githubusercontent.com/7584089/148214467-8eb0fcbd-1be6-4beb-8f54-5ba7efd51103.gif)

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-12-16-the-new-github-issues-12-16-update/
