### ISSUE TITLE
Projects beta parity with projects classic (milestone 1)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#287]
### Summary

In order to help teams migrate over from projects classic, we have a number of areas where we are working towards feature parity. In progress for this quarter are:

- [x] Ability to add outside collaborators  
- [x] Project descriptions
- [x] Index page search filters

**Comment by ankneis** [comment]
🚢 Partially shipped: https://github.blog/changelog/2022-02-02-the-new-github-issues-02-02-update/
