### ISSUE TITLE
Updates to our issue status icons and colors

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#289]
## Summary

Our current issue icon colors are a source of constant user feedback, citing confusion with errors, confusion between why Open is green and Closed is red, accessibility concerns and the general scariness of seeing red across the issues index page when a bunch of closed issues is usually a good thing.

Furthermore, customers also need a way to quickly differentiate issues that are closed because they are not going to be worked on vs. those that are closed after they are resolved (either by a PR being merged, or some other means). However we also have over 500M closed issues on GitHub that we cannot retroactively capture the intent as they were resolved.

In an effort to address the above feedback we are planning the following updates:

1. An issue will have three core statuses (`Draft`, `Open`, `Closed`), with each having a distinct icon. The `draft` status is already being introduced in the new GitHub Issues within projects and in the future will be possible to create them across the platform.
2. The issue closed icon will be updated **from red to purple**, addressing accessibility concerns, aligning with other icons in GitHub and addressing confusion we see today.
3. We will provide the capability to mark the resolution of an issue to differentiate between closing because it is not going to be worked on or closing because it is done. This will be rolled out later this quarter as we start a conversation with GitHub integrators and apps to see how they can best support this new functionality.

The following image shows the end state outlined above.

<img src="https://user-images.githubusercontent.com/884366/138879329-ba6ebfde-6965-438a-811d-eeb96c2e9ea4.png" width="320px" alt="Preview of the new issue status icons" />

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/
