### ISSUE TITLE
Audit log git events API in GHES

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#322]
### Summary

Following on from the addition of the complete REST API for audit log events in GHES in 3.3 in https://github.com/github/roadmap/issues/216, we will ship git events APIs to GHES in 3.5. This brings parity with the [REST API capabilities in GHEC](https://github.blog/changelog/2021-04-12-audit-log-git-events-and-rest-api-are-generally-available/). 

We will launch this feature with a configurable retention period for git events so that there is a limited and reasonable additional impact on GHES storage infrastructure by default.

### Intended Outcome

The goal is to provide customers with the ability to consume git events in the audit log alongside all other audit log data via the REST APIs.

### How will it work?

We will ship the API with a similar [schema to GHEC](https://docs.github.com/en/organizations/keeping-your-organization-secure/reviewing-the-audit-log-for-your-organization#using-the-rest-api). We will implement a default storage retention period for git events. For GHES, the retention period will be configurable by enterprise owners in the `compliance` tab of the enterprise overview.

**Comment by spaltrowitz** [comment]
this has shipped to GHES! https://docs.github.com/enterprise-server@3.5/admin/release-notes#git-events-in-the-enterprise-audit-log

leaving open to track to GHAE 3.5
