### ISSUE TITLE
Advanced Security (GHAS) committer-based billing license data export (GHES) 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#327]
### Summary

Customers will be able to export GitHub Advanced Security (GHAS) committer-based billing license data to gain better insights into their GHAS consumption data. This includes data on individuals (committers) who are counting towards the GHAS license, and total seat counts. This will be available in GitHub Enterprise Cloud (see separate roadmap item), as well as in GitHub Enterprise Server (GHES).

### Intended Outcome

Customers will understand GHAS committer-based billing calculations and have a better understanding of their GHAS consumption.  

### How will it work?

Users will be able to export user-level committer-based billing data.  This export will be available via the enterprise and organisation settings billing pages.

**Comment by ankneis** [comment]
🚢 This shipped with `GHES 3.4`: https://docs.github.com/enterprise-server@3.4/admin/release-notes#export-license-data-of-committer-based-billing-for-github-advanced-security
