### ISSUE TITLE
Code scanning: organization-level API for alerts (GHES)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#328]
### Summary

An external code scanning org-level API to review code scanning alerts at organization level.  

Users want to understand code scanning alerts across their organization, so that they can generate insights and better understand their overall security status.  Users want to address questions like _"which repositories have lots of code scanning alerts?"_, _"which repositories are not fixing their code scanning alerts?"_, and _"do different repositories have different types of alerts?"_.  The code scanning org-level API will allow users to review alerts at org-level and derive these insights. 

### Intended Outcome

The existing code scanning API is only available at repository level.  This makes it difficult for users to retrieve and understand code scanning alerts across an organization. 

### How will it work?

The code scanning org-level API will be a new API which will be available on Cloud and GitHub Enterprise Server (see separate roadmap item). The API will support one endpoint to retrieve all code scanning alerts.

**Comment by ankneis** [comment]
🚢 This has shipped to GHES 3.5 https://docs.github.com/enterprise-server@3.5/admin/release-notes#custom-repository-roles-are-generally-available
