### ISSUE TITLE
Secret scanning REST API surfaces location (server)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#329]
### Summary

In GHES 3.4, GitHub Advanced Security customers can retrieve commit details of secrets detected in private repository scans via the GitHub REST API. The new endpoint will surface the location of a secret's first detection within a file as well as the commit author.

### Intended Outcome

Security teams often need more context on a detected secret to take appropriate action and secure their repos. Enabling these teams to better track exposed credentials with information on commit location facilitates a more efficient remediation process.

### How will it work?

Enterprise customers upgraded to GHES 3.4 can access the new endpoint.

**Comment by alexcnichols** [comment]
Shipped on [cloud](https://github.blog/changelog/2021-12-01-secret-scanning-rest-api-now-surfaces-locations/) and [GHES 3.4](https://docs.github.com/enterprise-server@3.4/admin/release-notes#secret-scanning-rest-api-now-returns-locations)
