### ISSUE TITLE
Fork a repository to the same organization as its parent

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#330]
### Summary

This feature will allow a repository to be forked to the same organization as its parent repository, addressing situations where users work in a single organization and don't want their repositories to be forked to other organizations or user accounts.

### Intended Outcome

Users operating within a single GitHub organization face challenges collaborating on private repositories. When a member of the organization wants to contribute to a repository, they have two options:

1. **Create a branch in the repository:** This is a challenge for users who don't have write access to create a branch and repository owners are wary of granting that permission.

2. **Fork the repository:** This is a challenge because repositories can't be forked within a single organization. Users often resort to forking to a different organization or their personal account which can be undesirable for private repositories.

### How will it work?

We'll address this by adding support for forking repositories within a single organization as shown in this mock-up:

<img src="https://user-images.githubusercontent.com/1767415/135889902-bfb6784d-3f8a-4397-abf3-48bcd4aef315.png" height="300" />

In this mock-up, the repository's visibility (private) is shown, you can choose to fork to the same organization as the parent repository, and the fork's name can be customized to avoid conflicting with the parent repository's name.

**Comment by spaltrowitz** [comment]
this has shipped to dotcom! 🚢 https://github.blog/changelog/2022-06-27-improved-innersource-collaboration-and-enterprise-fork-policies/ closing out this issue.
