### ISSUE TITLE
Link code scanning alerts to issues (public beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#332]
### Summary

Code scanning alerts will integrate with GitHub issues task lists to let users create a "tracked in" relationship.  This will ship as public beta on cloud.

### Intended Outcome

Issues are the core work queue management at GitHub. Currently, code scanning alerts are managed through a separate interface and so sit outside of the existing developer work queue. This can mean that code scanning alerts can be missed, not prioritised, and a backlog of alerts grows and becomes stale. Creating this relationship includes code scanning alerts in the existing developer work queue, ensuring that they are triaged, prioritised and actioned.

### How will it work?

Users will be able to use code scanning alerts in issues task lists to create a "tracked in" relationship. The functionality follows the design of the "tracked issues" behaviour for a consistent experience. Users will also be able to create a new issue from an alert, which automatically populates body content and adds the alert to a task list in the issue.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-11-10-track-code-scanning-alerts-in-github-issues-using-task-lists/
