### ISSUE TITLE
Codespaces: Devcontainer composer

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#335]
### Summary

Crafting a devcontainer can require venturing into unfamiliar territory or cumbersome scripting. Today, users can [add a devcontainer configuration in VS Code](https://docs.github.com/en/codespaces/customizing-your-codespace/configuring-codespaces-for-your-project#using-a-predefined-container-configuration) with some options. Improving this composer will allow users to generate the right configuration files (devcontainer.json + Dockerfile) by selecting easy to understand components for their base image, runtimes, and tools.

### Intended Outcome

Building a devcontainer configuration for a repo is necessary to optmize the experience with Codespaces; however, not everyone is a devcontainer expert and even familiar users benefit from well-defined, commonly used configurations. With a lightweight composer, users can focus on what they need in their container while abstracting the complexity of figuring out how all the pieces fit together in the config file.

Allowing users to generate and share their own components also enables us to support a wide range of community and enterprise needs. For example, an enterprise could build a component to install internal tooling as part of their config and end-users don’t have to worry about how to incorporate this installation into their configuration.

### How will it work?

1. There will be a small set of maintained components that users can optionally add to their devcontainer via the `Add dev container configuration...` flow or ` Configure container features` command in VS Code. These features include things like the GitHub CLI and Docker-in-Docker support for the container.
2. Users can create and reference their own components - allowing them to reuse these pieces across their various configurations and share core pieces with others.
3. Components can be published to a registry whereby users can search for a specific component they need and add it to their configuration without needing to understand how to build the component.

**Comment by Sid-ah** [comment]
https://docs.github.com/en/codespaces/customizing-your-codespace/configuring-codespaces-for-your-project#adding-additional-fe[…]evcontainerjson-file
