### ISSUE TITLE
Command Palette

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#336]
### Summary

![demo of navigating between organizations and using the theme switcher command with the command palette](https://user-images.githubusercontent.com/33528647/138329062-c54f0651-d4cd-4f29-83a0-a1786660a33a.gif)

The Command Palette is a new GitHub surface designed to improve how users navigate around GitHub and execute time saving commands. Jump to your organizations and repositories quickly, and search within them for pull requests, issues, projects, files, and more. Execute commands to optimize your workflows, all without lifting your hands from the keyboard. 

### Intended Outcome

The command palette gives new users and super fans alike a new way to cut down on the time necessary to navigate GitHub and execute commands for common workflows. 

### How will it work?
Open the command palette using one of the following keyboard shortcuts:
- Windows and Linux: <kbd>Ctrl</kbd><kbd>k</kbd> or <kbd>Ctrl</kbd><kbd>alt</kbd><kbd>k</kbd> 
- Mac: <kbd>⌘</kbd><kbd>k</kbd> or <kbd>⌘</kbd><kbd>option</kbd><kbd>k</kbd>

Use modes to find specific types of resources: 
   - <kbd>#</kbd> Search for issues, pull requests, discussions, and projects
   - <kbd>!</kbd> Search for projects
   - <kbd>@</kbd> Search for users, organizations, and repositories
   - <kbd>/</kbd> Search for files within a repository scope 

For more information, review [command palette documentation](https://docs.github.com/en/get-started/using-github/github-command-palette).

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-10-27-command-palette-beta/
