### ISSUE TITLE
IP address disclosure in audit log events in GHEC

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#345]
### Summary

Disclosure of IP addresses in the audit log will allow customers more robust security investigations and threat detection and also better equip customers to meet compliance requirements.

### Intended Outcome

Audit and compliance objectives as well as security concerns are increasing in importance to enterprise customers. We want enterprise administrators to have access to the data they need for the job they need to do, whether that be a compliance matter, short term security investigation or longer-term threat analysis and prevention.  By providing IP addresses in the audit log, customers can better meet their compliance and security needs.

### How will it work?

We will provide the actor's IP address for the following audit log events:
* all organization-related events
* all events pertaining to organization-owned projects and other assets where the actor is a member of the organization.
* all events pertaining to organization-owned private and internal repos where the actor is a member of the organization.
 
IP address disclosure will be an opt-in feature.  For organizations that choose to enable the feature, organizations members will be notified of the change.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2022-06-02-github-enterprise-cloud-customers-can-access-ip-addresses-for-audit-log-entries-for-enterprise-owned-assets
