### ISSUE TITLE
Tree view for changed files in a pull request

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#348]
### Summary

Pull requests typically change multiple files, and understanding the scope of these changes and navigating between files can be difficult for reviewers in the current experience. A tree view will be added to help reviewers quickly navigate to all the files changed in a hierarchical view that reflects the directory structure.

![image](https://user-images.githubusercontent.com/2503052/143882359-36229a93-36cf-4051-8672-dd821d2631cb.png)

### Intended Outcome

The goal is to improve the review experience and reduce review time by making it easier for users to quickly understand the scope of the changes before starting their review and by making it easier for users to navigate around the changes in the pull request.

### How will it work?

Changed files will be presented in a hierarchical structure on the **Files Changed** tab of the pull request page (replacing the existing **Jump to** drop-down). Clicking a file will scroll to the file's "diff" so the user can review and comment.

**Comment by spaltrowitz** [comment]
this feature has shipped! https://github.blog/changelog/2022-03-16-pull-request-file-tree-beta/
