### ISSUE TITLE
Fine grained permissions for Dependabot alerts

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#352]
### Summary

With the recent beta release of [custom roles](https://github.blog/changelog/2021-10-27-enterprise-organizations-can-now-create-custom-repository-roles/), administrators want to craft roles which include either read or write access to Dependabot alerts. 

### How will it work?

Dependabot alerts and secret scanning alerts share an existing permissions implementation. We will deprecate this function and move to using custom roles. This will better align these security features with the broader story for role based access control across the product.

**Comment by ankneis** [comment]
⛵ Shipped as of 2/2: https://github.blog/changelog/2022-02-02-dependabot-alert-permissions-can-now-be-configured-as-part-of-custom-repository-roles/
