### ISSUE TITLE
Enterprise administrators can assume Organization ownership

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#353]
### Summary

GitHub Enterprise Ownership has been built in layers over the years from repos to orgs to enterprise accounts. It can be difficult for administrators across companies to govern all of these entities together.

To address this, and as the follow-up to #526, we will enable enterprise admins to assume the organization owner role in organizations owned by their enterprise account.

### Intended Outcome

Enterprise Admins can assume ownership of an org to audit and apply policies and security controls, and ensure that no organizations are left in an unowned state. 

### How will it work?

Enterprise Admins will be able to navigate to the organization view within the Enterprise Account and select an option on the organization card to `Become Organization Owner`.

**Comment by spaltrowitz** [comment]
Shipped to dotcom! https://github.blog/changelog/2022-03-02-enterprise-owners-can-assume-organization-ownership/
