### ISSUE TITLE
Protanopia & Deuteranopia Colorblind Themes GA

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#357]
### Summary

![colorblind theme preview](https://user-images.githubusercontent.com/33528647/135456151-7d12909b-5848-4e66-a0d3-3b656be9718a.gif)

Varying by gender and geography, color blindness could affect up to 8% of the world's population, with a majority impacted by the red/green color spectrum. As red and green have become ubiquitous indicators for status (open vs. closed, pass vs. failed) as well as for communicating warning or destructive action states, colorblind users are forced to use shape and iconography to interpret meaning from UI. This new theme swaps colors like red and green across GitHub.com for orange and blue to make GitHub more inclusive for users with Protanopia & Deuteranopia color blindness. 

### Intended Outcome

Users with Protanopia & Deuteranopia color blindness are able to use github.com with a light and dark theme that uses more colors within their visible spectrum.

### How will it work?

From the [appearance settings](https://github.com/settings/appearance) page, a user is able to choose from the light and dark Protanopia & Deuteranopia colorblind themes in their preferred theme settings.

**Comment by ankneis** [comment]
Closing this one out - will create a new roadmap issue when the work gets picked up again.
