### ISSUE TITLE
Pricing Calculator V2

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#359]
### Summary

On August 11th, we launched V1 of the pricing calculator page that supports the cost estimates for Codespaces, Actions, Packages, GHAS.

We are planning to add the following new features to the pricing calculator and continue improving the experience to calculate the cost for GitHub products. 

**Q2 Milestones**
- [x] FAQ 
- [x] Free Trial CTA 
- [x] Hints 

### Intended Outcome

Enable GitHub Sales and Customers to calculate cost and budgets for Consumables.

### Free Trial CTA
![image](https://user-images.githubusercontent.com/47511016/143916006-4d677e2e-1a8e-4dcf-807e-3df16287cd37.png)

### FAQs
![image](https://user-images.githubusercontent.com/47511016/143915851-4cc593ae-7ce2-4990-ac54-950e25c9abf2.png)

### Hints 
![image](https://user-images.githubusercontent.com/47511016/143916081-89c4482a-eee2-4042-a664-6cd2e3573a7d.png)

**Comment by Sid-ah** [comment]
https://github.com/pricing/calculator
