### ISSUE TITLE
Azure AD OpenID Connect Authentication for GHEC EMUs (Beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#362]
### Summary

[OpenID Connect](http://openid.net/connect/) (OpenIDC) is a protocol that sits on top of the [OAuth 2.0](https://oauth.net/2/) framework. While OAuth 2.0 provides authorization via an access token containing scopes, OpenID Connect provides authentication by providing an ID token which contains a new set of scopes and claims specifically for identity. Using the ID token, OpenID Connect allows separate systems to interoperate and share authentication state and user profile information.

### Intended Outcome

The introduction of OpenID Connect as an authentication protocol lays the foundation for a number of customer benefits that we intend to bring to GHEC EMUs and GHAE. Those include full support for [Conditional Access Policy (CAP)](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/) governance via Azure AD, enabling customers to centralise CAP policies such as location restrictions to their identity provider. It is also a bridge to GitHub supporting Azure [Service Principals](https://docs.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals). 

In this initiative, we will enable OpenIDC on GHEC EMUs. Later, we will bring this capability to GHES and GHAE.

### How will it work?

Enterprise administrators will be able to configure OpenID Connect via the enterprise account settings and Azure AD portal.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2022-05-31-azure-ad-oidc-and-conditional-access-support-for-ghec-emus/
