### ISSUE TITLE
Bulk-enable code scanning for multiple repositories

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#441]
### Summary

Currently, code scanning can be enabled and configured easily for a single repository at a time. We're going to provide a solution for teams to easily and efficiently set up code scanning on multiple repositories at the same time.

### Intended Outcome

Enabling and configuring code scanning on multiple repositories will make it easier to quickly roll out code scanning across an entire business.

**Comment by ankneis** [comment]
🚢 This shipped to dotcom: https://github.blog/changelog/2023-03-20-enable-code-scanning-default-setup-with-codeql-at-the-organization-level-public-beta. Leaving open to track for GHES release.

**Comment by ankneis** [comment]
🚢 This has shipped with GHES 3.9: https://docs.github.com/en/enterprise-server@3.9/admin/release-notes. Closing as complete.
