### ISSUE TITLE
Maintenance Mode Site Validation Access

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#448]
### Summary

In order to give administrators confidence that their GitHub Enterprise Server instance is ready for all users to access after it is put in maintenance mode, they will be given the ability to specify an IP exception list of addresses that can access application services on the GitHub Enterprise Server instance while maintenance mode is enabled.

Those users accessing from the allowed IP address will be able to verify the instance's operations while the server is in maintenance mode for all other users. 

### Intended Outcome

Problems can occur when upgrading GHES versions, adding or updating hardware and carrying out other maintenance functions; some of these problems cannot be detected, diagnosed, and in some cases do not even manifest, until certain git, user, web or other interactions are performed. 

This function will enable basic validation of system consumer interactions that will reduce the impact of encountering errors at scale when turning off maintenance mode and receiving production traffic. These basic tests may cover the different interaction models (web, API, git) and may be executed by direct user interaction or as customer-driven test suites.

### How will it work?

GitHub Enterprise Server administrators will be able to add a list of IP Addresses that can be granted access while the instance is in maintenance mode for all others. They will do so via the Management Console.

Access will respect user permissions, and actions will be logged as per normal operation. 

Should those users identify problems with the instance, access can be blocked, essentially reverting the server back to standard maintenance mode for further fault analysis and problem resolution.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2022-05-31-github-enterprise-server-3-5-is-now-generally-available/
