### ISSUE TITLE
Secret scanning detects secrets leaked in issue content

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#450]
### Summary

Secret scanning currently scans commit content for all supported patterns. We're extending the breadth of our scans for Advanced Security customers to cover issue content, like the issue description and any comments on the issue.

### Intended Outcome

While most secret leaks occur in code content, a portion _do_ also leak in other content types, including issues. We're expanding the scope of our scans for more exhaustive coverage to better protect our users across GitHub.

### How will it work?

Advanced Security customers will be able to view detections found in private and public repositories for issue content within the secret scanning UI and REST API.

**Comment by ankneis** [comment]
🚢 This has shipped to cloud: https://github.blog/changelog/2022-12-08-secret-scanning-now-detects-new-secrets-in-issue-content/. Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This shipped with GHES 3.11: https://docs.github.com/en/enterprise-server@3.11/admin/release-notes
