### ISSUE TITLE
CodeQL supports C# 10 (GHES)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#460]
### Summary

The [CodeQL analysis engine](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql) for [GitHub code scanning](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning) on GitHub Enterprise Server will be able to analyze projects written in C# 10.

### Intended Outcome

Currently, [CodeQL supports builds and standard language features up to C# 9](https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/). C# 10 has now been released publicly. Updating CodeQL support will allow customers who have adopted C# 10 to benefit from CodeQL's comprehensive security analysis.

### How will it work?

If a project contains C# 10 code, or if C# has been [configured as a language to be analyzed](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#changing-the-languages-that-are-analyzed) in the [code scanning workflow](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#about-code-scanning-configuration), CodeQL will pick up code using C# 10 language features automatically. No further configuration changes are needed. As soon as the analysis is finished, the CodeQL results will then become visible to you in the "Security" tab and on pull requests. C# 10 support will also be available through the [CodeQL CLI](https://codeql.github.com/docs/codeql-cli/about-the-codeql-cli/) for use with local environments or third-party CI systems. Users of previous GitHub Enterprise Server versions can [upgrade CodeQL independently](https://docs.github.com/en/enterprise-server@3.0/admin/advanced-security/configuring-code-scanning-for-your-appliance#configuring-codeql-analysis-on-a-server-without-internet-access).

**Comment by ankneis** [comment]
🚢 This shipped with GHES 3.5: https://docs.github.com/enterprise-server@3.5/admin/release-notes#code-scanning-detects-more-security-issues-supports-new-language-versions
