### ISSUE TITLE
npm: Mandatory 2FA for top 100 packages

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#466]
### Summary

As part of our ongoing commitment to [npm ecosystem security](https://github.blog/2021-11-15-githubs-commitment-to-npm-ecosystem-security/), we have already rolled out enhanced login verification to all publishers on the npm registry. The next step in securing the accounts of publishers on the registry is to enforce the use of 2FA for all accounts with publishing rights to high-impact packages. The first phase of enforce will be the top 100 packages, by dependents, on February 1 2021.

### Intended Outcome

All publishers of the top-100 packages by dependents enrolled in mandatory 2FA.

### How will it work?

Once mandatory 2FA is enforced accounts with publish rights to the top-100 packages on the registry, by dependents, will have limited access to the registry and npmjs.com until they register a 2FA device.

**Comment by ankneis** [comment]
🚢 This has been shipped as of 2/1: https://github.blog/2022-02-01-top-100-npm-package-maintainers-require-2fa-additional-security/
