### ISSUE TITLE
GitHub Copilot extension for Visual Studio (technical preview)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#468]
### Summary

Starting this February, Visual Studio developers will be able to use GitHub Copilot technical preview by installing an extension from the [marketplace.](https://marketplace.visualstudio.com/) In all manners, this extension will provide AI-powered autocomplete similar to GitHub Copilot extension already available for [VS Code.](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot)

### Intended Outcome

Using Visual Studio and GitHub Copilot, developers will be able to:

- Generate multi-line suggestions based relevant to the context of your file and project. 
- Convert comments to code. Write a comment describing the logic you want, and let GitHub Copilot assemble the code for you.
- Cycle through multiple suggestions. Pick the suggestion that best suits your application.
- Work with a broad set of frameworks and languages. The technical preview does especially well for Python, JavaScript, TypeScript, Ruby, Java, and Go, but it understands dozens of languages and can help you find your way around almost anything.

### How will it work?

After being admitted to the [GitHub Copilot technical preview](https://copilot.github.com), Visual Studio developers should install the GitHub Copilot extension from the [Marketplace.](https://marketplace.visualstudio.com/) Once installed, you'll be prompted to sign-in with your GitHub identity. After that, all you need to do is type in the code editor! GitHub Copilot will suggest multi-line code completions as you type. Hit "tab" to accept a suggestion. 

Illustration:
![Copilot_vs_UE_3](https://user-images.githubusercontent.com/16976466/151772017-5fd7d4f8-e7f2-46f3-abbf-744610561d82.gif)
.

**Comment by spaltrowitz** [comment]
This release has shipped to dotcom! Closing out this issue.
