### ISSUE TITLE
Actions:  Publish custom summary documents (Cloud)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#470]
### Summary

In addition to the text log actions will now be able to publish a markdown document that will be displayed on the run summary page.  

### Intended Outcome

Actions like test runners, and linters often want to provide a richer experience for their output than is possible with simple text.  

### How will it work?

An action author will have a new method in the toolkit that will let them write markdown formatted content to a summary file that is automatically created per action in a job.  On completion of each action the summary file is automatically uploaded and will be displayed on as part of the run summary.

**Comment by spaltrowitz** [comment]
this has shipped! 🚢  https://github.blog/changelog/2022-05-09-github-actions-enhance-your-actions-with-job-summaries/
