### ISSUE TITLE
Actions: Management experience for Cache (Server) 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#471]
### Summary

Dependency caching is one of the most effective ways to make jobs faster on GitHub Actions. 
However, caches can often go corrupt, and there is no great way to clear caches or debug issues with them. Also while we evict caches at a certain threshold limit, the cache performance can take a hit when the storage is near its quota. All this generates significant support requests and prevents the broad adoption of our caching capability. 

We are now enabling a management experience for users to view and delete their existing caches and monitor their current cache storage usage within a Repository. 

### Intended Outcome

- GitHub Actions enables customers to cache intermediate outputs and dependencies for their workflows. Caching is an effective way to make jobs faster and a management experience for cache usage would further promote its adoption. 
- Cache Management makes it easier to debug caching issues and provides greater control over cache usage by enabling users to view and delete existing caches.
- As we start supporting caching in ES and AE, a self-serve way will reduce support tickets by providing better ways to troubleshoot and debug corrupted caches.

### How will it work?

Once we enable Cache support in GHES, We will also be enabling a new Management experience (API based) to help cache users to view and monitor their cache usage across all the workflows in their repository.

**Comment by ankneis** [comment]
🚢 This went out with the GHES 3.7 release: https://docs.github.com/en/enterprise-server@3.7/admin/release-notes
