### ISSUE TITLE
Actions: Ability to view cache usage (Cloud)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#472]
### Summary

Dependency caching is one of the most effective ways to make jobs faster on GitHub Actions. 
However, there is no great way to clear caches or debug issues with them. Also while we evict caches at a certain threshold limit, the cache performance can take a hit when the storage is near its quota. This prevents the broad adoption of our caching capability. 

We are now enabling a management experience for users to view and monitor their current cache storage usage within a Repository. 

### Intended Outcome

- GitHub Actions enables customers to cache intermediate outputs and dependencies for their workflows. Caching is an effective way to make jobs faster and a management experience for cache usage would further promote its adoption. 
- Cache Management makes it easier to debug caching issues and provides greater control over cache usage by enabling users to view and delete existing caches.
- As we expand caching to ES and AE, a self-serve way will reduce support tickets by providing better ways to troubleshoot and debug corrupted caches.

### How will it work?

We will enable cache users to view and monitor their cache usage across all the workflows in their repository using APIs. Org admins would also be able to view the cache usage for each of the repositories in their org using an API.

**Comment by spaltrowitz** [comment]
this feature has shipped! https://github.blog/changelog/2022-03-17-view-cache-usage-in-your-action-workflows/
