### ISSUE TITLE
Expose information about development dependencies in Dependabot alerts

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#473]
### Summary

In ecosystems like npm where developers can indicate that a certain dependency is used during development only (a `devDependency`), developers have asked for a way to understand when Dependabot alerts are related only to a development dependency. In this initial ship, we expect to add support for a label on alerts that concern development dependencies to make it easier to filter, triage, or sort alerts. 

---

**Comment by ankneis** [comment]
This has shipped to dotcom! 🚢 https://github.blog/changelog/2022-06-23-dependabot-alerts-filter-alerts-by-the-scope-of-the-dependency-runtime-and-development/

**Comment by ankneis** [comment]
🚢 This has shipped with the GHES 3.7 release: https://docs.github.com/en/enterprise-server@3.7/admin/release-notes
