### ISSUE TITLE
Enterprise admins can set a specific organization as the default repository creation location

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#475]
### Summary

When GitHub Enterprise Cloud users create a repository, its location often defaults to the user's account. This increases risks of leaking enterprise data if the user adds such data to their repository.

With this feature, enterprise admins will be able to configure a specific organization as the default repository creation location. Then, when users who are authenticated to the enterprise create a new repository, its default location will be the configured organization.

### Intended Outcome

This will reduce the risk of enterprise data being accidentally leaked.

### How will it work?

In enterprise settings, enterprise admins will have an option to configure a specific organization as the default repository creation location. Then, when enterprise users create a repository, its default location will be the configured organization. This mock-up shows how the enterprise setting might look:

![image](https://user-images.githubusercontent.com/1767415/154565432-211ff7a6-188d-429d-ab8e-5d63e21e3131.png)

This table shows how repository creation behavior will change when configured as above.

| Action | Default repository location | Default repository location when configured as above |
| - | - | - |
| 1. On the GitHub homepage (https://github.com/) or a non-enterprise context, when a user clicks "**+**" on the page header and then **New repository** | The user's personal account | The user's personal account |
| 2. In the context of a specific enterprise (https://github.com/intel-sandbox/*) when a user clicks "**+**" on the page header and then **New repository** | The user's personal account | The in-context enterprise's configured organization |
| 3. When a user clicks the **New** repository button on an organization overview page (this button is only visible if the user has permission to create repositories in the organization) | The organization in which the **New** button was clicked | The in-context enterprise's configured organization |
| 4. When a user clicks the **Use this template** on a template repository | The user's personal account | The in-context enterprise's configured organization |

**Comment by ankneis** [comment]
Closing as cancelled.
