### ISSUE TITLE
Admins can block commits with noncompliant messages

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#476]
### Summary

Today, many organizations have requirements for the contents of commit messages. For example, a repository owner might require commit messages to reference an issue or tracking number. But such requirements can be overlooked and are difficult to enforce. Users can commit changes to a repository with any commit message they choose.

This feature will allow admins to configure required patterns for commit messages. Repository users will not be able to commit unless the commit messages comply with these patterns.

### Intended Outcome

This feature will allow admins to block commits unless their commit messages match certain patterns.

### How will it work?

Admins will be able to configure required patterns for commit messages. Repository users will see an error if they attempt to commit with a commit message that doesn't comply with the patterns.

**Comment by ankneis** [comment]
Closing this issue as it has been consolidated with: https://github.com/github/roadmap/issues/644
