### ISSUE TITLE
Admins can block noncompliant branch and tag names

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#477]
### Summary

Today, many organizations have requirements for the naming of branches and tags. For example, a repository owner might require branch names to include the creating user's username in a pattern like `/users/my-username`. But such requirements can be overlooked and are difficult to enforce. Users with write permission can create branches and tags with any name of their choosing.

This feature will allow admins to configure required patterns for branch and tag names. Repository users will not be able to create branches and tags unless their names comply with these patterns.

### Intended Outcome

This will allow admins to block branches and tags from being created unless their names match configured patterns.

### How will it work?

Admins will be able to configure required patterns for branch and tag names. Repository users will see an error if they attempt to create branches or tags with names that don't comply with the patterns.

**Comment by ankneis** [comment]
Closing this as it has been consolidated with: https://github.com/github/roadmap/issues/644
