### ISSUE TITLE
Automatic user license sync improvements

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#481]
### Summary

Automatic license sync enables you to manage license usage across your GitHub Enterprise deployments by automatically syncing user licenses from your GitHub Enterprise Server instance to GitHub Enterprise Cloud.

In an effort to reduce enterprise administration of the license sync process, we are making improvements to the matching experience.

### Intended Outcome

The goal is to provide you with more clarity when viewing license sync results and total licenses consumed, as well as offer a better approach to identifying duplicate users between GitHub Enterprise Server and GitHub Enterprise Cloud.

### How will it work?

We will provide the following improvements:

* a more robust consumed licenses dataset
* REST endpoints for querying license sync status and the more robust consumed licenses dataset mentioned above
* an enhancement to the license sync matching algorithm whereas the user's GitHub Enterprise Server email address will be compared with SAML metadata on a GitHub Enterprise Cloud user's account[^1]; this new matching logic will be in addition to the existing matching logic we have today

[^1]: For customers that use SAML for GitHub Enterprise Cloud and store the user's primary email address as part of the user's SAML metadata, this new functionality will allow for one to one matching with the user's Enterprise Server account.  GitHub.com users will no longer need to add their work email address to their their user account.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2022-08-18-license-sync-updates-new-consumed-license-data-a-new-license-api-and-license-matching-improvements-public-beta/
