### ISSUE TITLE
Projects beta GraphQL API

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#482]
### Summary

Today we have a limited GraphQL API for projects beta, during this quarter we will both be expanding the API and improving how you can interact with it. 

### How will it work?

This work will be split into two areas: 

**1. Improving the coverage of the API**

In addition to the existing API, you will be able to:
- Fetch the values of all fields in a project.
- Access the settings of iteration and single select field types.
- Fetch the configuration options for a given view.
- Fetch the values of all fields in a project, including linked pull requests.
- Fetch all items in a project, including draft issues.
- Given an item, the user can determine its type.
- Create draft issues.
- Re-order an item within a project.

**2. Create a new permissions scope for projects**

This will simplify and reduce the amount of permissions you will need to request when generating an API token to work with projects.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/.
