### ISSUE TITLE
Codespaces: APIs for organization administration 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#484]
### Summary

Organization admins can use APIs to manage codespaces.

### Intended Outcome

As organizations start to scale with Codespaces, we've heard feedback around admins needing more more flexibility, beyond UI-only settings, around managing codespaces settings for their organization. This functionality aims at providing organization admins access to APIs that will enable them automate and manage codespaces and codespaces settings more efficiently across various repositories within their org. 

### How will it work?

Provides org admins APIs to manage org-owned codespaces with support for the following APIs: 

- Manage codespaces access
- View org owned codespaces across repositories by user and cost 
- Stop org owned codespaces across repositories
- Set repo level and org level secrets
- Configure prebuilds for desired repositories
- Set & update policies across repositories

**Comment by spaltrowitz** [comment]
this has shipped! 🚢 https://github.blog/changelog/2022-06-27-whats-new-in-codespaces-for-organizations/

closing out this issue
