### ISSUE TITLE
Dependency review enforcement (GHES beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#487]
### Summary

This feature is the GHES version of https://github.com/github/roadmap/issues/149. In the initial version, it will be delivered as an API which allows developers to block pull requests which include vulnerable dependencies using an app or GitHub Action. We will deliver an open-source GitHub action which implements this functionality.

### Intended Outcome

Developers will check in fewer vulnerable dependencies by preventing accidental inclusion of vulnerable dependencies, leaving their end customers more secure. 

### How will it work?

We will provide an API and a GitHub action which implement this functionality.

**Comment by ankneis** [comment]
🚢 This has shipped: https://docs.github.com/enterprise-server@3.6/admin/release-notes#code-security!
