### ISSUE TITLE
Users can comment when dismissing code scanning alerts (GHES)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#489]
### Summary

Users can add a comment when dismissing code scanning alerts.

### Intended Outcome

This will let users record the context of an alert dismissal which can be used as justification during auditing and reporting.

### How will it work?

Users will be able to add a comment when dismissing a code scanning alert. This will be optional and in addition to selecting a dismissal reason. The comment be recorded in the code scanning alert timeline and REST API.

**Comment by ankneis** [comment]
This shipped and went out with GHES 3.6: https://github.blog/changelog/2022-06-01-users-can-now-add-a-comment-when-dismissing-code-scanning-alerts/
