### ISSUE TITLE
Secret scanning: dry-runs for enterprise-level custom patterns (server)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#492]
### Summary

As testing tool, a dry-run scan at the enterprise level will allow users to hone their custom regex patterns by determining the estimated number and quality of alerts generated for a specified pattern. This feature follows our release of repository and organization level dry-runs.

### Intended Outcome

A poorly authored regular expression can spawn thousands of results across an enterprise. Dry-run scans will allow users to prevent a bloat of results by testing their patterns before submission.

### How will it work?

Users can easily test their patterns before publishing at the repository, organization, and now enterprise levels. The dry-run scan will provide users with an estimate of the number of alerts that their pattern would create if published, as well as a sample set of detected secrets in the relevant repositories.

**Comment by ankneis** [comment]
This has shipped to GHES 3.6 🚢 https://docs.github.com/en/enterprise-server@3.6/admin/release-notes
