### ISSUE TITLE
Dependabot alerts shows transitive dependency paths

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#494]
### Summary

Dependabot alerts will surface more information about transitive dependencies, including direct dependency information and transitive dependency paths.

### Intended Outcome

In this initial ship, we expect to add filtering ability for alerts on direct and indirect dependencies, as well as surfacing of the direct dependencies that pull in a transitive dependency.

**Comment by spaltrowitz** [comment]
this has shipped to dotcom! 🚢  https://github.blog/changelog/2022-09-07-dependabot-unlocks-transitive-dependencies-for-npm-projects/

leaving open to track to GHES

**Comment by ankneis** [comment]
This issue is being closed as outdated. For more information, please check out this [Discussion post](https://github.com/github/roadmap/discussions/1014). Stay tuned for new additions to our refreshed public roadmap!

**Comment by ankneis** [comment]
We wanted to provide more details on why we removed this from the roadmap. This effort is under review by the product team. This has been removed from the roadmap until we can provide a more accurate delivery estimate.

We’d love you to share your thoughts in [this dedicated discussion](https://github.com/orgs/community/discussions/21630) —your feedback is invaluable in helping us prioritize.
