### ISSUE TITLE
Dependabot REST API

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#495]
### Summary

This feature will expose information about Dependabot alerts and Dependabot updates in a new REST API. 

### Intended Outcome

While users can already access information about Dependabot alerts and Dependabot updates from the GraphQL API, many users have indicated a preference for working with a REST API instead.

**Comment by spaltrowitz** [comment]
this has shipped to dotcom! leaving open to track to GHES https://github.blog/changelog/2022-09-22-dependabot-alerts-rest-api-is-now-available-in-public-beta

**Comment by ankneis** [comment]
This shipped with GHES 3.8: https://docs.github.com/en/enterprise-server@3.8/admin/release-notes
