### ISSUE TITLE
Secret scanning: Support push protection for custom patterns defined at the repository and organization levels

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#496]
### Summary

In public beta, secret scanning scans high-confidence tokens (those with a low false positive rate) and blocks a remote push if secrets are detected, thereby flagging secrets before exposure. Now, we're expanding push protections to support custom patterns!

### Intended Outcome

Advanced Security customers can enable push protection for our set of highly-identifiable, built-in patterns. While these patterns provide preventative support for customers, organizations want to also protect their developers from leaking organization-specific patterns. Push protection support for custom patterns will fill this coverage need.

### How will it work?

Advanced Security customers will be able to enable push protection for default patterns and custom patterns at the repository and organization levels.

**Comment by ankneis** [comment]
🚢 🚢 This has shipped to dotcom: https://github.blog/changelog/2022-12-15-secret-scanning-now-push-protects-custom-patterns.

Leaving open to track GHES release.

**Comment by ankneis** [comment]
Closing as this shipped to GHES 3.9: https://github.blog/2023-06-29-github-enterprise-server-3-9-is-now-generally-available/
