### ISSUE TITLE
Enterprise Support Bundles are more efficient

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#498]
### Summary

Enterprise Support Bundles enable GitHub Enterprise Server customers to share information with GitHub, when they need support. 

We are making improvements to the efficiency of the end-to-end generation and upload process in order to reduce the amount of time it takes for GitHub to support customers.

### Intended Outcome

GitHub Enterprise Server should be a reliable and highly available product for all customers. When customers experience incidents or problems, we work to help them restore service as quickly as possible. 

By reducing the amount of time it takes to generate and extract data from an Enterprise Support Bundle, we can help customers diagnose and resolve incidents faster.

### How will it work?

This initiative will not result any customer-facing changes to the Support Bundle generation process. We will reduce the time to generate and analyse bundles by optimising data at the point of collection and compression, and optimising GitHub's internal analysis tools to extract insight more quickly.

**Comment by ankneis** [comment]
🚢 This has shipped: https://docs.github.com/en/enterprise-server@3.4/support/contacting-github-support/providing-data-to-github-support
