### ISSUE TITLE
Codespaces: Prebuilds general availability 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#500]
### Summary

Prebuilds enable fast codespace creation experience regardless of the size and complexity of the repository by performing all the heavy-lifting tasks required to build your development environment beforehand. Think of a prebuild as a 'ready-to-go' template where your source code, editor extensions, project dependencies, commands, or configurations have already been downloaded, installed, and applied so that you don't have to wait for these tasks to finish in real-time every time you create a new Codespace.

### Intended Outcome

By using prebuilds, the time to create a new codespace for a project can decrease significantly, going from several minutes in some cases down to seconds.

#### Existing functionality that will be generally available 
- Repository admins can create and manage prebuild configurations in their repo's settings page.
<img width="700" alt="image" src="https://user-images.githubusercontent.com/30297258/166293331-439a66e9-f9b8-4cf7-be79-49e15d679919.png">

- Developers can create codespaces from 'prebuild ready' machine types to avail of fast creation times. 

![image](https://user-images.githubusercontent.com/30297258/166293587-ad872a42-f4e0-4571-aac0-7a899a364652.png)

#### New features that will be released with generally availability
- Repo admins can temporarily disable prebuild workflows to investigate failures and re-enable them when ready
<img width="700" alt="image" src="https://user-images.githubusercontent.com/30297258/166294151-0d7ba293-decb-4788-896a-51c956652618.png">

- Repo admins can specify a set of members to notify in case of prebuild workflow failures to help with quicker investigations towards mitigating any issues. 
<img width="700" alt="image" src="https://user-images.githubusercontent.com/30297258/166294669-a6918bd6-528c-40b8-87d2-a73baebc72a9.png">

- Repo admins can specify how many versions of prebuild configurations should be retained at a given point of time to help with cost control around storage for older versions. 
<img width="700" alt="image" src="https://user-images.githubusercontent.com/30297258/166295057-950e0907-0e9f-4d5a-9e11-d7c7523ee594.png">

#### Pricing at general availability:
You can learn more on the pricing for prebuilding codespaces here: https://docs.github.com/en/codespaces/prebuilding-your-codespaces/about-codespaces-prebuilds#about-billing-for-codespaces-prebuilds

**Comment by spaltrowitz** [comment]
this has shipped to dotcom! 🚢 https://github.blog/changelog/2022-06-15-prebuilding-codespaces-is-generally-available/

closing out this issue
