### ISSUE TITLE
Actions: Ability to list and delete caches

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#502]
### Summary

Dependency caching is one of the most effective ways to make jobs faster on GitHub Actions. However, there is no great way to clear caches or debug issues with them. Also, while we evict caches at a certain threshold limit, the cache performance can take a hit when the storage is near its quota. This prevents some customers from using the Actions cache. 

In the last quarter we have enabled cache users to view and monitor their current cache storage usage within a Repository. We are now enhancing the Cache management experience for users to list and delete their cache entries within a Repository. 

### Intended Outcome

- GitHub Actions enables customers to cache intermediate outputs and dependencies for their workflows. Caching is an effective way to make jobs faster and a management experience for cache usage would further promote its adoption. 
- Cache Management makes it easier to debug caching issues and provides greater control over cache usage by enabling users to view and delete existing caches.
- As we expand caching to ES and AE, a self-serve way will all admins to troubleshoot and debug corrupted caches.

### How will it work?

We will enable cache users to list and delete their cache entries across all the workflows in their repository using APIs and CLI.

**Comment by spaltrowitz** [comment]
this has shipped to dotcom! https://github.blog/changelog/2022-10-20-manage-caches-in-your-actions-workflows-from-web-interface

leaving open to track to GHES

**Comment by ankneis** [comment]
This shipped with GHES 3.7: https://docs.github.com/en/enterprise-server@3.7/admin/release-notes#3.7.0
