### ISSUE TITLE
Actions: New org level CI/CD admin role to enable management of Actions settings

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#503]
### Summary

Previously, the ability to manage CI/CD and package management was limited to organization administrators which resulted in a high burden on these individuals or teams. Organization administrators can now delegate CI/CD and package management-related controls to other users and teams.

### Intended Outcome
Today, many customers are overburdening their Git admins by also making them into CI/CD admins, due to their only being one permission. Others are having to take their CI/CD admins and make them 'global GitHub Admins' which, given the ever-growing functionality, in GitHub is a significant scope for their role. Each org admin account has a large blast radius if compromised, so reducing the number of Org admins and having the right Role Based Access Controls (RBAC) in place is top of mind for a lot of customers.

### How will it work?

We will provide a series of fine grained permissions focused on providing permissions to manage settings and configurations for CI/CD at an organization level. These settings include:

- Actions General Settings
- Actions Runners
- Actions Runner Groups
- Organization Actions Secrets
- Organization Actions Variables
- Actions Packages

Organization admins can use these setting when creating a Custom Organization Role for individual Organization Members or Teams.

We will use the work by the authorization team that allows organization admins to create and assign Custom Organization Roles.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2024-03-06-actions-fine-grained-permissions/
