### ISSUE TITLE
Actions: Seamless management of GitHub-hosted & self-hosted runners

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#504]
### Summary

GitHub Actions administrators now have a single management plane to look after all of the runners their teams are using in GitHub. This new management plane provides new information such as queue history, average wait time and aggregated runner data so that administrators can proactively add new runner types or capacity to get ahead of their developers having issues. This experience seamlessly brings together GitHub hosted and self hosted runners- providing a single place for administrators to empower their developers to succeed. 

### Intended Outcome

GitHub provides a single experience that empowers administrators to view, understand and manage their teams access to runners regardless of where they are running. Admins can do this in a way that lets them set the right policies and guard rails to keep developers safe, while avoiding interrupting them. 

### How will it work?

We will provide runner groups for 'all of GitHub runners', review how labels work to simplify them and provide experiences to understand job history on pools of machines -regardless of where those pools are running. This will all extend on what we have today for runner groups, which empowers administrators to provide the right Actions runners resources to the right repos, with the right guard rails in place.

**Comment by ankneis** [comment]
We [shipped](https://github.blog/changelog/2022-11-01-github-actions-restrict-workflows-to-specific-runners-using-runner-group-names/) the ability to target runner groups as a runs-on target and to scope runs-on to a label and a runner group. Given the measurable impact it had on the management experience for hosted and self-hosted runners, we are prioritizing other items at this time and removing this from the public roadmap.
