### ISSUE TITLE
Actions: Self-hosted runners now support Apple M1 silicon

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#507]
### Summary

The GitHub Actions runner application is now compatible with Apple silicone based hardware, which gives developers the capability to execute workflows using Apple’s latest M1 processor. Developers around the world running Actions workflows via self-hosted runner, will now be able unlock the full potential of their macOS development ecosystem. 

### Intended Outcome

The GitHub Actions runner application is now compatible with Apple’s latest M1 processor providing developers with the ability to run self-hosted macOS workflows in a OSX arm64 runtime.

### How will it work?

To ensure your macOS runner is configured properly, specify the “osx-arm64” runtime in your Actions YAML file.

**Comment by kevingduck** [comment]
This has shipped 🎉 https://github.blog/changelog/2022-08-09-github-actions-self-hosted-runners-now-support-apple-m1-hardware/
