### ISSUE TITLE
Actions: Reusable workflows work with private repositories

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#51]
**Summary**
This feature allows you to create reusable workflows in private repositories.

**Intended Outcome**
With this feature, you can keep the specifics of your workflow templates private.

**How will it work?**
Reusable workflows can be shared between private repositories.

**Comment by ankneis** [comment]
🚢 This has shipped to dotcom: https://github.blog/changelog/2022-12-14-github-actions-sharing-actions-and-reusable-workflows-from-private-repositories-is-now-ga

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This shipped with GHES 3.8: https://docs.github.com/en/enterprise-server@3.8/admin/release-notes

**Comment by kevingduck** [comment]
<img width="564" alt="1" src="https://github.com/github/roadmap/assets/2180038/72fcc591-6ed1-447d-abd8-a3471fd35d9c">
