### ISSUE TITLE
Adding an Issue Side-Panel to Github Projects

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#510]
### Summary

The GitHub Projects team is releasing one of our [most requested features](https://github.com/github/feedback/discussions/5381), a full-featured issue side-panel. 

### Intended Outcome

In part, we're building this feature to achieve parity with legacy projects. 

However, alongside the some of the features you know and love from legacy projects (like editing title, description, labels and assignees) we've added the ability to... 

* Read, add and edit issue comments
* Edit project meta-data (like project-specific single-select fields) 
* View and add emoji reactions ✨ to issues and issue comments 
* Archive or delete issues directly from the side-panel 

### How will it work?

The issue side-panel will be able to be accessed by simply clicking on any issue which is on a project board. 

For users who prefer to go directly to the issue page, simply `cmd` + `click` on Mac OS or `ctrl` + `click` on Windows/Linux to open the issue in a new tab.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/
