### ISSUE TITLE
Explorable archive for Projects 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#511]
### Summary

We're releasing an explorable archive for all items archived within your GitHub project.

### Intended Outcome

Added the ability to ...

- See when an item was archived and by whom
- Explore their archive quickly and easily with the filter bar 
- View previously archived draft issues 
- Bulk restore or delete items in the archive

### How will it work?

Check out a walkthrough of the explorable archive below! 

https://user-images.githubusercontent.com/16281246/162990380-23748538-bbe6-48fd-991e-1527abc17d92.mov

**Comment by ankneis** [comment]
🚢  Shipped: https://github.blog/changelog/2022-04-07-the-new-github-issues-april-7th-update/
