### ISSUE TITLE
Ability to delete an existing GitHub Project

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#512]
### Summary

Currently, users can choose to archive a project they are no longer using, we're adding the ability to delete a project.

### Intended Outcome

When built, this feature will allow users to permanently delete a project.

### How will it work?

The ability to delete a project will be available through the project's settings page.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/
