### ISSUE TITLE
Admins can require that developers sign off on commits made in the web interface

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#514]
### Summary

This feature will let admins require developers to sign off on commits made through GitHub's web interface, such as when editing a file or merging a pull request. It will also make it easier for developers to complete those signoffs.

**Note:** Signing off on a commit is different than [signing a commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits), such as with a GPG key.

#### Background

The Git command line interface has a [`--signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--s) option that developers use to sign off on their commits. Many open-source organizations require developers to sign off on changes to affirm their compliance with repository rules and licensing. Git's `--signoff` option appends a specially formatted line to the commit message, as shown here:

```
Signed-off-by: Mona Lisa <mona@github.com>
```

This text is often called a “DCO signoff” because the most common signoff agreement is the [Developer Certificate of Origin (DCO)](https://developercertificate.org/) from the Linux Foundation.

#### Problems

Open-source projects often use pull request checks to block commits from being merged unless they're signed off. Here’s an example of a commit being blocked in the open-source [Gradle Profiler](https://github.com/gradle/gradle-profiler/) repository which requires DCO signoffs:

![A pull request check that failed because a commit was not signed off](https://user-images.githubusercontent.com/1767415/166159897-49cfbbc0-c7be-4efb-ab14-15d5a7bf5659.png)

This problem is more likely when committing from GitHub's web interface where Git’s `--signoff` option isn't available. To sign off there, developers must manually add the `Signed-off-by:` text to their commit message. That's easy to overlook or misformat, resulting in the commit being blocked from merging. Resolving this situation can be complicated and slow developers down, as shown in these instructions to fix one commit:

![Instructions for amending a commit that is not signed off](https://user-images.githubusercontent.com/1767415/166236147-8ae48936-5cf4-45be-9429-372900e7ff09.png)

In the words of an open-source contributor:

>As a pull request reviewer, this is my biggest pain point. If someone forgets to manually sign off on a commit in the web UI, the pull request check fails, and the only resolution is to rebase or squash and force push to fix the commit message. Either way, the review history becomes unclear. This is high friction for new/infrequent contributors and people forget.

### Intended Outcome

This feature will simplify signing off on commits made in GitHub's web interface so that it's easier for developers, fewer commits are blocked from merging, and less time is spent resolving the blocked commits.

### How will it work?

* Admins will be able to toggle a setting that requires developers to sign off on commits made through GitHub's web interface.
* When the setting is enabled, the web interface will inform developers that their action of committing will also constitute signing off. It will look similar to the mocked-up image below. Like using Git's `--signoff` option on the command line, signing off in GitHub's web interface will automatically append the `Signed-off-by:` text to the developer's commit message.

![GitHub's web interface for committing will inform developers that they are also signing off when they commit](https://user-images.githubusercontent.com/1767415/166171381-b70438c7-928a-4429-8947-610e74178eec.png)

### Other information

Related to this feature, GitHub is planning a repository protection that blocks commits that aren't signed off, whether the commits are made in GitHub's web interface or pushed from the command line or another Git client.

We appreciate feedback on this and other topics in GitHub's [public feedback discussions](https://github.com/github/feedback/discussions/).

**Comment by spaltrowitz** [comment]
this has shipped to dotcom! 🚢 https://github.blog/changelog/2022-06-08-admins-can-require-sign-off-on-web-based-commits/
