### ISSUE TITLE
Powerful new code search capabilities (beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#517]
### Summary

GitHub will release substantial improvements to searching code, including flexible search syntax, filtering by language and path, smart ranking of results, and rich symbol information and navigation.

### Intended Outcome

Developers frequently need to pause their work to search, discover, navigate, and understand other code. This is particularly challenging when the answers are spread across multiple organizations and repositories. The longer it takes for developers to find what they need, the more context they lose about their work in progress and the more difficult it is to get back into a flow state. GitHub's vision for this roadmap item is to help developers find what they need quickly and intuitively to sustain their context and productivity.

### How will it work?

In December 2021, we released a technology preview of these new capabilities, now with a search index of over 12 million repositories. We encourage you to [sign up for it now](https://cs.github.com/about) and [give us your feedback](https://github.com/github/feedback/discussions/categories/code-search-and-navigation-feedback). Using what we're learning from the technology preview, our next step is to graduate its capabilities to GitHub.com proper, replacing its current code search experience. This roadmap item represents the culmination of that effort. Here are a few of the anticipated features:

* Easily find what you’re looking for among the top results, with smart ranking and an index that is optimized for code.
* Search for an exact string, with support for substring matches and special characters, or use regular expressions (enclosed in `/` separators).
* Scope your searches with `org:` or `repo:` qualifiers, with auto-completion suggestions in the search box.
* Refine your results using filters like `language:`, `path:`, `extension:`, and Boolean operators (`OR`, `NOT`). Search for definitions of a symbol with `symbol:`.
* Get your bearings quickly with additional features like symbol information for the active scope, find references, jump-to-definition, select-to-search, and more!

This mockup image shows how certain features might look:

![A mockup image that shows how some of the features might look](https://user-images.githubusercontent.com/1767415/167199532-1c9e3fe1-a6ce-4205-a122-58f766f33a69.png)

For more details, visit [frequently asked questions](https://cs.github.com/about/faq) of the technology preview and check out the preview's [search syntax](https://cs.github.com/about/syntax).

**Comment by spaltrowitz** [comment]
this has shipped to dotcom in a public beta! https://github.blog/changelog/2022-11-09-search-based-code-navigation-for-rust-projects. closing out this issue
