### ISSUE TITLE
Enterprise Managed Users: Optionally redirect users to SSO when not authenticated

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#518]
### Summary

Today, enterprises using the [Enterprise Managed Users (EMU)](https://docs.github.com/en/enterprise-cloud@latest/admin/identity-and-access-management/using-enterprise-managed-users-for-iam/about-enterprise-managed-users) feature are hidden entirely on GitHub.com.  Visiting a URL for their repos, orgs, and enterprise pages all result in a 404 if you are not signed in to the EMU enterprise already. 

This improvement allows an administrator to replace that 404 page with a redirect to the enterprise's linked IdP in order to SSO.  

### Intended Outcome

The existing 404 behavior prevents unwanted accidental discovery of enterprise resources, but can also make it harder for users to sign in.  By automatically redirecting the user to the linked IdP for SSO, it'll be easier and faster for enterprise users to get access to GitHub. 

### How will it work?

Enterprise administrators will be able to opt-in to the authentication redirect using their GitHub enterprise settings. The redirect will occur for all of the resources within the enterprise, once enabled. Setting this flag will not change the results of any API responses, whether authenticated or not.

**Comment by ankneis** [comment]
🚢 This shipped to public beta: https://github.blog/changelog/2022-09-19-automatic-single-sign-on-for-enterprise-managed-users-public-beta/.

Changing the release phase to reflect that.
