### ISSUE TITLE
GHES: SCIM support for user provisioning and group management

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#519]
### Summary

Starting with GHES 3.7, enterprise administrators can use SCIM to manage user accounts in their Enterprise Server instance.  Using the API, administrators can create, update, and delete user accounts, and sync group information to map GitHub Team memberships. 

### Intended Outcome

Automated user provisioning and group membership management is critical for large-scale installations of GitHub Enterprise Server. 

### How will it work?

The GHES SCIM API is tested for compatibility with the Azure AD SCIM implementation. Flexible SCIM providers that can match the Azure AD dialect will also be supported, and a Swagger for the API will be published for testing.

**Comment by spaltrowitz** [comment]
this has shipped to GHES 3.7! https://docs.github.com/en/enterprise-server@3.7/admin/release-notes 

closing out this issue

**Comment by ankneis** [comment]
Note: SCIM for GitHub Enterprise Server is currently in private beta and is subject to change. For access to the beta, contact your account manager on [GitHub's Sales team](https://github.com/enterprise/contact). Please provide feedback in the [GitHub Community discussion](https://github.com/orgs/community/discussions/36825).
