### ISSUE TITLE
GHEC Team Sync will no longer send out invitations to users removed from an organization

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#521]
### Summary

[Team Sync](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-saml-single-sign-on-for-your-organization/managing-team-synchronization-for-your-organization) allows you to keep your GitHub Enterprise Cloud teams in sync with security groups managed by your IdP, based on the SAML identities linked to the GitHub personal accounts in your organizations or enterprise. 

We will be changing this feature to no longer invite users to orgs in order to add them to the team.  Going forward, [SCIM](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-saml-single-sign-on-for-your-organization/about-scim-for-organizations) will be the management tool for organization memberships, while Team Sync will be used to organize org members into teams. 

### Intended Outcome

Enterprise and organization admins should be able to cleanly separate management of organization membership and team membership.  This change will fix the "unescapable org" issue that some admins report, where a user who has left an org is constantly re-invited to it because Team Sync is still indicating that they are a member of a team in that org. 

### How will it work?

Team Sync will check for organization membership before adding a user to a team.  If they are not a member of the organization that owns the team, then they will not receive an invitation to the organization, nor be added to the team.  If they are invited to the org later, via SCIM, then they will be added to the team automatically.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-04-20-team-sync-no-longer-invites-or-removes-organization-members-by-default/
