### ISSUE TITLE
Secret scanning users can comment when closing an alert

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#523]
### Summary

Users can add a comment when closing a secret scanning alert.

### Intended Outcome

Users can record the context of an alert closure, which security teams can view when auditing resolved alerts.

### How will it work?

Users will be able to add an optional comment when closing a secret scanning alert. The secret scanning timeline and REST API will display the comment.

**Comment by spaltrowitz** [comment]
this has shipped to dotcom! https://github.blog/changelog/2022-09-29-secret-scanning-alerts-now-have-a-timeline-and-users-can-add-a-comment-when-resolving

leaving open to track to GHES

**Comment by ankneis** [comment]
This has shipped with GHES 3.8: https://github.blog/2023-03-07-github-enterprise-server-3-8-is-now-generally-available/
