### ISSUE TITLE
Secret scanning historical timeline for alerts

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#524]
### Summary

In the UI for a secret scanning alert, users can view a timeline of actions taken on the alert, e.g. if the alert has been closed or reopened.

### Intended Outcome

Admins and security teams can better understand the history of an alert over time.

### How will it work?

When a user changes the state of an alert, the timeline in the UI will update with a new event for that action. Previous state changes will be persisted in the timeline. The [secret scanning API](https://docs.github.com/en/enterprise-cloud@latest/rest/secret-scanning#list-secret-scanning-alerts-for-a-repository--parameters) will still show the latest state in the `resolution` field.

**Comment by spaltrowitz** [comment]
this has shipped to dotcom! https://github.blog/changelog/2022-09-29-secret-scanning-alerts-now-have-a-timeline-and-users-can-add-a-comment-when-resolving

leaving open to track to GHES

**Comment by ankneis** [comment]
🚢 This has shipped with GHES 3.8: https://github.blog/2023-03-07-github-enterprise-server-3-8-is-now-generally-available/
