### ISSUE TITLE
Automatic user license sync re-sync button

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#525]
### Summary

Automatic license sync enables you to manage license usage across your GitHub Enterprise deployments by automatically syncing user licenses from your GitHub Enterprise Server instance to GitHub Enterprise Cloud.  Syncing happens on a weekly basis.

In an effort to reduce enterprise administration, we are adding a re-sync button to GitHub Enterprise Server so that enterprise owners can sync license data on demand.

### Intended Outcome

The goal is to enable enterprise owners to deduplicate users between GitHub Enterprise Server and GitHub Enterprise Cloud by kicking off the license sync process whenever it is convenient.

### How will it work?

Enterprise owners can click the re-sync button in GitHub Enterprise Server to transmit license data and run the matching algorithm that deduplicates licenses.

**Comment by ankneis** [comment]
🚢 This has shipped: https://docs.github.com/en/enterprise-server@3.5/admin/release-notes#sync-license-usage-any-time
