### ISSUE TITLE
GitHub Actions: Apple Silicon (M1) powered macOS runners (Public Beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#528]
### Summary

Apple developers will get the hardware and performance they need for their CI/CD operations with GitHub-hosted macOS runners powered by Apply silicone in an OSX arm64 runtime. The new runner options will make certain their apps are compatible with past, present, and future software requirements and have the performance they need to increase development velocity. 

### Intended Outcome

Developers that want to build and deploy their applications using the latest Apple technologies will be able to do so with ease using GitHub Actions.  

### How will it work?

To get started using M1 powered GitHub-hosted macOS runners, update the `runs-on:` key in your Actions workflow YAML to have those jobs target the new runner.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/
