### ISSUE TITLE
Secret scanning as a push protection (server beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#530]
### Summary

For repositories with Advanced Security enabled, secret scanning scans for a list of tokens after a push and alerts users of exposed secrets. As a push protection, secret scanning will scan high-confidence tokens (those with a low false positive rate) and block a remote push if secrets are detected, thereby flagging secrets before exposure.

### Intended Outcome

With a single setting, organizations will be able to scan every `git push` to their repositories and protect against accidentally committed secrets prior to the push. This addition will help enterprises with Advanced Security enforce compliance and security workflows, more tightly integrate secret scanning services, and reduce the number of opened issues for exposed secrets.

### How will it work?

GitHub will provide a UI for organizations to enable pre-push scanning for high confidence tokens.
With push protection enabled, developers within these organizations will have a CLI experience, or an equivalent in other popular developer environments, that notifies them of detected secrets during an attempted push.

Note that this beta will not include support for custom patterns.

**Comment by ankneis** [comment]
🚢  This has shipped: https://github.blog/2022-05-31-github-enterprise-server-3-5-is-now-generally-available/
