### ISSUE TITLE
Secret scanning: Validity check for GitHub tokens

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#531]
### Summary

GitHub will validate detections of GitHub tokens, including Personal Access Tokens and OAuth tokens.

### Intended Outcome

GitHub Advanced Security customers can prioritize their detected GitHub tokens based on their validity status for facilitated remediation.

### How will it work?

The secret scanning alert view will indicate whether a GitHub token is still valid or not.

**Comment by ankneis** [comment]
🚢 This has shipped to dotcom: https://github.blog/changelog/2023-01-19-secret-scanning-users-can-now-see-the-validity-of-detected-github-tokens.

Leaving open to track for GHES release!

**Comment by ankneis** [comment]
🚢 This has shipped with GHES 3.9: https://docs.github.com/en/enterprise-server@3.9/admin/release-notes. Closing as complete.
