### ISSUE TITLE
Ability to set up a security manager team at the organization level via the API

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#532]
### Summary

This functionality will enable GitHub Advanced Security customers the ability to set up a security manager team at the organization level programmatically.

### Intended Outcome

Today, organization owners can set up the security manager role only through the UI. For org admins that use GHAS and have many organizations, setting up a security manager team for each organization is cumbersome.  The goal is to provide enterprise customers with the ability to create security manager teams at the organization level via the API.  

### How will it work?

We will provide you with the ability to view (`GET`) the security manager team assigned at an organization level and assign the security manager role to a team (`PATCH`).

**Comment by ankneis** [comment]
🚢 This shipped to dotcom: https://github.blog/changelog/2022-08-01-rest-api-now-available-for-the-organization-level-security-manager-role-public-beta/. Leaving open to track for GHES 3.7 release.

**Comment by ankneis** [comment]
🚢 This has shipped with the GHES 3.7 release: https://docs.github.com/en/enterprise-server@3.7/admin/release-notes
