### ISSUE TITLE
Ability to enable/disable security features at the organization level via the API

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#533]
### Summary

This functionality will enable GitHub Advanced Security customers and Dependabot users to enable/disable security features at the organization level via the API.

### Intended Outcome

GitHub Advanced Security customers and Dependabot users have expressed a need to enable/disable security feature at the organization level via the API and are building cumbersome workarounds due to this missing functionality. The goal is to provide enterprise customers with the ability to enable/disable security features at the organization level via the API.  

### How will it work?

We will provide you with the ability to view (`GET`) and update (`PATCH`)—at the organization level—the enablement status and the setting to automatically enable for new repos. This functionality will be provided for the following security features:
* Dependency graph
* Dependency alerts
* Dependabot security updates
* Secret scanning
* Secret scanning as a push protection

In addition, you will be able to view and update the GitHub Advanced Security settings for an organization.

**Comment by spaltrowitz** [comment]
this has shipped to dotcom! https://github.blog/changelog/2022-08-31-update-and-configure-code-security-enablement-settings-via-the-organization-rest-api

leaving open to track to GHES

**Comment by ankneis** [comment]
🚢 This has shipped with the GHES 3.7 release: https://docs.github.com/en/enterprise-server@3.7/admin/release-notes
