### ISSUE TITLE
Codespaces: Private networking with Azure VNETs (Preview)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#534]
### Summary

This functionality will enable developers access on-prem resources from within their codespace alongside providing enterprise and org admins more control on the network settings for org-owned codespaces.

### Intended Outcome

One piece of constant feedback that blocks many enterprises from using Codespaces is access to on-prem services and resources from within a Codespace (e.g. databases, enterprise web services, package managers). In addition to on-prem access, more regulated enterprises also want existing firewall/networking policies to apply to Codespaces to aid secure development across their organization. This functionality aims at addressing the following scenarios: 
- Ability to connect from a Codespace to on-prem servers, other parts of Azure, or other clouds.
- Ability to restrict and isolate what a Codespace can connect to.

### How will it work?

Note: This functionality will be supported for the GitHub Enterprise Cloud plan.

- Enterprise administrators can connect an existing Azure VNET and subnet to their Enterprise.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/30297258/180478115-213d0ce2-ca6b-45e7-b02a-7b84e36ed68b.png">

- Once the VNET is connected, child organizations and repositories within that Enterprise can utilize that VNET for org-owned Codespaces to be created into. 
<img width="700" alt="image" src="https://user-images.githubusercontent.com/30297258/180478413-0af2681e-0add-4b22-9976-86360383ea6e.png">

- Since the VNET is owned by the customer, they will have full control on setting the required policies, inbound/outbound NSG rules, ExpressRoute/network peering to enable Codespaces access on-prem resources in addition to being compliant with those policies.

**Comment by ankneis** [comment]
This was shipped in a private preview. Please continue to refer to our updated Public Roadmap for the latest ships, including updates on the continuation of these projects.
