### ISSUE TITLE
Ability to prevent repo admins from enabling/disabling security features

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#535]
### Summary

Today, repo admins can disable security features (e.g., secret scanning) that are enabled at the org level by an org owner or a security manager. A few of our customers have expressed a security need to disallow repo admins from disabling these features.

### Intended Outcome

The goal is to provide enterprise customers with the ability to prevent repo admins from enabling and disabling security features for a repo.  

### How will it work?

We will provide enterprise customers with an enterprise-level configuration that will prevent enterprise owners from   enabling/disabling Dependabot and secret scanning.

**Comment by ankneis** [comment]
🚢 This shipped with GHES 3.8: https://github.blog/2023-03-07-github-enterprise-server-3-8-is-now-generally-available/
