### ISSUE TITLE
Comment on binary and deleted files in a pull request

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#536]
### Summary

While reviewing a pull request, users can comment on binary files (like images), deleted files, renamed files, and make general comments about a source file without attaching it to a specific line. This helps improve code quality and the review experience by ensuring conversations happen as close to the change as possible. It also ensures conversations stay with the change as updates are made to the pull request.

![image](https://user-images.githubusercontent.com/2503052/180461708-99b81265-b713-4ddb-8bb5-9e0b08fb221d.png)

### Intended Outcome

1. Improve code quality by allowing users to comment on files that couldn't be commented on before
2. Reduce overall review time

### How will it work?

1. A user (A) opens a pull request that changes various files, and inadvertently deletes a file
2. A different user (B) is requested to review and navigates to the **Files Changed** tab 
3. User B notices the deletion and clicks the `+` (add comment) button next to the deleted file
4. User B adds a comment "_Please double-check that this file should be deleted_" and submits their review
6. User A reviews the comments, notices the comment about the deleted file, and replies with "_Good catch. Fixing!_"
7. User A pushes a change that reverts the deletion and clicks **Resolve conversation** to mark the conversation as resolved

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-04-11-commenting-on-files-in-a-pull-request-is-now-generally-available. Leaving open to track for GHES release.

**Comment by ankneis** [comment]
🚢 This has shipped with GHES 3.9: https://docs.github.com/en/enterprise-server@3.9/admin/release-notes. Closing as complete.
