### ISSUE TITLE
Codespaces: Pull Request Validation for prebuild-enabled repositories 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#537]
### Summary

[Prebuilds enable fast codespace creation experience for large and/or complex projects](https://github.blog/2022-06-15-prebuilding-codespaces-is-generally-available/) by performing all the heavy-lifting tasks required to build your development environment beforehand. Think of a prebuild as a 'ready-to-go' template where your source code, editor extensions, project dependencies, commands, or configurations have already been downloaded, installed, and applied so that you don't have to wait for these tasks to finish in real-time every time you create a new Codespace.

This functionality enables developers to test their changes while creating a pull request that might affect the prebuild configuration for their prebuild-enabled branch. 

### Intended Outcome

With a Pull Request Validation step available to prebuild-enabled branches, developers can validate upfront if their changes may adversely affect the prebuild configuration for their branch. With this, developers no longer have to worry about accidently breaking the prebuild for a branch by testing and making any fixes upfront thus ensuring everyone continues to have a fast creation experience. Additionally repository admins/team leads will have additional confidence around prebuilds being steady and reliable without any manual interference. 

### How will it work?

- For prebuild enabled repositories, when a developer wants to push a change that updates the underlying prebuild configuration for that branch (ex. update the devcontainer configuration), GitHub will automatically introduce a test to validate if the changes will in any way cause the prebuild configuration to break. Initially this experience will only be supported via the GitHub UI, with support for CLI coming in as a fast follow. 
- Developers will also have a link to the build log once the test completes to fix any issues they might discover before merging the PR thus ensuring prebuilds continue to work without any failures for their branch and repository. 

<img width="731" alt="image" src="https://user-images.githubusercontent.com/30297258/180316806-11e0f281-2490-4ab2-91fe-bd99bab783ad.png">

**Comment by ankneis** [comment]
This issue is being closed as outdated. For more information, please check out this [Discussion post](https://github.com/github/roadmap/discussions/1014). Stay tuned for new additions to our refreshed public roadmap!

**Comment by ankneis** [comment]
We wanted to provide more details on why we removed this from the roadmap. We are currently prioritizing other features on our roadmap at this time, and are removing this from the roadmap until we are able to prioritize this again.

If you’re interested in this feature, please share your feedback in the [GitHub community](https://github.com/orgs/community/discussions/) so we can track interest and consider it in the future.
