### ISSUE TITLE
Codespaces: Prebuilding codespaces for multi-repo and monorepo projects 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#539]
### Summary

[Prebuilds enable fast codespace creation experience for large and/or complex projects](https://github.blog/2022-06-15-prebuilding-codespaces-is-generally-available/) by performing all the heavy-lifting tasks required to build your development environment beforehand. Think of a prebuild as a 'ready-to-go' template where your source code, editor extensions, project dependencies, commands, or configurations have already been downloaded, installed, and applied so that you don't have to wait for these tasks to finish in real-time every time you create a new Codespace.

With this work-item, teams will be able to take advantage of prebuilt codespaces for monorepos as well as for multi-repo/microservices where projects may require accessing additional resources (ex. repo, packages) while configuring a codespace. 

### Intended Outcome

- For multi-repo or projects that require accessing additional resources to build a development environment, repository administrators can specify those permissions in the dev container configuration and the prebuild workflow will identify and respect those while creating a prebuild. 
- For monorepos, repository administrators can select a specific devcontainer configuration to be prebuilt based on a subset of the project that requires faster environment creation. 

### Multi-repo projects 
- For multi-repo projects, [required permissions can be specified in the dev container configuration for that repository](https://docs.github.com/en/codespaces/managing-your-codespaces/managing-repository-access-for-your-codespaces#setting-additional-repository-permissions). 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/30297258/179618967-cab50406-133a-4d4a-b169-4ca1abd93032.png">

- During prebuild configuration creation, if the selected devcontainer configuration for a branch includes requested permissions, the admin will be prompted to accept required permissions upon creation of the prebuild configuration 
<img width="600" alt="image" src="https://user-images.githubusercontent.com/30297258/179619603-bef3dfab-de65-4f8b-834d-aabded877237.png">

### Monorepo projects 
- For monorepos, repository admins can select a specific devcontainer configuration within their repo to be prebuilt while creating a prebuild configuration:
<img width="900" alt="image" src="https://user-images.githubusercontent.com/30297258/179618613-ba06c686-f9c5-4ed5-b7f5-585dd633f8de.png">

- Once the prebuild is ready, developers will be able to create prebuilt Codespaces by selecting the appropriate dev container configuration during creation.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2022-07-28-prebuilding-codespaces-is-now-supported-for-multi-repository-and-monorepo-projects/.
