### ISSUE TITLE
Mathematical expressions can be displayed within Markdown

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#540]
### Summary

Mathematical expressions are key to information sharing in academia and among engineers, scientists, economists, statisticians, and others. Support for displaying mathematical expressions was [released](https://github.blog/changelog/2022-05-19-render-mathematical-expressions-in-markdown/) to GitHub Cloud in May, 2022. Next, math support will be added to GitHub Enterprise Server.

### Intended Outcome

This feature will add native support for using LaTeX-style syntax to render mathematical expressions where Markdown is supported in issues, repositories, and discussions. Expressions can be added inline in Markdown or as separate expression blocks.

#### Writing expressions as blocks

To add mathematical expressions as a multiline block displayed separately from surrounding text, start a new line and delimit the expression with the <code>```math</code> [code block syntax](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting).

``````
```math
**The Cauchy-Schwarz Inequality**
$$\left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right)$$
```
``````

![An image of an independent block of math Markdown being displayed](https://user-images.githubusercontent.com/7219923/165633956-cfe6be6d-66ec-451a-8afd-be3546f4d0a1.png)

#### Writing inline expressions

To include a mathematical expression inline with your text, delimit the expression with a dollar symbol `$`.

```
This sentence uses `$` delimiters to show math inline: $\sqrt{3x-1}+(1+x)^2$
```

![An image of inline math Markdown being displayed](https://user-images.githubusercontent.com/7219923/165633994-a1f2cee5-71cb-4303-bbd9-1df1604d7a01.png)

GitHub Enterprise Server's math rendering capability will use MathJax; an open source, JavaScript-based display engine. MathJax supports a wide range of LaTeX macros and a number of useful accessibility extensions. For more information, see the [MathJax documentation](http://docs.mathjax.org/en/latest/input/tex/index.html#tex-and-latex-support) and the [MathJax Accessibility Extensions documentation](https://mathjax.github.io/MathJax-a11y/docs/#reader-guide).

For more information about authoring content with advanced formatting, see [Working with advanced formatting](https://docs.github.com/get-started/writing-on-github/working-with-advanced-formatting) in the GitHub documentation.

**Comment by spaltrowitz** [comment]
this has shipped to GHES 3.7! https://docs.github.com/en/enterprise-server@3.7/admin/release-notes

closing out this issue
