### ISSUE TITLE
Secret scanning: Dry-runs for custom patterns (GA)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#542]
### Summary

GitHub Advanced Security customers will be able to dry-run their custom secret scanning patterns across all repositories in their enterprise or organization before publishing.

### Intended Outcome

Enable admins to test their patterns across all their repositories before publishing and creating alerts.

### How will it work?

When creating a custom pattern at the enterprise or organization level, admins will click "Save and dry run" then select the option to dry-run the pattern across all repositories.

**Comment by ankneis** [comment]
🚢 This has shipped to dotcom: https://github.blog/changelog/2022-08-12-secret-scanning-organization-admins-can-dry-run-custom-patterns-across-all-repositories/. Leaving open to track for GHES 3.7 release.

**Comment by ankneis** [comment]
🚢 This has shipped with the GHES 3.7 release: https://docs.github.com/en/enterprise-server@3.7/admin/release-notes
