### ISSUE TITLE
Secret scanning: Add a custom help link to push protection blocks

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#543]
### Summary

GitHub Advanced Security customers can include a link for their developers to navigate to when GitHub detects secrets in their commits and blocks them from pushing.

### Intended Outcome

Admins can provide additional support to developers via a link to internal tools.

### How will it work?

When enabling push protection on an organization, admins can add an optional link to present to developers when they're blocked from pushing code.

**Comment by ankneis** [comment]
🚢 This has shipped to dotcom: https://github.blog/changelog/2022-08-24-secret-scanning-admins-can-now-provide-a-link-to-display-when-a-push-is-blocked/. Leaving open to track for GHES release.

**Comment by ankneis** [comment]
🚢 This has shipped with the GHES 3.7 release: https://docs.github.com/en/enterprise-server@3.7/admin/release-notes
