### ISSUE TITLE
Displaying token data used for authentication in enterprise audit log events [Beta]

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#544]
### Summary

For enterprise audit log events where a token (PAT, OAuth, GitHub Apps) was  used as the method of authentication, the audit log will contain a hashed rendering of the token used for authentication, as well as the token type and token scope. In doing so, customers will be able to query actions a  token has been used to perform on enterprise assets. 

### Intended Outcome

Compromised tokens have the potential to provide threat actors with access to private data. After learning of a token compromise, we know that administrators and security professionals want to understand the actions taken using the corrupt token. To support Enterprise customers to complete these investigations, we will enhance the audit log data by logging identifiable and queryable token data in the audit log for events using tokens for authentication.

### How will it work?

The audit log will display the authentication methods, as well as the last 8 chars of the token for authentication, for audit log events using any token for authentication.

**Comment by ankneis** [comment]
Shipped to dotcom! 🎉 https://github.blog/changelog/2022-10-07-display-authentication-token-data-in-your-enterprise-audit-log-beta/

**Comment by ankneis** [comment]
🚢 This has shipped with GHES 3.8: https://docs.github.com/en/enterprise-server@3.8/admin/release-notes
