### ISSUE TITLE
Dependabot alerts: optional comment with dismissal

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#545]
### Summary

Similarly to [code scanning](https://github.blog/changelog/2022-06-01-users-can-now-add-a-comment-when-dismissing-code-scanning-alerts/), with this change you will be able to add an optional comment when dismissing a Dependabot alert. Dismissal comments are recorded in the alert timeline. 

### Intended Outcome

You can record the context of an alert closure, which security teams can view when auditing resolved alerts.

### How will it work?

When dismissing a Dependabot alert, you will be able to add a comment.

**Comment by spaltrowitz** [comment]
This has shipped to dotcom! https://github.blog/changelog/2022-08-22-dependabot-alerts-optional-dismissal-comment-2/ Leaving open to track release to GHES

**Comment by ankneis** [comment]
This release has shipped to GHES 3.7🚢 https://docs.github.com/en/enterprise-server@3.7/admin/release-notes
