### ISSUE TITLE
Dependabot alerts: historical timeline for alerts

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#546]
### Summary

Dependabot Alerts will now show more context through an alert's history, with timelines in the UI page for an alert. For example, alerts will show when and by who they were dismissed or reopened. 

### Intended Outcome

Admins and security teams can better understand the history of an alert over time.

### How will it work?

When an alert changes state, the event history will be added to a UI-based timeline in the alert's details page.

**Comment by ankneis** [comment]
🚢 This shipped to dotcom: https://github.blog/changelog/2022-07-28-dependabot-alerts-timeline-of-events-on-the-alert-details-page/. Leaving open to track for GHES release.

**Comment by ankneis** [comment]
🚢 This has shipped with GHES 3.7: [Viewing Dependabot alerts](https://docs.github.com/en/enterprise-server@3.7/code-security/dependabot/dependabot-alerts/viewing-and-updating-dependabot-alerts#viewing-dependabot-alerts)
