### ISSUE TITLE
Secret scanning: Enable at the Enterprise level

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#548]
### Summary

GitHub Advanced Security customers can enable secret scanning and push protection at the Enterprise level

### Intended Outcome

Allow users to easily enable secret scanning across their entire enterprise

### How will it work?

Like at the organization level, users can choose to enable secret scanning and push protection through the UI in their enterprise's settings page.

**Comment by ankneis** [comment]
This has shipped! 🎉 A [changelog post](https://github.blog/changelog/2022-10-06-enable-secret-scanning-for-an-enterprise-with-one-click) for this release has just been published. 🚢 Leaving open to track for the GHES release.

**Comment by ankneis** [comment]
🚢 This has shipped with the GHES 3.7 release: https://docs.github.com/en/enterprise-server@3.7/admin/release-notes
