### ISSUE TITLE
Codespaces, general availability

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#55]
**Summary**
[Codespaces](https://github.com/features/codespaces) provide instant dev environments hosted in the cloud. With Codespaces developers can get going faster with cloud-hosted environments, reducing time-to-first-commit. Enterprises can have the benefit of secure, cloud-hosted environments so code remains cloud-based.

![Codespaces screenshot](https://user-images.githubusercontent.com/2132776/115079144-b7db8280-9ece-11eb-9e32-1f4ebd44fa1a.png)

**Intended Outcome**
Codespaces allows users and organizations to develop in instant cloud environments without acquiring a VDI or rolling their own cloud-hosted development solution.

**How will it work?** 
Developers click "Open in Codespace" from a repo to create a new Codespace which then creates a new environment based on any instructions which may or may not be codified in the repo via a devcontainer to configure the image. If no devcontainer exists, the code is directly added to the kitchen sink, default image. From there developers have a cloud-hosted VS Code environment where they can not only pull in extensions and sync with their local VS Code, but also can run, debug, and live share with other team members.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-08-11-codespaces-is-generally-available-for-team-and-enterprise/
