### ISSUE TITLE
Packages: npm - granular permissions and easy organization sharing

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#554]
**Summary**
This enhances GitHub Packages support for [npm] by allowing granular permissions for individual packages and easier sharing within the organization. 

**Intended Outcome**
With the [introduction of GitHub Container Registry](https://github.blog/2021-06-21-github-packages-container-registry-generally-available/), users are able to store and share container images close to their source code on GitHub, including advanced capabilities such as fine-grained access control and easy sharing of packages across the organization. The same functionality will now been leveraged for the npm registry!

npm packages can be published to the Package Registry ([npm.pkg.github.com](https://github.com/orgs/github/teams/engineering/posts/npm.pkg.github.com)), and retrieved whenever they need to be used as a dependency in a project. Going forward, users are enabled to

- publish packages on organization level, in addition to repository level
- have fine-grained access control over their npm packages, decoupled from the repository permissions
- have internal visibility settings for npm packages, in addition to private and public
- give permissions to packages independently for Actions and Codespaces
- increase performance and maintain more package versions than earlier

**How will it work?**
Packages are published to the organization and permissions and visibility are managed on the package itself.

[Packages: Container service (GA)]: https://github.com/github/roadmap-internal/issues/144
[Packages: Container service (Beta)]: https://github.com/github/roadmap-internal/issues/101
[Packages: Helm Charts]: https://github.com/github/roadmap-internal/issues/119
[Packages: Universal/Generic Storage]:https://github.com/github/roadmap-internal/issues/112

[GitHub Packages]: https://github.com/features/packages
[GHES]: https://github.com/enterprise
[Plans]: https://github.com/pricing

[Container]: https://en.wikipedia.org/wiki/Container_(abstract_data_type)
[OCI]: https://www.opencontainers.org/ "Open Containers Initiative"
[ORAS]: https://github.com/deislabs/oras
[CNAB]: https://cnab.io/
[CNCF]: https://www.cncf.io/
[Kubernetes]: https://kubernetes.io/
[Docker]: https://www.docker.com/
[npm]: https://www.npmjs.com/
[maven]: https://maven.apache.org/
[Swift]: https://swift.org/
[Helm Charts]: https://helm.sh/
[Helm Hub]: https://hub.helm.sh/
[Rust]: https://www.rust-lang.org/
[Go]: https://golang.org/
[PHP]: https://www.php.net/
[Debian]: https://www.debian.org/
[Python]: https://www.python.org/
[PyPI]: https://pypi.org/

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2022-08-31-packages-fine-grained-permissions-and-organization-level-publishing-are-now-available-for-the-github-packages-npm-registry/
