### ISSUE TITLE
Actions: Self-hosted runner auto-scaling support for Kubernetes

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#555]
### Summary

DevOps teams can now reduce the complexity, and cost of hosting their own GitHub Actions runners, thanks to GitHub's support for auto-scaling self-hosted runners. GitHub has announced that github.com and GitHub Enterprise customers can now make _better_ use of auto-scaling self-hosted Actions runners for containerized workflows, supported by GitHub. 

Using auto-scaling self-hosted runners eliminate fixed overheads of traditional self-hosted runners, reducing the total cost of ownership for teams. They are infinitely scalable within the context of your infrastructure capacity.
Now they are deeply integrated with GitHub to better scale when you need them. And thanks to GitHub support, they are enterprise ready with SLA’s to keep everyone online and working efficiently.  All this is now accessible in GitHub’s UI, giving you a first class experience for managing all your runners wherever they are hosted. 

### Intended Outcome

GitHub provides support for and a first-class experience to create, manage and audit your self-hosted autoscaling runners.

Today customers who add an autoscaling runner get no feedback as the size/queue or other pertinent information to understand the health and scale of what their autoscaling runner is doing. The setup is also painful, sitting outside the GitHub UI with multiple paths, some of which are harder than others. 

### How will it work?

Customers will be able to use the GitHub UI to get the learn and get the tools they need to deploy a self hosted autoscaling runner. This will be reflected back in their GUI giving them the information they need to manage these queues and understand where their bottlenecks are.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-05-10-github-actions-actions-runner-controller-public-beta
