### ISSUE TITLE
Packages: Granular permissions and easy organization sharing for enterprise customers

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#560]
### Summary

This enhances [GitHub Packages](https://github.com/features/packages) support for Enterprise Server Customers by allowing granular permissions for individual packages and easier sharing within the organization.

### Intended Outcome

This change introduces several improvements:

- publish packages on organization level, in addition to repository level
- have fine-grained access control over their packages, decoupled from the repository permissions
- have internal visibility settings for packages, in addition to private and public
- give permissions to packages independently for Actions and Codespaces

### How will it work?

Packages are published to the organization and permissions and visibility are managed on the package itself.

**Comment by ankneis** [comment]
This issue is being closed as outdated. For more information, please check out this [Discussion post](https://github.com/github/roadmap/discussions/1014). Stay tuned for new additions to our refreshed public roadmap!

**Comment by ankneis** [comment]
We wanted to provide more details on why we removed this from the roadmap. We are currently prioritizing other features on our roadmap at this time, and are removing this from the roadmap until we are able to prioritize this again.

If you’re interested in this feature, please share your feedback in the [GitHub community](https://github.com/orgs/community/discussions/) so we can track interest and consider it in the future.
