### ISSUE TITLE
Projects: Configure column visibility in board view

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#562]
### Summary

Users will be able to configure column visibility on the board view layout by selecting which columns are displayed.

### Intended Outcome

Providing users with the ability to configure which columns are displayed on board view will allow them to further customize their boards to only display the items and columns they want to show. It provides a cleaner board layout experience and a more focused view.

This aligns the column visibility behavior with table view by selecting which columns to show or hide.

### How will it work?

Users will be able to select which columns to show or hide on board view from the column settings menu, similar to selecting columns on table view. This will adjust the columns that are displayed.

**Comment by ankneis** [comment]
🚢 This has shipped:  https://github.blog/changelog/2022-10-18-the-new-github-issues-october-18th-update/
