### ISSUE TITLE
Projects: Add projects to team index

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#563]
### Summary

Users will be able to add projects to their teams page to allow for quick access. This aligns with the current workflow of adding a project for quick access to repositories.

![Frame 3007](https://user-images.githubusercontent.com/3174849/186283720-776c2441-9043-4089-a771-5e200134d569.png)

### Intended Outcome

Users will be able to curate the set of projects that should be associated with a team.

By enabling projects to be referenced from the team page, users can easily find and review the full set of projects that may be important for their team.

By adding the project to the team's quick access page, it will also automatically add the team to the project with `read` permissions (if they don't already have `read` permissions), thereby ensuring all teammates have basic permissions needed to access relevant projects.

### How will it work?

To add a quick access to the projects, users will navigate to their team's page and then to the `Projects` tab. From there, they'll select `Add project`, search for the appropriate project, and select it to add it to the Quick Access list.

By adding a project in this view, we will also automatically add `read` permissions for the team to access the project. Because adding a project updates permissions, only users with `Admin` permissions will be able to add a project to the team's quick access page.

**Comment by ankneis** [comment]
🚢 This has shipped to dotcom: https://github.blog/changelog/2022-09-27-the-new-github-issues-september-27th-update/. Leaving open to track the GHES release.

**Comment by ankneis** [comment]
This went out with GHES 3.9. Closing as complete.
