### ISSUE TITLE
Actions: Visual Studio Code extension for linting

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#564]
### Summary

GitHub will release an official Actions extension for Visual Studio Code (VSCode) to make building and managing workflows easier. Developers will now be able to use rich editing features, check their YAML syntax for validity, and view context such as workflow runs and environments all within VSCode, and even before committing their workflow code to a repository.

### Intended Outcome

The previous process of building a workflow was to commit a change, trigger a run, and then navigate to GitHub to view the status and logs of the workflow.  Developers would build the workflow and validate it in two separate consecutive steps.  This meant that even simple syntax errors could end up having a considerable impact on a developer’s productivity.

### How will it work?

Developers will be able to build Actions workflows faster with the power of IntelliSense in VSCode.  Features such as syntax highlighting and linting will be supplemented by code completion on expressions and inputs.  This will allow developers to build workflows faster and with less mental overhead.  These editing features will not only help experienced customers avoid simple errors but also help flatten the learning curve for new customers.

The new extension also brings Actions context into VSCode so developers can stay focused. After a workflow run is triggered, customers can view its status by clicking on the Actions icon in the activity bar to open up the explorer.  In this view, developers will be able to see workflow statuses and inspect logs.  The ability to edit workflow files and view statuses in a single place improves developer productivity by eliminating the need to switch between tools.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-03-28-github-actions-visual-studio-code-extension-is-now-in-public-beta
