### ISSUE TITLE
Audit log streaming API requests targeting Enterprises' private repositories [Beta]

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#582]
### Summary

Enterprises will be able to add API requests targeting private repositories to their audit log streaming configuration for all of [GitHub's supported streaming endpoints](https://docs.github.com/en/enterprise-cloud@latest/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/streaming-the-audit-log-for-your-enterprise). 

### Intended Outcome

By providing access to the API activity targeted private repositories via audit log streaming, Enterprise owners and security professionals can:

* Better understand and analyze API usage within their Enterprise
* Use HTTP status codes to identify and diagnose potentially misconfigured applications
* Diagnose API activity that may be contributing to API rate limiting
* Develop API specific anomaly detection algorithms to identify potentially malicious activity

### How will it work?

Customers will enable API requests to be displayed as part of the Audit Log settings associated with their enterprise account. 

Once enabled, API requests will be able to be streamed to a GitHub supported streaming endpoints.

**Comment by ankneis** [comment]
🚢 This shipped to dotcom: https://github.blog/changelog/2023-04-03-api-requests-are-available-via-audit-log-streaming-public-beta.

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
Closing as this shipped to GHES 3.9: https://github.blog/2023-06-29-github-enterprise-server-3-9-is-now-generally-available/
