### ISSUE TITLE
Codespaces Configuration Editor

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#584]
### Summary

To customize Codespace development environments, a developer can specify IDE settings, project content layout, project dependencies, runtime environment settings, tools & utilities, and other configurations via [Dev Containers.](https://containers.dev/) Today that experience requires a developer to either: 

* First create a Codespace, then invoke the magic keystrokes in VS Code to walk through the guided UI, and then to rebuild/reload the codespace, or...
* Learn the nuances of the `devcontainer.json` semantics and syntax intimately to create the customization from scratch 

### Intended Outcome

GitHub Codespaces will provide point-and-click options in the GitHub.com UI that will allow you to customize your Codespace by choosing which Operating System base [image](https://github.com/devcontainers/spec/blob/main/docs/specs/devcontainerjson-reference.md#image-or-dockerfile-specific-properties) and [dev container features](https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-features.md). A wide range of customizations will be possible through this capability, making customization more accessible for developers either (a) just getting started with dev containers, or (b) who just need a quick-and-easy way to tailor their Codespace because the default dev container doesn't work well for them.

### How will it work?

The UI will manipulate the `devcontainer.json` in the repository on behalf of the developer.

**Comment by spaltrowitz** [comment]
this has shipped! https://github.blog/changelog/2022-10-21-codespaces-configuration-with-the-dev-container-editor/ closing out this issue
