### ISSUE TITLE
Dependabot Alerts enterprise-level REST API

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#593]
### Summary

You will be able to view your Dependabot alerts in an enterprise-scoped list via the [REST API](https://docs.github.com/en/rest/dependabot/alerts). This new endpoint will supplement repository-level and organization-level endpoints.

**Comment by ankneis** [comment]
🚢 This has shipped to dotcom: https://github.blog/changelog/2022-11-01-dependabot-alerts-enterprise-level-rest-api

Leaving open to track for GHES release!

**Comment by ankneis** [comment]
This is now available on GHES 3.8: https://github.blog/2023-03-07-github-enterprise-server-3-8-is-now-generally-available/
