### ISSUE TITLE
Yarn 2 and Yarn 3 support in Dependabot updates

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#595]
### Summary

This item adds support for updating Yarn 2 and Yarn 3 dependencies automatically using Dependabot. 

### Intended Outcome

Dependabot can currently generate pull requests for repositories that use Yarn 1, but it does not support either Yarn 2 or Yarn 3. Later versions of Yarn have seen increasing adoption, so it's important that we support these to help developers stay on secure versions of their dependencies.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2022-10-20-dependabot-can-now-generate-security-and-version-updates-for-yarn-v2-and-v3/
