### ISSUE TITLE
Projects: Update multiple items with a group menu

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#596]
### Summary

Users will be able to bulk update items from the table, board, and roadmap layouts using a group menu. 

### Intended Outcome

Allowing users to update multiple items at once saves time by reducing manual toil. 

### How will it work?

Users will be able to delete and archive multiple items at once in a project view by grouping items and selecting an action from a drop down menu

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-08-10-github-issues-projects-august-10th-update/#group-menu-for-item-and-group-actions

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This shipped with GHES 3.12: https://docs.github.com/en/enterprise-server@3.12/admin/release-notes!
