### ISSUE TITLE
CodeQL support for projects built with C# 11 (beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#598]
### Summary

The [CodeQL analysis engine](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql) for [GitHub code scanning](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning) will be able to analyze projects built with C# 11.

### Intended Outcome

Currently, [CodeQL supports builds and standard language features up to C# 10](https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/). C# 11 is due to be released before EOY 2022. Updating CodeQL support will allow customers who want to adopt C# 11 to benefit from CodeQL's comprehensive security analysis.

### How will it work?

If a project contains C# 11 code, or if C# has been [configured as a language to be analyzed](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#changing-the-languages-that-are-analyzed) in the [code scanning workflow](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#about-code-scanning-configuration), CodeQL will pick up C# 11 project builds. No further configuration changes are needed. As soon as the analysis is finished, the CodeQL results will then become visible to you in the "Security" tab and on pull requests. C# 11 support will also be available through the [CodeQL CLI](https://codeql.github.com/docs/codeql-cli/about-the-codeql-cli/).

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-04-04-code-scanning-adds-support-for-c-11-net-7. Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This has shipped with GHES 3.10: https://github.blog/2023-08-29-github-enterprise-server-3-10-is-now-generally-available/
