### ISSUE TITLE
Billing API for metered products (i.e. Actions and Packages)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#60]
**Summary**
We are publishing a new `/billing` REST API endpoint that will provide data on Actions and Packages usage.

**Intended Outcome**
Customers can integrate with our APIs to monitor their usage.

**How will it work?**
The first iteration will add endpoints for the current billing cycle: `/settings/billing/actions`, `/settings/billing/packages`, `/settings/billing/shared-storage`.

We will build upon that to allow for expanded time ranges and specified repos/workflows.

**Comment by alexcnichols** [comment]
Documentation: https://docs.github.com/en/free-pro-team@latest/rest/reference/billing
