### ISSUE TITLE
Secret scanning: Metrics for push protection

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#603]
### Summary

In-product metrics that will live in an organization's security overview pages on how a push protection is performing, e.g. number of blocked and bypassed secrets.

### Intended Outcome

Allow GitHub Advanced Security customers to understand the value of push protection for their organization and take any needed action based on the provided metrics.

### How will it work?

In an organization's "Security" tab, organization admins can view metrics specific to push protection. These metrics include the number of blocked secrets, whether or not those secrets were bypassed to create alerts.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-07-31-secret-scanning-shows-metrics-for-push-protection-at-the-organization-level/

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
Closing as a duplicate of: https://github.com/github/roadmap/issues/604
