### ISSUE TITLE
Secret scanning: Metrics for custom patterns

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#604]
### Summary

In-product metrics on how a specific custom pattern is performing. The metrics can be accessed in the UI page of the specific custom pattern.

### Intended Outcome

We want to provide customers with insight into how their custom patterns perform. Based on those metrics, admins can take action to enable the custom pattern for push protection, edit the pattern to make it less noisy, or leave the pattern running as is.

### How will it work?

When viewing a custom pattern, admins will be able to view metrics about the specific custom pattern. Metrics will include the number of false positives, open alerts, etc.

**Comment by ankneis** [comment]
🚢 This has shipped to dotcom: https://github.blog/changelog/2023-03-31-secret-scanning-now-shows-metrics-for-custom-patterns. Leaving open to track for GHES release!

**Comment by ankneis** [comment]
This has shipped with GHES 3.10: https://github.blog/2023-08-29-github-enterprise-server-3-10-is-now-generally-available/
