### ISSUE TITLE
Secret scanning: Enable at the enterprise level with the Enterprise-level REST API

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#605]
### Summary

A REST API to enable GitHub Advanced Security, secret scanning, and push protection.

### Intended Outcome

Customers can use the enterprise level REST API to automate processes around the enablement of secret scanning and push protection.

### How will it work?

With the enterprise REST API, GitHub Advanced Security customers can:
- Enable or disable GitHub Advanced Security
- Enable or disable secret scanning
- Enable or disable push protection for secret scanning
- Add or update a custom link to display to contributors who are blocked from pushing a secret

**Comment by ankneis** [comment]
🚢 This has shipped to dotcom: https://github.blog/changelog/2022-12-13-enable-secret-scanning-with-the-enterprise-level-rest-api. Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This is now available on GHES 3.8: https://github.blog/2023-03-07-github-enterprise-server-3-8-is-now-generally-available/
