### ISSUE TITLE
Code scanning tool status page 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#606]
### Summary

Code scanning will include a new tool status page, which will show detailed information about the security tools/engines (including CodeQL) set up on a repository, and will provide information like coverage of files and directories. Users will be able to see errors for analysis and its configuration. 

### Intended Outcome

The code scanning tool status page will help users complete the setup successfully by raising awareness if the setup has failed or is incomplete. It will also allow users to maintain a successful setup by understanding if the success status has changed due to the latest changes in the repository. The tool status page will be a new entry point to debug and configure code scanning tools.

### How will it work?

Code scanning will report the status of the tool based on the number of files that were built and analysed. Users will be able to tweak and improve their analysis configuration based on the provided information.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-03-28-code-scanning-shows-the-health-of-tools-enabled-on-a-repository. Leaving open to track for GHES release.

**Comment by ankneis** [comment]
🚢 This has shipped with GHES 3.9: https://docs.github.com/en/enterprise-server@3.9/admin/release-notes. Closing as complete.
