### ISSUE TITLE
Transfer Organizations between GHEC Classic Enterprise Accounts

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#607]
### Summary

This feature enables GitHub Enterprise Cloud administrators to move organization move from one enterprise account to another without having to drop the org into a free state or request that GitHub Support transfers the organization for them. 

Note this feature enables the transfer of an organization between enterprise accounts only if both enterprise accounts are GHEC Classic accounts - not EMUs - and the administrator is an enterprise owner for both enterprise accounts. A future roadmap item will bring the ability to transfer an organization between GHEC Classic accounts which have different enterprise owners.

Customers wishing to move organizations into a GHEC EMU enterprise are advised to use the [GitHub Enterprise Importer](https://docs.github.com/en/early-access/enterprise-importer) to manage this. 

### Intended Outcome

Customers who are growing through acquisitions and partnerships can easily, confidently and quickly transfer organizations into their enterprise cloud account.

### How will it work?

An enterprise administrator with access to two enterprise accounts will:
- See a UI option in the enterprise account that is available within the organization's gear drop-down to `transfer` an organization
- Have the ability to invite an organization from another enterprise account to pull an organization over via the invitation flow

**Comment by ankneis** [comment]
🚢 This has shipped. Here is the changelog: https://github.blog/changelog/2022-11-01-transfer-organizations-between-ghec-enterprise-accounts/
