### ISSUE TITLE
Enterprise Membership & Improved Consumed License Reports

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#608]
### Summary

A new enterprise membership CSV report enables enterprise administrators to better analyse their membership and take action based on that information. Alongside this, we have also improved the enterprise consumed licenses report to provide more information to administrators.

### Intended Outcome

With these enhanced reports, customers should be able to more easily answer license consumption and enterprise access questions.

### How will it work?

The Consumed Licenses report is available both in GHEC UI on the enterprise account's `settings` > `enterprise licensing` page as a download button for `User licenses` as well as via API.

<img width="1425" alt="Screen Shot 2022-09-30 at 6 22 01 AM" src="https://user-images.githubusercontent.com/58748846/193249774-09ac320f-f401-429c-9b29-b984cb4aa55f.png">

The enterprise membership report, it is downloadable via the enterprise account's `People` page as a download button. 

<img width="1407" alt="Screen Shot 2022-09-30 at 6 24 01 AM" src="https://user-images.githubusercontent.com/58748846/193250107-e72fcfe7-a60a-4f2e-ab21-92cd62d352da.png">

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2022-11-29-new-and-improved-enterprise-reports-now-generally-available
