### ISSUE TITLE
Actions: Private networking support for secure connections to customer VNETs

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#614]
**Summary**
Enterprise customers can now set up Actions to connect with their internal networks in under 10 minutes! GitHub has introduced a turnkey set of tools that allow enterprise admins to give GitHub Actions access to the resources their teams need inside their private networks. This means that teams can now access their internal APIs, Databases, Artifactory instances and more from GitHub’s hosted runners. 

**Intended Outcome**
This enables Actions to connect to Azure services, such as Azure Storage, in a secure manner using service endpoints or to on-premises data sources, taking advantage of user-defined routes. You can also connect Actions to a network virtual appliance to inspect all outbound traffic and take actions according to allow and deny rules. Finally you can configure Actions to use custom DNS and configure network security group (NSG) rules to specify egress traffic restrictions.

**How will it work?**
With the introduction of GitHub’s secure networking for Actions, customers on Azure can now set up an integration with their [Azure subscriptions Virtual Networks ](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-overview)(VNets). This solution enables service traffic to go through the Azure backbone network, isolating communication from the public Internet and effectively injecting the Actions runner into your private network.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-11-01-github-hosted-runners-private-networking-with-azure-virtual-networks-public-beta
