### ISSUE TITLE
Actions: Enhanced GitHub Actions Usage Metrics and Insights

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#615]
**Summary** 
Organization and Enterprise Admins can now better understand what is driving their GitHub Action use by repo, workflow and Organization. Organization Admins can now interact with information empowering them to answer questions like which repo is using the most minutes, which workflows have changed resulting in more use and how their split of minutes usage compares across different operating systems.

**Intended Outcome**
Previously, Admins had to look across a range of un-supported data sources extracting information and then still struggled to answer questions like ‘which workflow is driving the most use across all of my runner types’ or ‘which of my repositories are triggering workflow runs and how are those workflows being triggered’. Understanding how the answers to these questions change over time or in comparison to another repository’s usage required even more custom tooling. Enhanced Usage Metrics solves these problems and more.

**How will it work?** 
The Actions Usage Metrics dashboard is customizable by date range and provides several filtering and summation tools for an organization's repositories. 

Included metrics:
Billable minutes
User counts 
Usage trends
Total usage forecasts 
Data sorting column header 
Data export (.csv format)
Successful workflow runs by invoking event (PR, Push, Merge, etc)
Successful workflow runs by runtime (macos, ubuntu, windows, etc)
Successful workflow runs by runner type (self hosted, hosted, custom)
Successful workflow runs by repository visibility (public or private)

**Comment by ankneis** [comment]
This has shipped to a private beta!
