### ISSUE TITLE
GitHub Sponsors for companies – invoiced billing GA

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#618]
**Summary**
Enable groups, corporations, and institutions to fund projects and developers that they depend on

**How will it work?**
Allow an organization to sponsor individuals and organizations via an invoice

**Reasoning**
Large institutions—companies, enterprises, governments, and more—are the biggest users of open source. They have a clear interest to ensure the projects and developers they depend on not only survive but thrive. Funding open source will help these sponsors to avoid abandonware, keep security tight, and attract technical talent while they’re at it.

**Notes**
This is the successor to https://github.com/github/roadmap-internal/issues/79

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-04-04-export-your-sponsorable-dependencies-and-sponsor-many-in-one-checkout/
