### ISSUE TITLE
Copilot for Teachers - [GA]

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#621]
### Summary

GitHub already provides [multiple benefits for verified teachers](https://education.github.com/teachers) including:

* [GitHub Classroom](https://classroom.github.com/) for managing assignments
* [GitHub Team](https://github.com/team) for courses, coding clubs, and nonprofit research
* [GitHub Codespaces](https://github.blog/2022-05-09-prepare-for-next-semester-with-github-global-campus-and-codespaces/) cloud-hosted development environments

**Now, verified teachers can also use [GitHub Copilot](https://copilot.github.com) free of charge.** GiHub Copilot is an AI pair programmer that uses [OpenAI Codex](https://openai.com/blog/openai-codex/) to suggest code and entire functions in real time, right from your editor. Earlier this summer, following a successful year long technical preview with more than 1.2 million developers, [we launched GitHub Copilot for individuals](https://github.blog/2022-06-21-github-copilot-is-generally-available-to-all-developers/). The feedback received from the community has made it abundantly clear: AI is one of the best tools to empower the next generation of developers. With GitHub Copilot, developers have more time and space to focus on solving bigger problems and building even better software.

### Intended Outcome
GitHub Copilot is effective at solving many introductory programming assignments, which may impact how you assess your students. One [study](https://doi.org/10.1145/3511861.3511863) found that solutions generated by GitHub Copilot placed it amongst the top 25% of students in a cohort.

We recognize that student's use of GitHub Copilot will likely change the way you plan new lessons, and are committed to partnering closely with our teacher community on how GitHub Copilot can support you and your students. By offering GitHub Copilot free of charge to teachers, we hope to make it easier for teachers to understand and anticipate the impact on student assignments. If you’re interested in sharing your experience, feedback, or ideas, please [join the conversation](https://github.com/community/Global-Campus-Teachers/discussions/118) with other verified teachers on GitHub Global Campus.

If you're a teacher, but haven't been verified yet, [join GitHub Global Campus for teachers.](https://education.github.com/discount_requests/teacher_application)

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/2022-09-08-github-copilot-now-available-for-teachers/
