### ISSUE TITLE
Fine-grained PATs support for GraphQL

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#622]
### Summary

While fine-grained PATs support GitHub's REST APIs, the public beta does not include GraphQL support.  This roadmap item tracks the ability to use a fine-grained PAT against all the same GraphQL APIs that a GitHub App can target. 

### Intended Outcome

Lots of GitHub features are surfaced via the GraphQL API, and we need fine-grained PATs to be able to use them. When complete, fine-grained PATs will have parity with GitHub Apps when it comes to GraphQL. 

### How will it work?

We'll be confident in the correctness and security of fine-grained PAT access to GraphQL APIs.  You'll be able to use a fine-grained PAT anywhere you could use a user-to-server GitHub app token.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-04-27-graphql-improvements-for-fine-grained-pats-and-github-apps/.

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This has shipped with GHES 3.10: https://github.blog/2023-08-29-github-enterprise-server-3-10-is-now-generally-available/
