### ISSUE TITLE
Change the default branch name for new repositories from `master` to `main`

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#63]
**Summary**
Many communities, both on GitHub and in the wider Git community, are considering renaming the default branch name of their repository from `master`. GitHub is gradually renaming the default branch of all our repositories from `master` to `main`. We're committed to making the renaming process as seamless as possible for project maintainers and all of their contributors. 

**Intended Outcome**
We’re making changes to GitHub in a few phases, designed to cause as little disruption to existing projects as possible.

- **Now:** we're supporting early movers by redirecting links that contain a deleted branch name to the corresponding link in the repository's default branch
- **This summer:** we're introducing a configurable default branch for new repositories
- **Later this year:** we're enabling seamless branch rename for existing repositories

**How will it work?**
[`github/renaming`](https://github.com/github/renaming) is our up-to-date guidance on how and when to rename your default branch.

**Comment by alexcnichols** [comment]
https://github.blog/changelog/2020-08-26-set-the-default-branch-for-newly-created-repositories/

**Comment by alexcnichols** [comment]
https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/
