### ISSUE TITLE
Enabling Developers to Start New Projects in Codespaces (Improved New Project Experience)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#635]
### Summary

For individuals new to coding, as well as experienced developers, Codespaces simplifies the creation of a development environment. This enables learners to jump directly into learning, and experienced developers to focus on writing their code. 

Currently, individuals must create a repository through Github and then create a codespace from that repository. This experience inhibits developers abilities to jump directly into development, and flips the development loop on its head.

### Intended Outcome

Developers should expect to be able to jump directly into a codespace without requiring a dependency on a repository. New developers should be able to jump into learning scenarios without having to worry about setting up the environment they are learning in. Experienced developers should be able to immediately start writing their code. All developers should be able to create a repository when they are ready to publish their code and start sharing with the greater GitHub community.

### How will it work?

Unpublished codespaces will become the default introduction to codespaces for all developers. Developers should be able to access a development experience without having to create a custom codespace just by having a GitHub account and accessing GitHub.com/codespaces. 

### Key Scenarios

**Create:**
We will maintain a set of template repositories for developers to use to create unpublished codespaces. These template repositories will contain all of the necessary dependencies for a developer to start building using the language or framework they desire.

**Upgrade:**
Once developers have developed their projects to a point where they are ready to share and publish their work, an upgrade experience to a repository should be available. Users will be able to upgrade their projects through their VCM.

**Delete:**
When a user wants to delete their unpublished codespace they will be able to delete it through the same process as deleting a codespace. A user will be able to go to github.com/codespaces, click the ellipses on their project, and select delete. If a user has unpublished changes in the codespace, or the codespace is unpublished, they will be prompted to confirm they want to delete a codespace with unpublished changes.

**Export:**
In the case of a user running out of entitlements, a user will be able to go to github.com/codespaces and publish the codespace to a new repo. This will enable the user to get access to their code through Git, and ensure that a user has access to their code if they run out of entitlements.

**Comment by ankneis** [comment]
🚢 This has shipped! https://github.blog/changelog/2022-11-09-codespace-templates/
