### ISSUE TITLE
GitHub Actions: Secure Shell Debugging (Preview)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#637]
### Summary

GitHub is building an SSH feature for Actions that will make troubleshooting workflows much easier. Secure Shell Debugging will be available on all hosted runner types to GitHub Enterprise customers. This feature offers customers a flexible and powerful tool that will reduce the number of iterations where the developer must edit, commit, and then push a workflow while debugging.

### Intended Outcome

There are hundreds of reasons that could cause a CI/CD pipeline to fail and sometimes connecting to the runner environment is the easiest and fastest way to debug.  Secure Shell Debugging will reduce the time it takes to troubleshoot a problematic workflow.  Additionally, offering a native SSH experience enables customers to use existing GitHub control mechanisms to provision the right access to developers.

### How will it work?

GitHub Enterprise customers can turn Secure Shell Debugging on at the organization level or for select repositories.  Developers with write access can initiate an SSH session from GitHub.com or the GitHub Command Line Interface (CLI). From the CLI, Actions will attempt to use any existing keys or, if a compatible key is not detected, generate a new SSH key that can be used to securely connect to the runner. Customers originating from GitHub.com will see a prompt with instructions on how to SSH into the runner.

Developers can enable SSH when re-running a job or initiate a session into an already running workflow. The use of SSH during a workflow run does not interrupt the job. However, if a job completes but an active SSH session is detected, the runner will remain open until the session is closed. Developers can select specific jobs to create an SSH session for when triggering a rerun from GitHub.com. For those selected jobs, SSH will become available at the conclusion of the job run.

**Comment by ankneis** [comment]
This issue is being closed as outdated. For more information, please check out this [Discussion post](https://github.com/github/roadmap/discussions/1014). Stay tuned for new additions to our refreshed public roadmap!

**Comment by ankneis** [comment]
We wanted to provide more details on why we removed this from the roadmap. We understand this is important and we have this work under consideration. We're removing it from our roadmap for now until we have more certainty on our timeline.

While we don’t have a timeline just yet, we’d love to hear your thoughts on what you’d like to see - feel free to upvote and share your feedback in this [dedicated thread](https://github.com/orgs/community/discussions/34968).
