### ISSUE TITLE
Actions: GitHub Enterprise Server can support Google Cloud Storage

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#64]
**Summary**
Adds support for Google Cloud Storage as a blob storage provider for Actions on GitHub Enterprise Server.

**Intended Outcome**
GitHub Actions for Enterprise Server requires an S3-compatible blob storage provider. Before this release, supported options are: S3, Azure Blob Storage, and Min.io with NAS Gateway.

This release adds support for Google Cloud Storage, enabling customers to run GitHub Enterprise Server entirely in Google Cloud Platform.

**How will it work?**
Administrators will use the Enterprise Server management console or CLI to configure Actions to use Google Cloud Storage.

**Comment by spaltrowitz** [comment]
this has shipped to GHES 3.7! https://docs.github.com/en/enterprise-server@3.7/admin/github-actions/enabling-github-actions-for-github-enterprise-server/enabling-github-actions-with-google-cloud-storage

closing out this issue
