### ISSUE TITLE
Code scanning default setup is available for all CodeQL supported languages, excluding Swift

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#641]
### Summary

Repositories will be able to use code scanning's default setup for enabling code analysis for [all languages supported by CodeQL](https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/), excluding Swift. Extending support to include Swift will follow [soon](https://github.com/orgs/github/projects/4247/views/1?filterQuery=label%3A%22code+scanning%22).

### How will it work?

Repositories will be able to use code scanning default setup in order to attempt to analyze all CodeQL supported languages using code scanning default setup. JavaScript/TypeScript, Ruby and Python are selected by default; the other languages can be explicitly selected. If a specific language fails, it's possible to deselect the failing language from the configuration.

This feature will be available at the repository level.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-06-29-code-scanning-default-setup-is-now-available-for-all-codeql-supported-languages-excluding-swift!

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This has shipped with GHES 3.10: https://github.blog/2023-08-29-github-enterprise-server-3-10-is-now-generally-available/
