### ISSUE TITLE
Projects: Improve Group By for multi-select fields

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#649]
### Summary

Currently, grouping multi-select fields in Projects does not create a distinct group for each value if multiple values are selected for the same row. We have heard from users that this is not the expected or desired behaviour. We intend to update group by for multi-select values so that each value creates a distinct group. 

### Intended Outcome

If a user creates a table view grouped by assignee and multiple assignees are assigned to an issue, a group will be created for each set of assignees. 

For example if Tom is assigned to 6 issues, and Mary is assigned to 6 issues and they are both assigned to 4 issues three groups will appear in the table - one for Tom with 6 issues, one for Mary with 6 issues and one for Tom and Mary with 4 issues. This is confusing because both Tom and Mary want to be able to see all 10 issues assigned to each of them. 

### How will it work?

We intend to update this behaviour so that when a user groups by a multi-select field in the table view a distinct group will appear for each value. Using the example from above - only two groups appear, one for Tom with 10 issues and one for Mary with 10 issues.

**Comment by ankneis** [comment]
Closing this issue in favor of: https://github.com/github/roadmap/issues/786
