### ISSUE TITLE
Enterprise Upgrades include Enterprise Accounts

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#651]
### Summary

Existing customers who opt to upgrade to GHEC (from Free and Teams) will get an enterprise account as part of the upgrade experience. 

### Intended Outcome

We are bringing enterprise accounts to all of our enterprise customers.

### How will it work?

During the upgrade flow, the customer will be prompted to name their enterprise and once they complete the upgrade purchase, they will land inside their newly minted enterprise account alongside their originating organization.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-08-22-upgrade-with-an-enterprise-account/.
