### ISSUE TITLE
Projects: Organization templates 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#652]
### Summary

Users in organizations will be allowed to create project templates that others in their organization can use when creating new projects.

### Intended Outcome

Teams and users often want to be able to share out and learn best practices in how they set up and use their projects to plan and track their work. Projects templates allow teams to create consistency in their projects with standardized working patterns and structures, share best practices among teams and from other users, and reduce manual effort to get started with a new project. 

### How will it work?

Users will be able to toggle a project to become a template at the organization level from the project settings page, or copy a project into a template.

![image](https://user-images.githubusercontent.com/101840513/252499096-4e824767-746c-4481-8f0e-7cf52b9c3f8f.png)

Once a template is created, a user can open the template to make adjustments, and select `Use this template` to create a new project using the template.

![image](https://user-images.githubusercontent.com/101840513/252499134-eb244f37-855b-42f3-af64-f1412fea55b1.png)

The template library is also available when creating a new project, so you have a preview of what will be included in the project.

![image](https://user-images.githubusercontent.com/101840513/252499234-006a7ebb-027d-4f21-bfcc-76fbf196429f.png)

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-05-25-github-issues-projects-may-25th-update/#%F0%9F%8E%A8-project-templates-for-organizations.

Leaving open to track for GHES release!

**Comment by ankneis** [comment]
This has shipped with GHES 3.10: https://github.blog/2023-08-29-github-enterprise-server-3-10-is-now-generally-available/
