### ISSUE TITLE
View a trend of security feature enablement/security alerts for your organization

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#655]
### Summary
At the organization level, you will be able to view a trend of security feature enablement and security alerts in order to analyze your security program's performance.

### Intended Outcome
Today, enterprise users can see only the current status of security alerts and security feature enablement at the organization level.  It's not possible to get a historical view of trends across your organization.  With this feature, users will be able to see a trend of security feature enablement and security alerts at the organization level.

### How will it work?
We will offer two new pages in security overview at the organization level: security coverage trends and risk trends that will house trends graphs for the following security features:
* Dependabot alerts
* Code scanning alerts
* Secret scanning alerts
* Push protection _(enablement trends graph only)_
* GitHub Advanced Security _(enablement trends graph only)_

**Comment by ankneis** [comment]
This has shipped to dotcom: https://github.blog/changelog/2024-03-19-enablement-trends-for-security-products-public-beta/

And GHES 3.13!
