### ISSUE TITLE
Actions: Increase the cache size for a repo using shared storage

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#66]
**Summary** 
GitHub Actions enables customers to cache intermediate outputs and dependencies for their workflows via the [cache](https://github.com/actions/cache) action.  Currently this storage is limited to 5GB pre repository and is rotated based on the last access time for a given cache entry.  

**Intended Outcome** 
Having the ability to expand the cache size for a given repo can enable customers to improve the performance of their workflows for more scenarios and larger repos.

**How will it work?** 
We are now doubling the cache storage limit to 10 GB/repository to enable more customers to experience faster Jobs using GitHub actions.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-11-23-github-actions-cache-size-is-now-increased-to-10gb-per-repository/
