### ISSUE TITLE
Multi-user authentication for GHES Management Console - [GA]

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#660]
### Summary

GHES Management Console authentication is currently based on a single admin password. For many customers this is a security risk since this password is shared and there is no way of having an audit trail about which user made changes to the system.

We are therefore introducing a multi-user concept with a user management interface to the Management Console which will allow administrators to invite new users with different types of roles.

### Intended Outcome

Allow GHES administrators to create separate logins for each user that needs access to the Management Console in GHES.

### How will it work?

GHES administrators can create and manage users that have access to the Management Console from within the Management Console itself. Please note that these users are specific to the Management Console and are not system users, so the `admin` account will continue to be the only account that can be used to ssh into the appliance.

**Comment by ankneis** [comment]
🚢 This has shipped with GHES 3.8: https://github.blog/2023-03-07-github-enterprise-server-3-8-is-now-generally-available/
