### ISSUE TITLE
Dependabot version updates: support for private registries (Cloud Beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#67]
**Summary**
Dependabot support for private registries allows users to keep private packages secure by opening pull requests to update the packages' dependencies to the latest version.

**Intended Outcome**
Keep private package dependencies up to date and vulnerability-free.

**How will it work?**
Today, [Dependabot Version Updates](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) updates the packages you rely on to newer versions, even if the version on which you currently rely doesn't have any (known) vulnerabilities. Support for private registries allows users to configure which private registries they are using, and supply credentials for those, to allow Dependabot to update those packages' dependencies.

**Comment by alexcnichols** [comment]
https://github.blog/changelog/2020-12-02-dependabot-version-updates-from-private-github-repositories/

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-03-15-dependabot-private-registry-support-public-beta/
