### ISSUE TITLE
Actions: GitHub Enterprise Server can use GitHub-managed runners with GitHub Connect

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#72]
**Summary** 
This feature enables GHES to use Actions hosted runners for their workflows.

**Intended Outcome** 
Currently, GitHub Enterprise Server (GHES) can only use self-hosted runners with Actions. This will make it easier for GHES customers to run their workflows with hosted runners that require no configuration.

**How will it work?** 
Actions hosted runners provide VMs for Windows, Linux, and Mac with the common tools needed to build, test, and deploy your code. They automatically scale with a simple pay-as-you-go model so there is no maintenance.

**Comment by ankneis** [comment]
We are currently prioritizing other features on our roadmap at this time, and are removing this from the roadmap until we determine a better delivery date.
