### ISSUE TITLE
Actions: Use actions from internal repositories

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#74]
**Summary**
This feature enables workflows to use actions in internal repositories, without having to publish those actions to the GitHub Marketplace.

**Intended Outcome**
Currently, to use an action in an Actions workflow its code must be in the same repository as the workflow, or a separate public repository, or published to the GitHub Marketplace. This feature allows Actions workflows to use actions that have their code in an internal repository, which is important for customers that need to keep the code of their action private.

**How will it work?**
Users will be able to mark an internal repository as accessible to any workflow that exists in the same enterprise account.

**Comment by spaltrowitz** [comment]
shipped to dotcom! https://github.blog/changelog/2022-03-04-sharing-github-actions-within-your-enterprise-is-now-ga/

**Comment by spaltrowitz** [comment]
this has shipped to GHES 3.5! https://docs.github.com/enterprise-server@3.5/admin/release-notes#sharing-github-actions-within-your-enterprise-is-generally-available

closing out this issue.
