### ISSUE TITLE
Projects: Updated Projects header

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#761]
### Summary

We are updating the Projects header by surfacing project view configurations directly from the view, rather than within the view configuration dropdown menu. This includes options such as sorting, grouping, slicing, and visible fields. This will allow users to easily set up and configure their project views by making them more discoverable, accessible, and easy to use.

### Intended Outcome

We want to make it easy for users to set up and configure their project, as well as knowing how an existing project is set up. Updating the Projects header to include more customizations directly from the view will make these less confusing and less hidden.

### How will it work?

When a user creates a new project or updates an existing project, they will be able to explore and use the view-level customizations from a more visible and discoverable location, so they can select and configure options such as their `sort` field, `group` field, or visible `fields` to display on the view. When creating a new project view, a user will also be able to select the layout type directly.

**Comment by ankneis** [comment]
This issue is being closed as outdated. For more information, please check out this [Discussion post](https://github.com/github/roadmap/discussions/1014). Stay tuned for new additions to our refreshed public roadmap!

**Comment by ankneis** [comment]
We wanted to provide more details on why we removed this from the roadmap. We are still considering this improvement to the Projects navigation, but we've removed it from our roadmap for now until we have more certainty on the delivery timeframe. 

If you’re interested in this feature, please share your feedback in the [GitHub community](https://github.com/orgs/community/discussions/) so we can track interest and consider it in the future.
