### ISSUE TITLE
Projects: Bulk edit items in board layout

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#762]
### Summary

We are providing users with the ability to perform bulk-edits to their board items. This includes updated keyboard shortcuts to navigate through their board and make adjustments to the board items within and between a column, as well as support for multi-select drag and drop to update multiple items at once.

### Intended Outcome

Supporting multi-select drag and drop will allow users to quickly make adjustment to their items when planning out and updating their work, such as moving multiple items from `In progress` to `Done` in a single action. Providing keyboard shortcuts to navigate the board and update items will make it easy to quickly change where an item ranks within a column, as well moving it to a different column.

### How will it work?

Select multiple board items to drag and drop them from one column to another, or utilize keyboard shortcuts to move an item within a column or to a different column.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-05-25-github-issues-projects-may-25th-update/#%F0%9F%92%AA-%E2%8C%A8%EF%B8%8F-bulk-updates-and-keyboard-navigation-on-boards.

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This has shipped with GHES 3.10: https://github.blog/2023-08-29-github-enterprise-server-3-10-is-now-generally-available/
