### ISSUE TITLE
Organization archiving

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#764]
### Summary

This release enables organization administrators to archive an entire organization at once. Archiving an organization will make all the repositories in the org read-only, prevents the creation of new repositories, and adds a banner at both the org profile level and each repo indicating that it is archived.

### Intended Outcome

Enterprises with deep usage of GitHub often end up with a confusing and hard-to-manage proliferation of organizations that can number in the dozens or even hundreds. Internally, we had 106 open source orgs at the beginning of the year! Many of these are stale or obsolete, but currently there is no easy way to archive a once-active organization: you have to individually archive each repository in the org, and even then the top-level org still permits repo creation, new teams, etc. This adds to the toil of enterprise administration and makes for an inconsistent, unpleasant experience for open source maintainers, OSPO managers, and IT teams responsible for managing their GitHub presence.

Our new feature lightens this administrative burden. 

### How will it work?

This will add a button to the Organization Settings "Danger Zone" which will:

* archive all the repositories in the organization
* set a key in the API to indicate the org has been archived
* restrict most activities in that organization such as creating new repos

![image](https://user-images.githubusercontent.com/94867353/253099205-f88e9371-1ac5-4c46-b3b7-fcf7bc4607fd.png)

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-06-15-organization-archiving-public-beta. 

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This shipped with GHES 3.11: https://docs.github.com/en/enterprise-server@3.11/admin/release-notes
