### ISSUE TITLE
Dependency review works with dependencies submitted with the dependency submission API 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#765]
### Summary

The dependency review API and will now include dependencies submitted via the dependency submission API. The [dependency review action](https://github.com/actions/dependency-review-action) will also consider dependencies submitted via the dependency submission API, and will fail if a PR introduces dependencies with known vulnerabilities.

**Comment by ankneis** [comment]
This shipped with GHES 3.11: https://docs.github.com/en/enterprise-server@3.11/admin/release-notes
