### ISSUE TITLE
pnpm support for Dependabot Updates

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#768]
### Summary

With this feature, any developer who manages their project dependencies using the pnpm package manager will be able to get Dependabot version updates for these dependencies. Security updates for pnpm will not be supported at this time.

### Intended Outcome

This increases the number of ecosystems supported by Dependabot version updates and increases our market of potential users.

### How will it work?

You will be able to configure Dependabot to update versions of dependencies defined in the pnpm package manager.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-06-12-dependabot-version-updates-now-supports-pnpm/.

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This has shipped with GHES 3.10: https://github.blog/2023-08-29-github-enterprise-server-3-10-is-now-generally-available/
