### ISSUE TITLE
Pages: Private Access

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#77]
**Summary** 
For GitHub Enterprise users, they'll be able to make their Pages sites private to the world. Only those individuals that have access to the repository housing the site will have access to the private pages site.

**Intended Outcome**
In cases where organizations want to build an intranet site or publish internal documentation, private pages will allow organization to keep the content private to their organizations.

**How will it work?**
For Enterprise Cloud customers, if a repository is private, they'll be able to go to the Pages settings and change the visibility of the pages site from `public` to `private`. Once that change is made, a new pages URL will be created that's distinct from the rest of the pages sites that exists within that organization.

**Comment by alexcnichols** [comment]
https://github.blog/changelog/2021-01-21-access-control-for-github-pages/
