### ISSUE TITLE
GitHub Actions Importer - Bamboo Migrations

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#770]
### Summary

GitHub Actions Importer helps users plan, forecast, and automate the migration of their existing CI/CD pipelines to GitHub Actions. With this update, we will be adding support for Bamboo. Bamboo users can migrate their pipelines to GitHub Actions easily and for free using the official GitHub CLI. 

### Intended Outcome

- Simplify the pipeline migration process for Bamboo users by automating manual and tedious steps
- Reduce the potential for errors during migration and speed up development teams

### How will it work?

Users will be able to migrate existing Bamboo pipelines to GitHub Actions using the `audit`, `forecast`, `dry-run`, and `migrate` subcommands of `gh actions-importer`

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-05-22-github-actions-importer-bamboo-server-and-data-center-migrations-public-beta/.
