### ISSUE TITLE
Actions: Built-in deployment protection rules (gates)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#771]
### Summary

We are now adding support for built-in protection rules which can be natively enabled on all environments. These would compliment the community powered custom protection rules which are powered by GitHub Apps. 

### Intended Outcome

Built-in protection rules enable us to provide key CD capabilities within "environments" by default. These preempt the experience for “discovery” and “installation” needed by custom rules powered by "GitHub Apps".  

### How will it work?

Built-in protection rules make “Environments” more robust with native gating capabilities which tie into the other GitHub features that we support across our product.

**Comment by ankneis** [comment]
We are currently prioritizing other features on our roadmap at this time, and are removing this from the roadmap until we determine a better delivery date.
