### ISSUE TITLE
GitHub Actions Starter workflow improvements

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#772]
### Summary

Previously, to create a [custom starter workflow](https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization#creating-a-starter-workflow), customers needed to add their starter workflows to a public .github repository in their organization. However, organizations don't want to maintain their custom starter workflows in a public repository. Now, org admins have control to choose their own repository(s) (public/private/internal) in the organization to store their custom starter workflows. Any workflow stored in starter-workflows folder in the chosen repositories will be shown as a org suggested starter workflows for the developer. 

And we are also enhancing the new workflow experience in the repository. You will see a dedicated page for showing organization starter workflows.

### Intended Outcome

Org admins can choose specific repositories (public, private, internal) of their choice to maintain their custom starter workflows. Developers can see the org suggested starter workflows when they try to create a new workflow.

### How will it work?

- Org admin configures the set of repositories to use for storing starter workflows.
- Team members can contribute and store the starter workflows in the starter-workflows folder in the chosen repositories.
- The visibility of the repository decides in what repositories the starter workflow shows up as a suggestion.
- When a developer clicks on new workflow in a repository, he/she can see the org suggested starter workflows in a separate section.

**Comment by ankneis** [comment]
This issue is being closed as outdated. For more information, please check out this [Discussion post](https://github.com/github/roadmap/discussions/1014). Stay tuned for new additions to our refreshed public roadmap!

**Comment by ankneis** [comment]
We wanted to provide more details on why we removed this from the roadmap. We continue to plan to make improvements to make it easier to get started with GitHub Actions. But we're removing this from our roadmap for now until we have more certainty on our timeline and approach. 

We’d love you to share your thoughts in this [dedicated thread](https://github.com/orgs/community/discussions/25764)—your input plays a critical role in helping us set priorities.
