### ISSUE TITLE
GitHub Actions configuration variables - GA

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#773]
### Summary

Previously, customers needed to store this configuration data as encrypted secrets in order to reuse values in Actions features like reusable workflows. While extremely secure, this method did not allow for easy storage and retrieval of non-sensitive configuration data such as compiler flags, usernames, or server names.

Configuration variables allow you to store your non sensitive data as plain text variables that can be reused across your workflows in your repository or organization. You can define variables at Organization, Repository, or Environment level based on your requirement.

### Intended Outcome

- Configuration variables help developers define their non-sensitive information as plain text variables that can be consumed across multiple workflows in the repository.
- Configuration variables allows you to define default parameters for tools like our Java compiler at an organization level, but permit individual development teams to override them as they see fit.
- Configuration variables help DevOps team to provide a ‘golden path’ for build and deployment patterns while still allowing customization and control by the developers we support.

### How will it work?

- Customer can create new Variables at Organization, Repository and Environment level.
- Customers can refer to the value of the variable in the workflow documents using the contruct `${{vars.<variable name>}}`
- The inheritance model for variables i.e. Org, Repo, Env work similar to secrets.

**Comment by ankneis** [comment]
Please continue to refer to our updated Public Roadmap for the latest ships, including updates on the continuation of these projects.

**Comment by ankneis** [comment]
This was prematurely closed and has actually been shipped to GA! 🚢
