### ISSUE TITLE
GitHub Enterprise Server: See how migrations are progressing during an upgrade

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#775]
### Summary

When upgrading to a new version of GHES we do not provide any information about how the upgrade is progressing. We know that running the necessary database migrations is one of the longest parts of any upgrade, so we want to provide more insight into how this step of the upgrade is progressing.

### Intended Outcome

Starting in GitHub Enterprise Server 3.9, enterprise administrators will be able to see the progress of the migrations that are running as part of an upgrade **in real time**. 

### How will it work?

We will print concise and easy-to-read information to the SSH console about the migrations that are running during an upgrade. Administrators will be able to monitor this information **in real time** to see how the migrations are progressing.

**Comment by ankneis** [comment]
🚢 This has shipped with GHES 3.9: https://docs.github.com/en/enterprise-server@3.9/admin/release-notes. Closing as complete.
