### ISSUE TITLE
Projects: Increase project item limit 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#776]
### Summary

Currently, projects can only support 1200 active items and 10,000 archived items but we've heard from many larger teams that these limits are too low for the work they need to track such as long-running backlogs. While we can't completely remove the limit for projects, we will raise the limit to approximately 50k active items to better support this scenario.

### Intended Outcome

For long running projects or all-encompassing backlogs for companies, the current limit for project items is too constricting. In order to better serve our large team and enterprise customers, we need to increase this limit so that their projects can grow as they do.

### How will it work?

Projects will work as they do now, just with a higher upper limit on active items.

**Comment by ankneis** [comment]
🚢 This has shipped to beta: https://github.blog/changelog/2024-02-12-github-issues-projects-projects-without-limits-private-beta/
