### ISSUE TITLE
Security overview alert-centric view dynamic grouping (beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#777]
### Summary
This feature enhances the three alert-centric views (Dependabot, code scanning, and secret scanning) in security overview by enabling you to dynamically group alerts by various attributes such as repository, ecosystem, CVE, and team.

### Intended Outcome
Enterprise users need to be able to group the number of security alerts by specific attributes, such as a particular CVE or team. Currently, the only way to do this is to download data via the REST API and summarize it in a spreadsheet. This feature aims to provide users with more dynamic views to quickly identify the most critical security risks and prioritize remediation efforts.

### How will it work?
You will be able to select an attribute to group by via a drop-down at the top of each of the three alert-centric views: Dependabot, code scanning, and secret scanning. Security alerts will be grouped by the selected attribute, and aggregate counts will be displayed, similar to how [GitHub Projects functions](https://docs.github.com/en/issues/planning-and-tracking-with-projects/customizing-views-in-your-project/changing-the-layout-of-a-view).

**Comment by ankneis** [comment]
We are excited to bring more AI capabilities to GHAS. As a result, this feature’s development is on hold. We appreciate your understanding and welcome your feedback in the [GitHub community](https://github.com/orgs/community/discussions/categories/code-security).
