### ISSUE TITLE
Comprehensive code security analysis with an enterprise-level security overview dashboard

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#779]
### Summary
This feature provides for additional views of code security—at the enterprise, presenting critical metrics to evaluate your security and identify areas for improvement.

### Intended Outcome
Security managers face challenges in analyzing the extensive data generated by security products. The volume of alerts can be overwhelming, leading to critical questions such as, "Are we making progress?" "Where should we focus our efforts?" and "What are our priorities?" This dashboard enables security managers to make informed decisions, prioritize tasks, and monitor progress, enhancing code security and ultimately reducing vulnerability.

### How will it work?
The security overview dashboard will serve as the primary view for code security, providing a comprehensive analysis of critical metrics that drive behavior. You'll be able to access the dashboard by clicking on the security tab, displaying a visually intuitive, one-page view of the most relevant information to achieve your code security objectives.

**Comment by ankneis** [comment]
Closing as a duplicate of: https://github.com/github/roadmap/issues/978
