### ISSUE TITLE
Code security transaction report in PDF

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#781]
### Summary
This feature enables you to generate a report of security alerts occurring during a specified period and export the results in PDF format.

### Intended Outcome
Enterprise users must comply with strict security regulations that require producing transactional reports of security alerts. The reports must meet specific requirements and, generally, must be generated by the security vendor directly. This feature streamlines the compliance reporting process, enabling users to generate reports that meet regulatory standards.

### How will it work?
You will be able to specify a reporting period and generate a report of security alerts that occurred during that period. The report will be able to be generated in PDF format.

**Comment by ankneis** [comment]
With our exciting roadmap ahead, we've made the tough decision to deprioritize this feature to focus on higher-impact projects. If you’re interested in this feature, please share your feedback in the [GitHub community](https://github.com/orgs/community/discussions/categories/code-security) so we can track interest and consider it in the future.

**Comment by ankneis** [comment]
We wanted to provide more details on why we removed this from the roadmap. We are currently focusing on other features. This has been removed from the roadmap for now, and we will revisit it once we can provide a more accurate delivery estimate.

If you’re interested in this feature, please share your feedback in the [GitHub community](https://github.com/orgs/community/discussions/) so we can track interest and consider it in the future.
