### ISSUE TITLE
Export security coverage and security risk data in security overview to CSV

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#782]
### Summary
This feature enables you to export data on the security coverage and security risk pages in either CSV or JSON formats, providing a more efficient way to analyze and manipulate data.

### Intended Outcome
Enterprise users require the ability to analyze data using various creative approaches not intended to be supported by the product. This feature provides users with the ability to analyze and manipulate data more efficiently, improving overall productivity and data analysis.

### How will it work?
You will be able to click the export button on the security coverage or security risk page and select the desired export format, either CSV or JSON. Data from all pages within the view will be exported.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-09-12-csv-export-functionality-for-the-organization-level-risk-and-coverage-pages-on-the-security-tab/

**Comment by ankneis** [comment]
Reopening to track for GHES 3.15 release.

**Comment by ankneis** [comment]
This shipped with GHES 3.15: https://docs.github.com/en/enterprise-server@3.15/admin/release-notes

**Comment by ankneis** [comment]
Edit to clarify: This feature will be available with the GHES 3.15 general availability release on December 3
