### ISSUE TITLE
View a trend of security feature enablement/security alerts for your enterprise

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#783]
### Summary
At the enterprise level, you will be able to view a trend of security feature enablement and security alerts in order to analyze your security program's performance.

### Intended Outcome
Today, enterprise users can see only the current status of security alerts and security feature enablement at the enterprise level.  It's not possible to get a historical view of trends across your enterprise.  With this feature, users will be able to see a trend of security feature enablement and security alerts at the enterprise level.

### How will it work?
We will offer two new pages in security overview at the enterprise level similar to what we'll offer at the organization level: security coverage trends and risk trends that will house trends graphs for the following security features:
* Dependabot alerts
* Code scanning alerts
* Secret scanning alerts
* Push protection _(enablement trends graph only)_
* GitHub Advanced Security _(enablement trends graph only)_

**Comment by ankneis** [comment]
This has shipped to dotcom: https://github.blog/changelog/2023-06-15-risk-and-coverage-views-on-the-code-security-tab-for-enterprises-public-beta/

This has also shipped with GHES 3.10: https://docs.github.com/en/enterprise-server@3.10/admin/release-notes
