### ISSUE TITLE
Code scanning default setup makes it possible to use security-extended CodeQL query suite across your organization

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#784]
### Summary

At the organization level, you will be able to enhance the security of your repositories by easily choosing the `security-extended` query suite when enabling code scanning default setup for multiple repositories.

### Intended Outcome

Enterprises users have requested the ability to enable CodeQL at scale and use the `security-extended` query suite. Currently, the only way to enable CodeQL with the `security-extended` query suite is at the repository level. This creates a significant workload for users and leads to dissatisfaction with the process. 

This feature makes that job easier.

### How will it work?

With this feature, you will be able choose between the `security-extended`  and the `default` query suite when enabling repositories at the organization level when using the "enable all" feature or the multi-repo enablement feature on the security coverage page.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-07-20-select-a-query-suite-when-enabling-code-scanning-with-default-setup-at-the-organization-level/.

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This shipped with GHES 3.11: https://docs.github.com/en/enterprise-server@3.11/admin/release-notes
