### ISSUE TITLE
Repository properties integration with security overview

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#785]
### Summary
At both the enterprise and organization levels, you will be able to easily filter the security overview data by repository properties, giving you the ability to more efficiently analyze and manage security risks.

### Intended Outcome
Enterprises users have long-requested the ability to group their repositories for easier monitoring of code security status within security overview. Users have specifically requested the ability to filter the risk and coverage views and alert-centric view in security overview by a specific subset of repositories, rather than having to look at all repositories at once.

### How will it work?
With this feature, repository properties will be automatically available for filtering via the search bar. This means that you can easily search for specific repositories and filter results based on various repository properties you have setup.

**Comment by ankneis** [comment]
🚢 This has shipped - leaving open to track for GHES release!
