### ISSUE TITLE
Multi-account support on GitHub.com

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#795]
### Summary

With [enterprise managed users](https://docs.github.com/en/enterprise-cloud@latest/admin/identity-and-access-management/using-enterprise-managed-users-for-iam/about-enterprise-managed-users), more and more developers have to juggle a professional account and a personal account on GitHub.com. To switch between these accounts, developers must sign out of one and then sign in to the other. This can be particularly difficult for developers who frequently switch between those contexts.

To make switching between professional and personal accounts easier, we're building an account picker for GitHub.com that lets developers switch between accounts without signing out and signing in again. 

### Intended Outcome

It's easy for a developer to switch between their accounts on GitHub.com.

### How will it work?

Up to 10 user sessions will be cached in the browser, and one will be considered active. Developers can switch between cached sessions, changing which one is active. Authorization, SAML, and similar per-account or per-session information are not shared between cached sessions, so there's no leakage of data between them. 

When signing in to apps via OAuth, or being deeplinked to features like Pages that require authentication, users with multiple accounts in session will be asked which account to use to continue to the app or feature. 

When switching an account, as with sign-out or SAML session expiration, notifications will be sent to the other browser tabs open, ensuring that stale sessions and tabs don't result in confusion over which account is being used.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-11-03-multi-account-support-on-github-com
