### ISSUE TITLE
One-click enablement for Maven transitive dependency detection

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#796]
### Summary

Automatically enable the detection of transitive dependencies for Maven with a one-click set up through a repository's settings. 

### Intended Outcome

Dependency graph currently does not automatically detect transitive dependencies for Maven. Users can use a GitHub Action to detect and submit these dependencies to the dependency graph, but the discoverability of this action is low and the configuration hurdle can be high. A one-click enablement eliminates these hurdles for users and provides the dependency information they need.

### How will it work?

Users will be able to enabling automatic submission of dependencies for Maven through a repository's settings page. When enabled, GitHub will run a dynamic workflow to automatically build the maven project in the repository and submit it using the dependency submission API. The dependency insights page for the repository will show the complete Maven dependencies, and users will received Dependabot alerts for any known vulnerabilities. Users do not need to configure their own workflow files.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2024-07-29-automatically-submit-your-maven-transitive-dependencies-to-the-dependency-graph

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This feature will be included in a future GHES release. Stay tuned.
