### ISSUE TITLE
Secret scanning push protection bypass rules (beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#798]
### Summary

Security teams need more configurability over who can bypass push protection to balance security and developer productivity effectively. By integrating secret scanning's push protection into [repository rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets), Application Security teams can provide fine-grained control over which users can approve requested bypasses. Developers will have the ability to request approval from authorized users to push a blocked secret.

**Comment by ankneis** [comment]
This shipped with GHES 3.14: https://docs.github.com/en/enterprise-server@3.14/admin/release-notes
