### ISSUE TITLE
Repository Properties

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#799]
We are introducing a new feature for repositories called Custom Properties. Think of it as a key-value property store for each repository in which you can store arbitrary data about the repository.

- Organization admins can assign key-value metadata to repositories called custom properties
- Properties can be viewed and edited using the UI or API
- Users can search and filter lists of repositories using custom properties
- Organization admins can create rulesets targeting repositories matching custom property queries
- GitHub Advanced Security (GHAS) dashboards (including security risk and coverage) can be filtered using custom properties

**Comment by ankneis** [comment]
This shipped with GHES 3.13: https://docs.github.com/en/enterprise-server@3.13/admin/release-notes#3.13.0

Closing as complete.
