### ISSUE TITLE
Code scanning (Cloud)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#81]
**Summary**
We're integrating CodeQL analysis into GitHub, and building an interface for displaying static analysis results more generally. GitHub will show analysis results in the repository and pull request experiences.

**Intended Outcome**
We want high-quality, automated security review to be a native and positive part of the developer workflow. Integrating static analysis results directly into the PR experience will help engineering teams catch security vulnerabilities earlier.

**How will it work?**
Advanced Security users will be able to set up an Actions workflow that runs CodeQL analysis on each pull request, or on a schedule, and posts the results to GitHub using a standard static analysis result format (SARIF). GitHub will determine which alerts are new as a result of the code changed in the pull request and surface any potential vulnerabilities in-line.

**Comment by alexcnichols** [comment]
https://github.blog/changelog/2020-09-30-code-scanning-is-generally-available/
