### ISSUE TITLE
Code scanning default setup automatically includes all CodeQL supported languages

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#812]
### Summary

Code scanning default setup will automatically attempt to analyze all CodeQL supported languages in a repository. Repositories no longer need to manually choose to include compiled languages in the default setup configuration. If a language fails it will be automatically deselected from the configuration, and the  analysis and any alerts from the successful languages will be available. 

This will ship at the repository and organization level.

### Intended Outcome

Code scanning default setup automatically sets up the best possible configuration for your repository to get started easily with CodeQL. 

### How will it work?

All CodeQL supported languages will be selected automatically by code scanning default setup, and automatically removed from the configuration if they fail. The "edit configuration" page allows users to see which languages are included in the configuration and apply any customization if required.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-10-23-code-scanning-default-setup-automatically-includes-all-codeql-supported-languages/

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
🚢 This has shipped with GHES 3.12: https://docs.github.com/en/enterprise-server@3.12/admin/release-notes
