### ISSUE TITLE
CodeQL support for Lombok (Java) framework (public beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#815]
### Summary

[Lombok](https://projectlombok.org/) is a commonly used Java framework that is currently not supported by CodeQL. CodeQL will support extracting and scanning projects that use the Lombok framework.  

### Intended Outcome

Users that have applications built with Lombok, will be able to extract and scan them.  During the extraction of Lombok code, CodeQL will also extract Java code located in the same files as the Lombok code. The extractions of additional code can lead to the discovery of new alerts. 

### How will it work?

If a Java application is built with Lombok and the CodeQL configuration flag is enabled, CodeQL will automatically scan the application's Java and Lombok framework code.

**Comment by ankneis** [comment]
🚢 This shipped: https://github.blog/changelog/2023-09-01-code-scanning-with-codeql-improves-support-for-java-codebases-that-use-project-lombok/

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This shipped with GHES 3.11: https://docs.github.com/en/enterprise-server@3.11/admin/release-notes
