### ISSUE TITLE
Projects: Activity History

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#816]
### Summary

Users will be able to view an activity history of their project so that they can view changes to their project items over time. Users will be able to see who performed the action, what the action was, and the timestamp details of when it was performed.  

### Intended Outcome

By providing users with the ability to view an activity history of their project items, we can help them accomplish tasks such as
- Knowing what has changed in their project items
- Determining whether a project is still active, or if it is stale and out of date
- Referencing a history of how items have changed in a project, so that if an action was unintended or a mistake they can revert it on their own part

### How will it work?

Users will be able to access the activity history for a project from the project level `...` menu. This will open a tab that has the events for item changes within a project.

**Comment by ankneis** [comment]
This issue is being closed as outdated. For more information, please check out this [Discussion post](https://github.com/github/roadmap/discussions/1014). Stay tuned for new additions to our refreshed public roadmap!

**Comment by ankneis** [comment]
We wanted to provide more details on why this issue was removed from the public roadmap. We intend to provide activity history for Projects, but we're removing it from this roadmap for now until we have more certainty on our timeline. Please keep an eye out for a new roadmap issue coming soon with more details!
