### ISSUE TITLE
Ping Federate Connector for EMU enterprises

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#818]
### Summary

We released our [support for Ping Identity's GitHub EMU Connector for Ping Federate in June of this year](https://github.blog/changelog/2023-06-13-enterprise-managed-users-connector-support-for-ping-federate-is-now-in-public-beta). We are on track for general availability on 2023-09-06.

---

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-09-19-enterprise-managed-users-support-for-ping-federate-is-now-generally-available/.
