### ISSUE TITLE
GitHub Actions Importer: Bamboo & BitBucket Support

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#820]
### Summary

GitHub Actions Importer helps users plan, forecast, and automate the migration of their existing CI/CD pipelines to GitHub Actions. With this update, we will be adding support for Atlassian's CI/CD products: Bamboo Server, Bamboo Data Center, and BitBucket. Users can migrate their Bamboo and BitBucket pipelines to GitHub Actions easily and for free using the official GitHub CLI or our issue ops flow.

### Intended Outcome

- Simplify the pipeline migration process for Bamboo Server, Bamboo Data Center & BitBucket Pipeline users by automating manual and tedious steps
- Reduce the potential for errors during migration and speed up development teams

### How will it work?

Users will be able to migrate existing Bamboo & BitBucket pipelines to GitHub Actions using the `audit`, `forecast`, `dry-run`, and `migrate` subcommands of gh actions-importer

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-09-18-migrate-bamboo-and-bitbucket-pipeline-to-github-actions

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
🚢 This has shipped with GHES 3.12: https://docs.github.com/en/enterprise-server@3.12/admin/release-notes
