### ISSUE TITLE
Audit Log: Copilot for Business events

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#822]
### Summary

Copilot for Business users will now be able to review updates and changes to their Copilot settings through the [audit log](https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/reviewing-the-audit-log-for-your-organization#accessing-the-audit-log).

### Intended Outcome

With any large organization or enterprise, it's important to be able to trace settings updates and purchases. We want to empower our organization and enterprise admins to be able to investigate any changes to their Copilot for Business account and settings without having to reach out to support.

### How will it work?

We'll integrate with the existing audit log feature by emitting relevant events from the Copilot for Business service. These events will include but are not limited to:
- Adding Copilot access for a user/team
- Removing Copilot access for a user/team
- Updating the duplicate detection policy
- Updating the seat assignment policy (No members, all org members, select members)
- Updating the chat access policy

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-09-07-github-copilot-september-7th-update/

Leaving open to track for GHES release.
