### ISSUE TITLE
Code referencing for code completion in Visual Studio Code

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#823]
### Summary

When a user accepts a code snippet that has a match to public code, we will now notify them via a pop-up message and an alert in their Visual Studio Code status bar. Upon clicking the notification, they'll be able to review the sets of repos where matching code exists as well as an aggregate count of the associated licenses.

### Intended Outcome

Last year, we introduced a GitHub Copilot feature that allows developers to silently block suggestions greater than 150 characters that match public code. But the world’s developers have a diverse perspective of wants and needs when they’re building. While simply blocking public code can be useful, a number of developers told us they actually want to see code matches. Some want to learn from other’s code;  some may want to take a package dependency rather than introduce new business logic; still others want to give or receive credit for similar work. With this feature, we hope to enable them to review extra information about the match and make the decision best fit for them. 

### How will it work?

If GitHub Copilot makes a suggestion matching public code, it’ll share a list of the repositories where that code can be found, and their licenses – all right in the editor. If there’s a match, a pop-up window appears that shows you all of the code matches, what their repository licenses are, and how many repositories—including repositories without licenses—that code appears in, as well as links to those repositories.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/2023-08-03-introducing-code-referencing-for-github-copilot/
