### ISSUE TITLE
Actions: Custom VM Images for GitHub-hosted runners (Preview)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#826]
### Summary

Actions Hosted runners will now include the option to build your own virtual machine image to power your workflows that are run on GitHub Actions. This allows developers to gain control over their supply chain and reduce the average duration of their workflows by customizing the software, tools, and files on Actions Hosted runners before a workflow starts.

### Intended Outcome

33% of Actions people run are to set up tools/dependencies on their machine before they even start to download images/packages that their application is dependent on. This takes time on every run of that workflow. With custom images developers can now customize those pre-installed tools, saving time by creating a "pre-warmed" machine. 

### How will it work?

GitHub's image customization allows developers to use their existing workflow YAML to produce images which can be used as the base for their different developer environments. Developers can use the new syntax to take the state of their current environment and save that to an image to be used in future workflows.

**Comment by ankneis** [comment]
🚢 This has shipped to private preview.
