### ISSUE TITLE
Organization Archiving - GA

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#827]
### Summary

This is the initial GA release of Organization Archiving, building on the public beta phase 🎉 

This feature enables organization administrators to archive an entire organization at once.

Enterprises with deep usage of GitHub often end up with a confusing and hard-to-manage proliferation of organizations that can number in the dozens or even hundreds. Many of these are stale or obsolete, but previously there was no easy way to archive a once-active organization: you had to individually archive each repository in the org, and even then the top-level org still permitted repo creation, new teams, etc. This added to the toil of enterprise administration and made for an inconsistent, unpleasant experience for open source maintainers, OSPO managers, and IT teams responsible for managing their GitHub presence.

Our new feature lightens this burden by adding a button to the Organization Settings "Danger Zone" which will:

* archive all the repositories in the organization
* restrict many "write" activities in that organization, such as creating new repos
* set a key in the API to indicate the org has been archived

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-09-06-organization-archiving-general-availability/

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This shipped with GHES 3.11: https://docs.github.com/en/enterprise-server@3.11/admin/release-notes#3.11.0
