### ISSUE TITLE
Actions: Create and share workflows templates in an organization

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#83]
**Summary** 
Today, when developers use the GitHub interface to create a new workflow they see a number of "starter workflows" to choose from:

![Screen Shot 2020-04-24 at 10 03 43 AM](https://user-images.githubusercontent.com/1865328/80227171-e8b60e00-8612-11ea-9083-74bd9aa08a51.png)

These workflows are available to all repositories and are defined in the [actions/starter-workflows](https://github.com/actions/starter-workflows) repository.

**Intended Outcome** 
With this feature, users will be able to define their own starter workflows. These will be defined at the organization level, and will be made available to every repository within the organization. 

**How will it work?** 
When developers create a new workflow, they will see these custom workflows and can choose whether to use them or not.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2020-06-23-github-actions-workflow-templates/
