### ISSUE TITLE
Issues: Issue Types

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#837]
### Summary

It's no easy feat to search and triage issues across repositories when you have many teams working towards a shared goal. Issue types will allow users to classify and manage different types of issues across repositories. 

![issue type organization settings page](https://github.com/github/release-assets/assets/94867353/b8d5b900-0f10-421f-9a0a-1cc11bf98394)

### Intended Outcome

Some folks have tried to use labels in order to do this - however labels are tied to repositories and label syntax can drift across repos. This makes triaging issues across repos difficult.

We believe that by creating a shared language to standardize work items across repositories we'll unlock reporting and automation use-cases.

### How will it work?

Users will be able to define issue types (ex. bug, feature request, spike) at the org level and apply this syntax to an issue in a repo.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2024-10-01-evolving-github-issues-public-preview/
