### ISSUE TITLE
Actions: Share secrets across multiple repos

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#84]
**Summary** 
Today, secrets are defined at the repository level. When a team has multiple repositories that all need the same secret, they have to repeat the definition of that secret across all of them. This introduces friction and the possibility of errors. With this feature, users will be able to define secrets for multiple repositories at once. 

**Intended Outcome** 
This frees up users to work on more interesting things and reduces the chance of errors. It also enables them to quickly update a secret across multiple repositories, such as in response to a leak.

**How will it work?** 
Users will be able to define a secret at the organization level. They'll be able to specify that all repositories within the organization can access the secret, or a subset of them.

**Comment by Sid-ah** [comment]
https://github.blog/2020-05-22-keep-your-secrets-synced-across-multiple-repositories-with-organization-secrets/
