### ISSUE TITLE
Code scanning: Improve experience for code scanning PR merge protection functionality for Rulesets

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#847]
### Summary

Code scanning allows configuring code scanning merge protection rule for PRs as part of repository [Rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets). The configuration is available at the repository and organisation levels and via the Rulesets API. As part of the code scanning rule, users can set the alert's severity that causes the merge block.
Users can set up code scanning rules for each code scanning tool, including CodeQL and any 3rd party tools.

### Intended Outcome

Users can choose a code scanning tool and configure the code scanning alert level to block the pull request merge.

### How will it work?

Code scanning has its own rule for configuring the merge protection functionality on pull requests. The rule does not require a code scanning status check to pass. The pull request merge will be blocked when the code scanning rule is configured for the branch and repository while the pull request waits for code scanning analysis or when code scanning analysis reports the alert with a defined severity level on the pull request.

**Comment by ankneis** [comment]
🚢 This has shipped: The feature is released on .com: https://github.blog/changelog/2024-04-30-code-scanning-now-allows-configuring-rulesets-to-prevent-pull-requests-from-being-merged-beta

Leaving open to track for GHES release!

**Comment by ankneis** [comment]
This shipped with GHES 3.14: https://docs.github.com/en/enterprise-server@3.14/admin/release-notes
