### ISSUE TITLE
Harden backup-utils for Cluster

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#851]
### Summary

The preflight checks from backup-utils v.312.0 onwards will better support customers using our cluster topology. These checks will improve the performance of backup-utils by performing the following checks:

1. Verify that all remote file systems are **not** read-only, and highlight the nodes that are not writable.
2. Log an error message from `ghe-cluster-host-check` for each cluster node that is offline, so that customers know which nodes to fix before starting to generate a backup.
3. On High Availability setups, backup-utils will now write the temporary `.sync_in_progress` lock file (which should pause network maintenance globally) to both the primary and replica nodes during backups.

**Comment by ankneis** [comment]
🚢 This has shipped with GHES 3.12: https://docs.github.com/en/enterprise-server@3.12/admin/release-notes
