### ISSUE TITLE
Code scanning default setup supports self-hosted runners on GHEC

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#852]
### Summary

Code scanning default setup will be available for self-hosted runners on GHEC.

### Intended Outcome

Customers with self-hosted runners on GHEC can use code scanning default setup on their repositories. 

### How will it work?

Code scanning default setup will use self-hosted runners on GHEC if a repository has access to self-hosted runners with the label `code-scanning`. Default setup will only use one runner type per repository, either hosted or self-hosted.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-12-19-code-scanning-default-setup-is-now-available-for-self-hosted-runners-on-github-com/
