### ISSUE TITLE
Code scanning default setup can be enabled on repositories before code in supported languages are added to the repositories

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#854]
### Summary
Code scanning default setup can now be enabled on repositories which don't contain any CodeQL supported languages and will automatically update to include any supported languages when they are added to the repository.

### Intended Outcome
You can enable default setup on any repository and have confidence that it will automatically give the best possible protection when the repository changes to include CodeQL supported languages.

### How will it work?
When default setup is enabled on a repository without any CodeQL supported languages, the repository will watch for CodeQL supported languages that added to the repository and automatically update to analyse them.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2024-02-05-code-scanning-can-now-be-enabled-on-repositories-before-they-contain-codeql-supported-languages/

**Comment by ankneis** [comment]
This shipped with GHES 3.13: https://docs.github.com/en/enterprise-server@3.13/admin/release-notes#3.13.0

Closing as complete.
