### ISSUE TITLE
Actions: Workflow visualization

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#88]
#### Summary
This feature will allow users provides a real-time, visual graph of their workflow as it runs so users can see how it’s progressing.

#### Intended outcome
This makes it easier for users to assess progress of their workflows as they run, and to more easily identify problems for troubleshooting. This will save time and make it easier to communicate status to others, especially for complicated or lengthy workflows.

#### How will it work
For each workflow, a visual graph will be generated, with color coding to identify success, in progress, or failure of a particular step. Each step will include metadata and deep-linking to help speed investigations of any underlying workflow or source code files that may be needed.

**Comment by alexcnichols** [comment]
https://github.blog/changelog/2020-12-08-github-actions-workflow-visualization/
