### ISSUE TITLE
GitHub Actions for GHES

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#89]
**Summary**
With this GA release, GitHub Enterprise Server (GHES) will include Actions.

**Intended Outcome**
GitHub Enterprise Server customers can use Actions.

**How will it work?**
Actions on GHES is designed for organizations who want to manage Actions entirely on their own infrastructure (on-premise or cloud). You’ll need to provide the following:

* Compute capacity for the Actions services
* Self-hosted runners
* S3-compatible storage capacity, which will be used for logs, caching, and artifacts

GitHub Actions on GHES includes tools to help you operate the service successfully:

* Key metrics to on the Management Console  
* Audit logs
* Access control functionality to rollout Actions in a controlled way

Actions on GHES will be released in two phases:

* Beta
* General availability

**Comment by Sid-ah** [comment]
https://docs.github.com/en/enterprise-server@3.0/admin/release-notes#github-actions
