### ISSUE TITLE
Packages: Support for GHES (Beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#90]
**Summary**
[GitHub Packages] will be available to [GHES] (GitHub Enterprise Server) for on-premise deployments.

**Intended Outcome**
GitHub Enterprise Server customers can use GitHub Packages.

**How will it work?**
This initial release is a beta available to customers for feedback purposes. Features include:

- All existing Packages services:
  - Docker (note: we plan to replace the Docker service with a beta of the GitHub Container Registry in the next GHES release)
  - npm
  - maven/Gradle
  - RubyGems
  - NuGet
- Configurable storage backend (requires AWS S3 or MinIO)
- Private package deletion via APIs and UI

[GitHub Packages]: https://github.com/features/packages
[GHES]: https://github.com/enterprise "GitHub Enterprise Server"
[Plans]: https://github.com/pricing "GitHub Pricing Plans"

[Container]: https://en.wikipedia.org/wiki/Container_(abstract_data_type)
[OCI]: https://www.opencontainers.org/ "Open Containers Initiative"
[ORAS]: https://github.com/deislabs/oras
[CNAB]: https://cnab.io/ "Cloud Native Application Bundle"
[CNCF]: https://www.cncf.io/ "Cloud Native Foundation"
[Kubernetes]: https://kubernetes.io/
[Docker]: https://www.docker.com/
[npm]: https://www.npmjs.com/
[maven]: https://maven.apache.org/ "Apache Maven"
[NuGet]: https://www.nuget.org/
[Swift]: https://swift.org/
[Helm Charts]: https://helm.sh/
[Helm Hub]: https://hub.helm.sh/
[Rust]: https://www.rust-lang.org/
[RubyGems]: https://rubygems.org/
[Go]: https://golang.org/
[PHP]: https://www.php.net/
[Debian]: https://www.debian.org/
[Python]: https://www.python.org/
[PyPI]: https://pypi.org/

**Comment by alexcnichols** [comment]
https://enterprise.github.com/releases/2.22.0/notes
