### ISSUE TITLE
Dependabot Version Updates (Cloud)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#91]
**Summary**
[Dependabot Version Updates](https://help.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates#enabling-github-dependabot-version-updates) keep projects secure by opening pull requests that update dependencies to the latest version.

**Intended Outcome**
Keep project dependencies up to date. This helps keep a project secure as patches may only be available on the latest version(s) of a dependency, or security patches may be released without being (initially) announced. This also ensures that projects can be regularly updated, so that a critical patch will require a 'smaller' upgrade.

**How will it work?**
Today, [Dependabot Security Updates](https://help.github.com/en/github/managing-security-vulnerabilities/configuring-automated-security-updates#about-automated-security-updates) can help you avoid vulnerabilities in packages you rely on by automatically updating you to a non-vulnerable version - this functionality similarly regularly updates the packages you rely on to newer versions, even if the version on which you currently rely doesn't have any (known) vulnerabilities.
This includes GA for Dependabot support for private registries.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-03-31-dependabot-version-updates-are-now-generally-available/
