### ISSUE TITLE
Dependabot on Actions Opt-In Migration

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#913]
### Summary

Dependabot is migrating to Actions. With this change, there will be no interruption or change to the functionality of Dependabot, but you will be able to see Dependabot's jobs in the Actions tab and leverage Actions-related tools to manage Dependabot, including running Dependabot on self-hosted runners.

Note about GHES: this feature is already available on GHES, so this particular ship will not be going to any version of GHES.

With this release, repository and organization administrators will be able to opt-in to migrate Dependabot to run in Actions for their repository or organization. 

- Self-hosted runners will **not** be supported until that feature launches separately (status: launched, support now available)
- Larger runners will be supported
- Dependabot use will **not** count as billable Actions minutes (i.e. Dependabot remains free)
- There will be no interruption to the functioning of Dependabot - it will still run as expected (both security & version updates)
- This feature will be available for every deployment except GHES, as GHES already runs Dependabot in Actions.

### Intended Outcome

This will consolidate Dependabot further onto GitHub infrastructure, and enable customers to have greater control over Dependabot runs.

### How will it work?

With this release, you will be able to opt-in to migrating Dependabot to run on Actions. There will be no interruption to Dependabot's runs. Following the migration, you will be able to:

- Leverage the Actions API to track Dependabot job failures
- See Dependabot job logs in the Actions tab

**Comment by ankneis** [comment]
This has shipped: https://github.blog/2024-05-02-dependabot-on-github-actions-and-self-hosted-runners-is-now-generally-available/
