### ISSUE TITLE
Dependabot Grouped Security Updates GA

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#914]
### Summary

With this feature, you will be able to configure how Dependabot groups multiple dependency updates related to Dependabot alerts into single pull requests.

### Intended Outcome

This will reduce the number of Dependabot security PRs that get opened.

### How will it work?

You will be able to either click a button in the repository settings page to tell Dependabot to group all security updates, or use dependabot.yml checked into the repository to configure which updates to include. You will be able to configure grouping rules based on:

- Package name and patterns (e.g. `eslint` or `*`)
- Dependency type (`production` or `development`)
- Semver update (e.g. `semver-patch`, `semver-major`)
~~- Directories~~

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2024-03-28-dependabot-grouped-security-updates-generally-available

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This shipped with GHES 3.14: https://docs.github.com/en/enterprise-server@3.14/admin/release-notes!
