### ISSUE TITLE
Security Advisories: CWE and CVSS

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#92]
**Summary**
Today, [GitHub Security Advisories](https://help.github.com/en/github/managing-security-vulnerabilities/about-github-security-advisories) enable maintainers to privately discuss, fix, and disclose information about vulnerabilities in their projects. This information is used to automatically trigger security updates for participating GitHub repositories. The updated security advisory form will make it easier to provide details required for a CVE.

**Intended Outcome**

- Maintainers can communicate severity using the CVSS calculator or by providing a CVSS formula from their own calculator
- Maintainers can specify the Common Weakness Enumeration (CWE) that categorizes their vulnerability

**How will it work?**
During the creation of a Security Advisory, the maintainer will be able to add the CWE and CVSS score.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2021-02-09-cwe-and-cvss-in-security-advisories/
