### ISSUE TITLE
CodeQL can scan Java applications without requiring a supported build configuration or build command (public beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#920]
### Summary

Enable CodeQL to scan Java applications, without requiring a build command or a configuration that can be automatically recognized to reproduce the build. The improvements to Java scanning will increase the number of applications that can be scanned with minimal configuration.

### Intended Outcome

Java applications that are scanned with CodeQL need to be able to specify a build command or be compiled with the CodeQL autobuilders. This new approach will allow users to scan significantly more Java repos without requiring additional configuration. This will improve the overall adoption of CodeQL for Java.

### How will it work?

In the current state, CodeQL requires a working build that can be automatically replicated by CodeQL's autobuilders or a manual build command supplied in the configuration. After this change, users will be able to point CodeQL to Java applications which previously did not have a working autobuilder or a manual build command in the configuration. CodeQL will automatically extract as much of the Java code as possible and run a security analysis.

**Comment by ankneis** [comment]
🚢 This has shipped:  https://github.blog/changelog/2024-03-21-java-projects-no-longer-require-a-build-when-using-code-scanning-via-default-setup/ &&  https://github.blog/changelog/2024-03-26-codeql-can-scan-java-projects-without-a-build/
