### ISSUE TITLE
Expanding access to historical log data via audit log exports (Preview)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#921]
### Summary

Customers are currently able to access and export 7 days worth git events and 6 months of all other audit log events via the audit log API and audit log exports. To retain access to events beyond these retention periods, Enterprise customers are able to stream their audit logs to a supported streaming endpoint. If a customer is not an Enterprise or has not set up streaming, the customer must contact support to secure access to git data greater than 7 days old, or other audit log activity greater than 6 months. 

By expanding access to historical log data via audit log exports, we will enable customers to access 6 months of git events and 1 year of all other audit log events using audit log exports. In doing so, customers will be empowered to independently access and export data equivalent to that historically provided by GitHub's support team. In addition, customer's adopting streaming will have the ability to backfill a broader set of historical logs into one of GitHub's supported streaming endpoints.

**Comment by ankneis** [comment]
Please continue to refer to our updated Public Roadmap for the latest ships, including updates on the continuation of these projects.

**Comment by ankneis** [comment]
We wanted to provide more details on why we removed this from the roadmap. We understand this is important and this work remains a priority for our product team. We're removing it from our roadmap for now until we have more certainty on our timeline for delivering this feature.
