### ISSUE TITLE
Hierarchy: Sub-issues

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#927]
### Summary

Create and manage sub-issues from issues to create a parent/child hierarchy which can be traced up and down. From high level objective through to task. 

### Intended Outcome

We are building this as a replacement for the Tasklists beta. We have heard your feedback on this experience and are going to relaunch with a new look and feel to make it faster and easier to create, manage and work with parent / child relationships in Issues and Projects. 

### How will it work?

**Create new issues directly from the parent**
![Image](https://github.com/github/release-assets/assets/94867353/b28865ad-b8c3-4029-a4d9-795902b6d970)
![Image](https://github.com/github/release-assets/assets/94867353/d0406c1b-abc8-4034-8d59-b0fd0bbe0397)

**Navigate relationships in a list**

![Image](https://github.com/github/release-assets/assets/94867353/03ccadef-a56c-4099-8c6c-e87e8d64e71a)

**Or if there are multiple levels, in a tree**

![Image](https://github.com/github/release-assets/assets/94867353/09a20dff-5b77-4b69-babb-e36d6082e7ed)

**Add and view relationships on the sidebar**

Starting with parent / child with additional relationships to follow.  

![Image](https://github.com/github/release-assets/assets/94867353/34f8060e-dae4-4682-ba52-fc84519513a7)

**Explore your hierarchies directly in projects**

![Image](https://github.com/github/release-assets/assets/94867353/0e637535-9fd5-4857-ae55-96e0b5a7d938)

**Comment by ankneis** [comment]
Please continue to refer to our updated Public Roadmap for the latest ships, including updates on the continuation of these projects.

**Comment by ankneis** [comment]
For updates, please refer to this updated roadmap issue: https://github.com/github/roadmap/issues/1036
