### ISSUE TITLE
Issues: Nested filtering with `AND` `OR` operators

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#928]
### Summary

We are providing users with the ability to build and perform advanced queries to understand their issues. This includes supporting both the `AND` and `OR` operators, and providing support to build nested queries.

![Image](https://github.com/github/release-assets/assets/94867353/7dc4feaa-ef4a-401f-b514-0d5e5bf8d102)

### Intended Outcome

This will improve our current issue filtering support and allow users to build and share complex queries when searching across their issues. It will unlock the ability to understand questions such as "What are all of the open issues that are either assigned to me, _or_ have a particular set of labels?"

### How will it work?

Users will be able to filter their issues and build advanced queries from the filter bar using `AND` and `OR` operators, as well as parentheses for nested query support.

**Comment by ankneis** [comment]
🚢 This has shipped: We have shipped! https://github.blog/changelog/2024-10-01-evolving-github-issues-public-preview/

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This feature will be going out with a GHES version in its GA release. Please continue to follow along here: https://github.com/github/roadmap/issues/1036
