### ISSUE TITLE
Dependabot on Self Hosted Actions Runners for GitHub Enterprise Cloud

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#929]
### Summary

With this feature, developers will be able to configure Dependabot to run on self-hosted Actions runners, which can unlock access to privately-hosted registries and allow Dependabot to pull updates from them.

### Intended Outcome

Customers who use private registries to host their packages on internal networks cannot use Dependabot today to update the versions of those packages in their code. With this change, they can choose to run Dependabot on their private networks, which will allow Dependabot to access the registries and update the packages.

### How will it work?

By creating and configuring a self-hosted Actions runner for Dependabot, you can enable Dependabot to use this runner during its update jobs. By further configuring private registry credentials in each of your repositories, you can configure Dependabot to access your privately hosted registries for updates.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2024-05-02-dependabot-pull-requests-jobs-are-now-available-to-run-on-self-hosted-actions-runners
