### ISSUE TITLE
Packages: PHP support

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#93]
**Summary** 

This is the GA (generally available) release of support for [PHP] dependency management through [Composer].

**Intended Outcome** 

GitHub [Packages] customers will have the ability to publish public and private [PHP] packages within their organization. [Composer] packages published can be shared internally and will benefit from the fine grained access controls connected to GitHub teams available to all other package registry services.

- Language: PHP
- Framework: Composer
- CLI: composer

**How will it work?** 

```json
"repositories": [
    {"type": "composer", "url": "https://php.pkg.github.com/$ORG/"}
],
  "require": {
    "$ORG/package": ">= 1.2.3"
  }
```

```shell
composer install
```

[Packages: Container service (GA)]: https://github.com/github/roadmap-internal/issues/144
[Packages: Container service (Beta)]: https://github.com/github/roadmap-internal/issues/101
[Packages: Helm Charts]: https://github.com/github/roadmap-internal/issues/119
[Packages: Universal/Generic Storage]:https://github.com/github/roadmap-internal/issues/112

[Packages]: https://github.com/features/packages
[GHES]: https://github.com/enterprise
[Plans]: https://github.com/pricing

[Container]: https://en.wikipedia.org/wiki/Container_(abstract_data_type)
[OCI]: https://www.opencontainers.org/ "Open Containers Initiative"
[ORAS]: https://github.com/deislabs/oras
[CNAB]: https://cnab.io/
[CNCF]: https://www.cncf.io/
[Kubernetes]: https://kubernetes.io/
[Docker]: https://www.docker.com/
[npm]: https://www.npmjs.com/
[Swift]: https://swift.org/
[Helm Charts]: https://helm.sh/
[Helm Hub]: https://hub.helm.sh/
[Rust]: https://www.rust-lang.org/
[Go]: https://golang.org/
[Go modules]:https://blog.golang.org/using-go-modules
[PHP]: https://www.php.net/
[Composer]: https://getcomposer.org/
[Debian]: https://www.debian.org/
[Python]: https://www.python.org/
[PyPI]: https://pypi.org/

**Comment by ankneis** [comment]
This is no longer planned due to a change in our strategic priorities and the allocation of our resources towards higher-priority initiatives.
