### ISSUE TITLE
GitHub Actions: Artifacts v4 available in GitHub Enterprise Server

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#930]
### Summary

We will be extending support for `v4` of the actions to upload and download artifacts to GitHub Enterprise Server (GHES). This new version improves artifact upload and download speeds by up to 98%. There are also [key differences](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) from previous versions that may require customers to update their workflows. We have published a [migration guide](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md) to help customers make the transition when they're ready.

**Comment by ankneis** [comment]
This issue is being closed as outdated. For more information, please check out this [Discussion post](https://github.com/github/roadmap/discussions/1014). Stay tuned for new additions to our refreshed public roadmap!

**Comment by ankneis** [comment]
We wanted to provide more details on why this issue was removed from the public roadmap. We do intend to bring Artifacts v4 to GitHub Enterprise Server, but we're removing it from this roadmap for now until we have more certainty on our timeline.
