### ISSUE TITLE
Audit log streaming health check [GA]

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#932]
### Summary

Audit log streaming configurations will be regularly tested to identify streams in an unhealthy state. If an Enterprise's stream is found to be unhealthy, Enterprise Administrators will receive an email asking them to verify their configuration. Resolving misconfigured streams within 7 days will ensure all audit log events are streamed to their designated endpoint.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2024-05-01-audit-log-streaming-health-check-is-generally-available
