### ISSUE TITLE
Audit Log Streaming Configuration API [Beta]

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#934]
### Summary

This release provides customers with the ability to create, update, and delete an audit streaming configuration through an external API. Customers will be able to programmatically update the audit log streaming configuration, including the credential used by the streaming configuration.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2024-07-15-audit-log-streaming-can-now-be-configured-via-githubs-rest-api-private-beta
