### ISSUE TITLE
Guest Collaborators general availability for enterprise managed users

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#936]
### Summary

Guest collaborators helps companies who work with contractors and other short-term partners in a flexible and managed fashion on specific projects, while also sharing code and ideas without restrictions amongst full enterprise members. 

[Learn more](https://docs.github.com/en/enterprise-cloud@latest/admin/managing-accounts-and-repositories/managing-users-in-your-enterprise/roles-in-an-enterprise#guest-collaborators) about guest collaborators.

### Intended Outcome

We will be making this feature generally available for GHEC EMU customers

### How will it work?

The guest collaborator role is defined via SCIM and assigned to users by the identity provider. Currently, guest collaborators must be added to an organization team in order to be granted access to repositories within that organization. When they are added to an organization team they become organization members and are subject to organization base permissions. Guest collaborators only have access to internal repositories within organizations where they are a member and private repositories they are authorized to access. Guest collaborators will never see internal repositories in an organization they are not a member of.

**Comment by ankneis** [comment]
🚢 This has shipped:https://github.blog/changelog/2024-05-02-ga-guest-collaborators-for-enterprise-managed-users
