### ISSUE TITLE
Repository collaborator access for Enterprise Managed Users (EMUs)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#937]
### Summary

GitHub Enterprise Cloud customers with enterprise managed users (EMUs) are currently only able to manage access to organization-owned repositories by adding users as members of that organization. This works well in relatively open working spaces exclusively containing full time employees and use of multiple organizations to categorize work. We are working to provide more flexibility in repository access management for EMUs so that the experience is similar to the rest of GitHub.

### Intended Outcome

Managing access to individual organization repositories will be possible for GHEC EMU customers.

### How will it work?

We are adding the ability to add individual EMU users to organization-owned repositories with a specific access level. This action will not grant that user organization membership. If the user is not already consuming an enterprise license, they will while they have access to at least 1 repository.

Any provisioned user in the enterprise, including guest collaborators, will be eligible to be added to any organization repository. In our current private beta implementation, repository administrators and organization owners may add users to repositories they manage. We will add enterprise policy support that can disable this feature, or restrict its use only to organization owners.

**Comment by ankneis** [comment]
🚢 This is shipped: https://github.blog/changelog/2024-05-02-public-beta-repository-collaborators-for-enterprise-managed-users/
