### ISSUE TITLE
Push Rulesets

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#939]
Repository Rules will now allow you to block commits on select file and path attributes. 

- Restrict file paths: Prevent commits that include changes in specified file paths from being pushed to the commit graph.
- Restrict file path length: Prevent commits that include file paths that exceed a specified character limit from being pushed to the commit graph
- Restrict file extensions: Prevent commits that include files with specified file extensions from being pushed to the commit graph.
- Restrict file size: Prevent commits that exceed a specified file size limit from being pushed to the commit.

![Image](https://github.com/github/release-assets/assets/94867353/f3bc4669-106e-42af-8398-88a114a5e11a)

Repository and Organizations admins can control who can contribute to certain locations in a repository ensuring certain paths stay locked down. It also ensure the correct types of file are committed to a repo making it sure you don't accidentally add a binary file or SSH key to a repository.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2024-04-18-push-rules-public-beta!
