### ISSUE TITLE
Packages: Python (PyPi) support

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#94]
**Summary** 

This is the GA (generally available) release of support for [Python] packages [PyPi] supporting the pip client.

**Intended Outcome** 

GitHub [Packages] users will have access to a public and private [PyPI] package management server for distributing [Python] packages both publicly and privately within their organization. 

- Language: Python
- Framework: PyPI
- CLI: pip

**How will it work?** 

Set GitHub Packages as a repository

```ini
[packages]
repository: https://pypi.pkg.github.com/$USER_OR_ORG/
username: $GITHUB_PERSONAL_ACCESS_TOKEN
password:
```

Use the Packages repository for pushing 

```shell
python setup.py sdist upload -r packages

```

[Packages: Container service (GA)]: https://github.com/github/roadmap-internal/issues/144
[Packages: Container service (Beta)]: https://github.com/github/roadmap-internal/issues/101
[Packages: Helm Charts]: https://github.com/github/roadmap-internal/issues/119
[Packages: Universal/Generic Storage]:https://github.com/github/roadmap-internal/issues/112

[Packages]: https://github.com/features/packages
[GHES]: https://github.com/enterprise
[Plans]: https://github.com/pricing

[Container]: https://en.wikipedia.org/wiki/Container_(abstract_data_type)
[OCI]: https://www.opencontainers.org/ "Open Containers Initiative"
[ORAS]: https://github.com/deislabs/oras
[CNAB]: https://cnab.io/
[CNCF]: https://www.cncf.io/
[Kubernetes]: https://kubernetes.io/
[Docker]: https://www.docker.com/
[npm]: https://www.npmjs.com/
[Swift]: https://swift.org/
[Helm Charts]: https://helm.sh/
[Helm Hub]: https://hub.helm.sh/
[Rust]: https://www.rust-lang.org/
[Go]: https://golang.org/
[Go modules]:https://blog.golang.org/using-go-modules
[PHP]: https://www.php.net/
[Debian]: https://www.debian.org/
[Python]: https://www.python.org/
[PyPI]: https://pypi.org/

**Comment by ankneis** [comment]
This is no longer planned due to a change in our strategic priorities and the allocation of our resources towards higher-priority initiatives.
