### ISSUE TITLE
🚢 This has shipped: https://github.blog/changelog/2024-01-18-github-issues-projects-project-status-updates-issues-side-panel/

### ISSUE THREAD

**Issue by timmeinerzhagen** [github/roadmap#942]
🚢 This has shipped: https://github.blog/changelog/2024-01-18-github-issues-projects-project-status-updates-issues-side-panel/

Leaving open to track for GHES release!

_Originally posted by @ankneis in https://github.com/github/roadmap/issues/830#issuecomment-1904750480_

**Comment by adriens** [comment]
:raised_hands: :clap:
