### ISSUE TITLE
2vCPU Actions hosted runners with fixed IP ranges & VNET support

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#944]
### Summary

Provide customers with the ability to setup and manage their own pools of 2vCPU runners that can have our advanced features available as part of runner groups used with them. 

### Intended Outcome

Customers will be able to use 2vCPU machines with our advanced features. 

### How will it work?

Customers will need to setup new pools of 2vCPU machines as part of the Actions runner management process, from here they will be able to assigned advanced features like fixed IP ranges.
Note: 2vCPU runners set up this way are not free in public repos and do not consume included Actions minutes on GitHub plans

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2024-04-02-whats-new-for-github-actions-hosted-runners/
