### ISSUE TITLE
Private Cargo Registry Support for Dependabot Updates

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#945]
### Summary

With this change, Dependabot will be able to access Cargo private registries in order to provide updates to Rust dependencies that are stored in these private registries.

### Intended Outcome

Customers who use private Cargo registries for their Rust dependencies cannot use Dependabot to keep those up-to-date today. With this change, they will be able to.

### How will it work?

By setting up your Cargo private registry information in `dependabot.yml`, Dependabot will automatically reach out to and authenticate with the private registry when doing updates for your Rust dependencies.

**Comment by ankneis** [comment]
🚢 This one shipped! https://github.blog/changelog/2024-06-03-dependabot-now-supports-private-cargo-registries/
