### ISSUE TITLE
Dependabot on Actions Forced Migration

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#946]
### Summary

With this deprecation, Dependabot will no longer run on legacy infrastructure, and instead all Dependabot jobs will run in GitHub Actions. Customers will be migrated automatically with no need for manual intervention on their part, and Dependabot jobs will not be interrupted.

### Intended Outcome

This will allow customers greater insight into Dependabot jobs and logs, and allow them to leverage the GitHub Actions APIs to observe Dependabot jobs or use the result of those jobs to kick off other parts of their CI/CD. They will also be able to set up Dependabot to run on self-hosted runners in order to allow Dependabot to access private registries that are not available to the public internet.

### How will it work?

Dependabot will continue to function as always, but will be running its jobs in GitHub Actions.

**Comment by ankneis** [comment]
This issue is being closed as outdated. For more information, please check out this [Discussion post](https://github.com/github/roadmap/discussions/1014). Stay tuned for new additions to our refreshed public roadmap!

**Comment by ankneis** [comment]
We wanted to provide more details on why we removed this from the roadmap. We continue to plan to migrate all Dependabot users to Actions, but we have removed this from our roadmap for now until we have more certainty on our timeline. If you’re interested in this feature, please share your feedback in the [GitHub community](https://github.com/orgs/community/discussions/) so we can track interest and consider it in the future.
