### ISSUE TITLE
GitHub Advanced Security ships organization 'security configurations'

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#948]
### Summary

GitHub Advanced Security will provide a solution to easily roll-out GitHub Advanced Security across an organization. 

Organizations will be able to create 'security configurations' which define how to enable GitHub Advanced Security on subsets of repositories in the organization. There will be a GitHub recommended security configuration to easily adopt GitHub's SME recommendation and enable security across the organization.   

### Intended Outcome

It is easy to enable GitHub Advanced Security across an organization, whether the organization has no specialist security knowledge or specific security requirements.

### How will it work?

Organizations will be able to 
* enable GitHub's recommended security configuration for an entire or part of an organization.
* create custom security configurations to enable GitHub Advanced Security to meet their needs on different subsets of repositories. 
* define which security configuration to apply to new repositories in their organization.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2024-04-02-code-security-configurations-let-organizations-easily-roll-out-github-security-products-at-scale

Leaving open to track for GHES release!

**Comment by ankneis** [comment]
This shipped with `GHES 3.15`, closing as complete: https://docs.github.com/en/enterprise-server@3.15/admin/release-notes

**Comment by ankneis** [comment]
Edit to clarify: This feature will be available with the GHES 3.15 general availability release on December 3
