### ISSUE TITLE
GitHub Enterprise Importer's new git source migration process improves reliability of large repo migration

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#953]
### Summary

GitHub Enterprise Importer (GEI) will be rolling out a new process for the migration of git source data. The new migration flow will improve the reliability of repository migrations, with a focus on improving the reliability of migrating large repositories up to 10 GB with complex git histories. 

### Intended Outcome

Improved success rate for all repository migrations, with a larger improvement to the migration success rates of large repositories up to 10 GB with complex git histories. 

### How will it work?

Customers will continue to follow our documentation for [migrations](https://docs.github.com/en/migrations). GEI new git source migration process will operate as the new default experience when migrating your git data.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2024-04-16-github-enterprise-importers-new-git-source-migrator-improves-reliability-of-large-repo-migrations/
