### ISSUE TITLE
Issues and Projects: Dependencies

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#956]
### Summary

We are providing users with the ability to track dependencies across issues. This will enable you to visualize the sequence in which issues need to be addressed. 

### Intended Outcome

We have heard your feedback that dependencies are important for advanced planning and tracking purposes. We want to enable your teams to power up your workflows. 

### How will it work?

You will be able to set, manage, and view dependencies in issues. These dependencies will then also be reflected in your project views.

**Comment by ankneis** [comment]
Please continue to refer to our updated Public Roadmap for the latest ships, including updates on the continuation of these projects.

**Comment by ankneis** [comment]
For updates, please refer to this updated roadmap issue: https://github.com/github/roadmap/issues/1036
