### ISSUE TITLE
Code scanning: AI-powered autofixes for CodeQL C# alerts in PRs

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#957]
### Summary

Code scanning will propose [AI-generated fixes](https://docs.github.com/en/code-security/code-scanning/managing-code-scanning-alerts/about-autofix-for-codeql-code-scanning) for CodeQL C# alerts in pull requests. These fixes help developers resolve alerts faster and prevent introducing new vulnerabilities into codebases.

Autofix is available to private GitHub enterprise repositories with GitHub Advanced Security enabled.

### Intended Outcome

Users can fix security vulnerabilities faster with the help of code scanning AI-generated remediation suggestions, which offer a convenient one-click fix option. Additionally, the UX allows users to jump into an editing environment in order for developers to make any adjustments to the proposed fix. Read more about autofix in our [announcement](https://github.blog/2024-03-20-found-means-fixed-introducing-code-scanning-autofix-powered-by-github-copilot-and-codeql/).

### How will it work?

Following the CodeQL analysis, code scanning utilizes Copilot to suggest a fix for any new C# alerts where possible. These AI-generated remediation suggestions are then posted on the PR's 'Conversation' and 'Files Changed' tabs. Read more about fix generation in our [transparency documentation](https://docs.github.com/en/code-security/code-scanning/managing-code-scanning-alerts/about-autofix-for-codeql-code-scanning).

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2024-04-26-codeql-2-17-1-ai-powered-autofixes-for-c-new-ruby-queries-and-more-java-models/
