### ISSUE TITLE
Actions: Policies for using external actions

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#96]
**Summary**
This feature enables enterprise, organization, and repository admins to limit external actions in their workflows to an "allow list" they control.

**Intended Outcome**
Admins can choose which external actions are available to their developers to utilize.

**How will it work?**
Admins can create an 'allow list' of external actions. Only actions on the list will be available to their developers. Any workflows that reference an external action outside of the list will fail.

**Comment by alexcnichols** [comment]
Documentation: https://docs.github.com/en/free-pro-team@latest/actions/reference/usage-limits-billing-and-administration#disabling-or-limiting-github-actions-for-your-repository-or-organization
Changelog: https://github.blog/changelog/2020-10-01-github-actions-fine-tune-access-to-external-actions/
