### ISSUE TITLE
Secret scanning detects secrets in GitHub wikis

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#964]
### Summary

Secret scanning is expanding detection coverage beyond commit content. GitHub now detects secrets found in GitHub wiki content.

As GitHub expands support, GitHub will be performing backfills to detect historically existing secrets across your GitHub wikis.

This release follows recent releases, including support of secret scanning for GitHub issues, pull requests, and discussions.

### Intended Outcome

Secrets can be exposed anywhere -- not just across code content. GitHub helps keep you safe by automatically scanning additional surfaces across GitHub, without the need for any additional setup.

### How will it work?

For repositories where secret scanning is enabled, you'll automatically begin to receive secret scanning alerts for any exposed secrets in pull requests or discussions. GitHub will also continue to scan public repositories for publicly leaked secrets, and will now notify partners in secret scanning's partnership program if secrets are detected in public pull requests or discussions.

**Comment by ankneis** [comment]
This shipped with GHES 3.15: https://docs.github.com/en/enterprise-server@3.15/admin/release-notes

**Comment by ankneis** [comment]
Edit to clarify: This feature will be available with the GHES 3.15 general availability release on December 3
