### ISSUE TITLE
Projects: Unlimited items

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#966]
### Summary

Currently, projects supports 1,200 active items and 10,000 archived items, but we've heard from many larger teams that these limits are too low for the work they need to track for long-running backlogs. We are increasing the limit to 50k active items per project, and we can increase further on a case-by-case basis. 

### Intended Outcome

For long running projects or all-encompassing backlogs for companies, the current limit for project items is too constricting. In order to better serve our large team and enterprise customers, we need to increase this limit so that their projects can grow as they do.

### How will it work?

Projects will work as they do now, just with a higher upper limit on active items.

**Comment by ankneis** [comment]
Please continue to refer to our updated Public Roadmap for the latest ships, including updates on the continuation of these projects.

**Comment by ankneis** [comment]
For updates, please refer to this updated roadmap issue: https://github.com/github/roadmap/issues/1036
