### ISSUE TITLE
Code scanning: AI-powered autofixes for CodeQL alerts in PRs

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#968]
### Summary

Code scanning will propose AI-generated fixes for CodeQL alerts in pull requests. These fixes help developers resolve alerts faster and prevent introducing new vulnerabilities into codebases.

This functionality will be available for all GHAS customers on GitHub.com.

### Intended Outcome

Users can fix security vulnerabilities faster with the help of code scanning AI-generated remediation suggestions, which offer a convenient one-click fix option. 

The UI will show statistics of generated fixes and suggestions that result in fixing alerts, as well as reasons for not displaying the autofix for the alert.  Additionally, the UX will allow users to jump into an editing environment in order for developers to make any adjustments to the proposed fix.

### How will it work?

Following the CodeQL analysis, an LLM (GPT 4) will propose a fix for any new alerts where possible. These AI-generated remediation suggestions are then posted as as a code scanning autofix on the PR's 'Conversation' and 'Files Changed' tabs.

**Comment by ankneis** [comment]
This has shipped: https://github.blog/changelog/2024-08-14-copilot-autofix-for-codeql-code-scanning-alerts-is-now-generally-available
