### ISSUE TITLE
Packages: Support for GHES

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#97]
**Summary**
[GitHub Packages] will be available to [GHES] (GitHub Enterprise Server) for on-premise deployments.

**Intended Outcome**
GitHub Enterprise Server customers can use GitHub Packages.

**How will it work?**
This is the GA (General Availability) release to customers. Features include:

- The following Packages services:
  - [npm]
  - [maven]
  - [RubyGems]
  - [NuGet]
- Configurable storage backend (requires AWS S3, MinIO, or Azure blob storage)
- Admin controls for enabling/disabling specific package types and per organization
- Private package deletion via APIs and UI

[GitHub Packages]: https://github.com/features/packages
[GHES]: https://github.com/enterprise "GitHub Enterprise Server"
[Plans]: https://github.com/pricing "GitHub Pricing Plans"

[Container]: https://en.wikipedia.org/wiki/Container_(abstract_data_type)
[OCI]: https://www.opencontainers.org/ "Open Containers Initiative"
[ORAS]: https://github.com/deislabs/oras
[CNAB]: https://cnab.io/ "Cloud Native Application Bundle"
[CNCF]: https://www.cncf.io/ "Cloud Native Foundation"
[Kubernetes]: https://kubernetes.io/
[Docker]: https://www.docker.com/
[npm]: https://www.npmjs.com/
[maven]: https://maven.apache.org/ "Apache Maven"
[NuGet]: https://www.nuget.org/
[Swift]: https://swift.org/
[Helm Charts]: https://helm.sh/
[Helm Hub]: https://hub.helm.sh/
[Rust]: https://www.rust-lang.org/
[RubyGems]: https://rubygems.org/
[Go]: https://golang.org/
[PHP]: https://www.php.net/
[Debian]: https://www.debian.org/
[Python]: https://www.python.org/
[PyPI]: https://pypi.org/

**Comment by Sid-ah** [comment]
https://docs.github.com/en/enterprise-server@3.0/admin/release-notes#github-packages
