### ISSUE TITLE
 Enterprise-level overview dashboard organized by key domain

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#973]
### Summary
Enhance your understanding of your security landscape with our newly redesigned enterprise-level overview dashboard. This intuitive interface categorizes your security insights into three distinct, streamlined domains: detection, remediation, and prevention. Experience enhanced visibility with top-line metrics from GitHub Advanced Security’s preventative features such as secret scanning’s push protection and CodeQL’s alerts in pull requests. This refined design ensures that you can quickly and easily understand your security metrics, enabling more effective decision-making at a glance.

### Intended Outcome
Security managers often struggle to effectively quantify and communicate the critical metrics from the key security activities. This redesigned dashboard makes it straightforward to navigate and understand the current status of your security operations. With immediate access to tangible metrics and insights, this feature empowers you to proactively manage prevention and remediation efforts, demonstrate their impact, and ultimately reduce your enterprise's risk exposure significantly.

### How will it work?
The updated security overview dashboard introduces a dedicated prevention section, displaying essential metrics. You'll find vital indicators such as the number of vulnerabilities detected in pull requests, the tally of alerts resolved through autofix, and the count of secrets proactively blocked. Further, the existing dashboard components for detection and remediation have been refined to seamlessly integrate with this new structure. This comprehensive and actionable view enables your team to continually optimize and fortify your security protocols.

**Comment by ankneis** [comment]
This shipped: https://github.blog/changelog/2024-05-23-code-security-and-secret-scanning-insights-for-your-enterprise-public-beta/

And with GHES 3.14: https://docs.github.com/en/enterprise-server@3.14/admin/release-notes
