### ISSUE TITLE
Enterprise-level CodeQL pull request alerts report

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#974]
### Summary
Elevate your enterprise's security with this new enterprise-level report, designed to proactively monitor and track preventative remediation activities and autofix metrics, ensuring vulnerabilities are addressed swiftly and efficiently. Additionally, this report is also designed to highlight the substantial value and return on investment that GitHub Advanced Security prevention tactics brings to your security operations.

### Intended Outcome
Many security managers struggle to quantify the preventative impact of GitHub Advanced Security, understand the value that autofix delivers and communicate its benefits effectively. Wit this report, you'll have the data-driven metrics at your fingertips to effectively drive prevention strategies, demonstrate impact, and, ultimately, significantly mitigate enterprise risks.

### How will it work?
Introducing a new, comprehensive report that aggregates CodeQL pull request alerts and breaks them down by repository, providing deep insights into your security landscape. This report will feature key metrics, including the most prevalent rules triggering pull request alerts, and detailed breakdowns of alert statuses—unresolved, merged, dismissed, and specifically, those fixed with or without autofix. Additionally, it will track and display trends in pull request alert volumes, offering a historical view that can be filtered extensively to suit your analytical needs.

_Prototype report_
![Image](https://github.com/github/release-assets/assets/94867353/0944849b-a3e2-498a-9677-21bd33643e89)

**Comment by ankneis** [comment]
This shipped with `GHES 3.15`: https://github.blog/changelog/2024-11-12-the-github-enterprise-server-3-15-release-candidate-is-available

**Comment by ankneis** [comment]
Edit to clarify: This feature will be available with the GHES 3.15 general availability release on December 3
