### ISSUE TITLE
 Close reasons trends grouping and filters for the overview dashboard

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#976]
### Summary
With this feature, you can now group alerts by close reasons on the alert trends report and apply filters on the overview page based on close reason. This improvement encompasses alerts from all GitHub security tools—Dependabot, CodeQL, secret scanning—as well as  third-party alerts.

### Intended Outcome
Security managers often grapple with the high volume of closed alerts, making it difficult to extract meaningful insights. Key questions like, "How many alerts were dismissed as false positives?" or "How many were actually remediated?" can now be answered effortlessly. This feature aims to empower security managers to monitor, track, and audit resolved alerts with precision, ultimately enhancing your organization's ability to address and reduce vulnerabilities.

### How will it work?
The updated security overview dashboard will introduce a new "Close Reason" grouping option within the alert trends graph. Additionally, you can apply filters using close reasons on both the dashboard and individual alert pages. For instance, you can display alerts marked as "risk accepted" using the filter `close-reason:risk-accepted`, allowing for a more granular and focused analysis of security alerts.

_New close reason alert trends grouping:_

![Image](https://github.com/github/release-assets/assets/94867353/e04020d2-83e0-47e0-aee2-1b2e528f5027)

**Comment by ankneis** [comment]
We are excited to bring more AI capabilities to GHAS. As a result, this feature’s development is on hold. We appreciate your understanding and welcome your feedback in the [GitHub community](https://github.com/orgs/community/discussions/categories/code-security).
