### ISSUE TITLE
Pre-defined organization roles

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#977]
### Summary

While organization owners can create [custom organization roles](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-peoples-access-to-your-organization-with-roles/about-custom-organization-roles) to control their users' access to the organization, we've found that there are common patterns that most organizations need. These roles will be built in to every GitHub organization, and available to all organizations, both enterprise and free, to provide a "batteries included" least-privilege setup. 

We'll be adding new roles over time as features within GitHub add granular management. At launch, though, we'll have a set of five  organization-wide base roles, which grant read, triage, write, maintain, or admin privileges against _every_ repository in the organization. These can be assigned to organization members as well as organization teams.

**Comment by ankneis** [comment]
This shipped with `GHES 3.15`: https://docs.github.com/en/enterprise-server@3.15/admin/release-notes

**Comment by ankneis** [comment]
Edit to clarify: This feature will be available with the GHES 3.15 general availability release on December 3
