### ISSUE TITLE
Enterprise-level overview dashboard [Public Beta]

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#978]
### Summary
Our current overview dashboard is aggregating and displaying data at the organization level, encompassing all repositories within the organization. To provide a more comprehensive view for larger enterprises, we aim to build an enterprise-level dashboard to aggregate and present data across all organizations within an enterprise. This enterprise-level dashboard will offer a macro view of application security metrics, aiding in broader strategic decisions and analyses.

### Intended Outcome
Enterprise users require the ability to analyze data across their enterprise. This feature will give application security users the ability to view aggregated data from all organizations within my enterprise in a single, unified dashboard so that they can easily compare and analyze metrics at an enterprise scale to make informed, overarching decisions regarding security and development practices.

### How will it work?
Security managers and organization owners will be able to access an overview of code security metrics through the enterprise account page. This dashboard will offer a consolidated view of security metrics across organizations that are currently only available at the organization level.

In cases where users have access to multiple organizations, they will have the flexibility of filtering by organization.

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2024-05-23-code-security-and-secret-scanning-insights-for-your-enterprise-public-beta/

Leaving open to track for GHES release.

**Comment by ankneis** [comment]
This shipped with GHES 3.14: This shipped with 3.14: https://docs.github.com/en/enterprise-server@3.14/admin/release-notes
