### ISSUE TITLE
Actions: Private networking for GitHub-hosted macOS runners

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#982]
### Summary
GitHub is thrilled to announce the availability of private networking for hosted macOS runners. This feature allows users to assign a set of static IPs to a runner or runner group, and also provides the option to use Azure private networking for macOS runners. By executing workflows behind the protection of the Azure Virtual Network, customers can ensure additional network security for workflows that require access to private resources within their network. This will be particularly useful for developers who have enabled IP allow lists, as they can now assign a specific set of static IPs to macOS runners.

### Intended Outcome
GitHub now offers private networking capabilities for hosted macOS runners, which enables users to securely access private resources within their on-prem or cloud-based locations, such as databases, artifactory, storage accounts, or APIs. Developers can enforce network security policies and outbound access rules on the runners, which can help to reduce data exfiltration risks. Additionally, developers can isolate their build traffic from the public internet and route it through their existing private network connections (such as VPN or ExpressRoute). 

### How will it work? 
The process of assigning static IPs or setting up Azure private networking for macOS runners is the same as it is for Ubuntu and Windows runners. For more information, please refer to our documentation.

- [Azure Private Networking](https://docs.github.com/en/enterprise-cloud@latest/admin/configuration/configuring-private-networking-for-hosted-compute-products/configuring-private-networking-for-github-hosted-runners-in-your-enterprise)
- [Assigning static IPs](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/managing-larger-runners#creating-static-ip-addresses-for-larger-runners)

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/

**Comment by ankneis** [comment]
Re-opening - as this has not yet shipped.

**Comment by ankneis** [comment]
This issue is being closed as outdated. For more information, please check out this [Discussion post](https://github.com/github/roadmap/discussions/1014). Stay tuned for new additions to our refreshed public roadmap!

**Comment by ankneis** [comment]
We wanted to provide more details on why we removed this from the roadmap. We continue to plan to bring private networking to macOS runners, but we have removed this from our roadmap for now until we have more certainty on our timeline.

If you’re interested in this feature, please share your feedback in the [GitHub community](https://github.com/orgs/community/discussions/) so we can track interest and consider it in the future.
