### ISSUE TITLE
Actions: Managing Environments at Scale

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#988]
### Summary

GitHub [Environments](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment) are typically used with Actions workflows to describe a general deployment target like production, testing, staging, or development to which an application or service (s) is deployed to. Currently we support “deployment protection rules” which can be configured to protect environments and their associated secrets & variables from getting accessed by unintended deployments.  And also to have more controlled deployment rollouts based on certain predefined criteria evaluated by each of the rules.

However, Developers and DevOps managers often need to centrally configure and manage protection rules on their environments across their teams and applications beyond the GitHub boundaries of organizations and repositories. 

To enable "Management of Environments at Scale",  we are coming up with a new delightful configuration experience for defining and managing groups of Environments across repositories coupled with powerful settings management across Environments.

### Intended Outcome

With this new cross-repo management experience for Environments, Developers and DevOps managers would be enabled to

- group environments within/across repos by adding metadata to environments across repositories in your organization. 
- easily and consistently apply protection rules on groups of environments across repositories in order to have a standard set of configurations and settings across all environments within the group.
- filter deployment views by groups of Environments.

### How will it work?

We are enabling a new central management experience for Environments across repositories by 
- Extending [rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets) to support central configurations on “protected Environments” 
- Supporting [custom properties](https://docs.github.com/en/organizations/managing-organization-settings/managing-custom-properties-for-repositories-in-your-organization) to group Environments and configure rulesets

**Comment by ankneis** [comment]
This issue is being closed as outdated. For more information, please check out this [Discussion post](https://github.com/github/roadmap/discussions/1014). Stay tuned for new additions to our refreshed public roadmap!

**Comment by ankneis** [comment]
We wanted to provide more details on why this issue was removed from the public roadmap. We continue to plan to make it easier to manage GitHub Actions environments at scale through organizations and enterprises. However this work is currently in an exploratory phase, so we have removed it from this roadmap while we develop more certainty on our scope and timelines.
