### ISSUE TITLE
Actions: Manual approvals in workflows

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#99]
**Summary** 
Deploying to production environments often requires a person to approve it, to meet certain security and compliance policies. Manual approvals enable you to control when workflows are allowed to deploy to specific environments by requiring a specific person or team to approve a workflow run before it can proceed.

**Intended Outcome** 
This allows time for manual inspection and verification of the artifacts being deployed.

**How will it work?** 
Finally, organizations will be able to configure rules about approvals such as not allowing the actor that triggered the run to be the same actor that approves it. Or use the API to integrate with existing change control systems.

**Comment by Sid-ah** [comment]
https://github.blog/changelog/2020-12-15-github-actions-environments-environment-protection-rules-and-environment-secrets-beta/
