### ISSUE TITLE
Increase GitHub Enterprise Importer's (GEI) repository size limit to 40GB (Preview)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#993]
### Summary

GitHub Enterprise Importer (GEI) currently imposes the following repository size limits: 
- 10 GB size limit for a Git repository: This limit only applies to the source code. To check if the repository archive is over the limit, use the [git-sizer](https://github.com/github/git-sizer) tool and review the total blob size in the output. 
- 10 GB limit for metadata: The Importer cannot migrate repositories with more than 10 GB of metadata. Metadata includes issues, pull requests, releases, and attachments.

To support the migration of larger repositories to GitHub and between GitHub products, we will be increasing the repository size limits to:
- 40 GB size limit for a Git repository
- 40 GB limit for metadata

### Intended Outcome

Customers will be capable of migrating larger repositories using GEI. In doing so, GitHub migration tooling is expanding to help customers operating large monorepos migrate to GitHub or between GitHub products. 

### How will it work?

This ship will not change how GEI is used. Customers can continue using GEI using the same instructions documented in our [documentation on GitHub Enterprise Importer](https://docs.github.com/en/migrations/using-github-enterprise-importer/understanding-github-enterprise-importer/about-github-enterprise-importer).

**Comment by ankneis** [comment]
Please continue to refer to our updated Public Roadmap for the latest ships, including updates on the continuation of these projects.

**Comment by ankneis** [comment]
We wanted to provide more details on why we removed this from the roadmap. We do intend to increase GEI's repository size limit to 40GB, but we're removing it from this roadmap for now until we have more certainty on our timeline for a public preview.
